### ISSUE TITLE
Unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#100]
This error happens with the seed URL for the site, so no document in the site is processed. What can I do?
```
MC(crawler): 2015-05-05 18:57:27 ERROR - Cannot fetch sitemap: http://valitsus.ee/sitemap_index.xml (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target)
MC(crawler): 2015-05-05 18:57:37 ERROR - Cannot fetch sitemap: http://valitsus.ee/sitemap.xml (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target)
.....
MC(crawler): 2015-05-05 18:57:40 ERROR - Cannot fetch document: http://valitsus.ee/ (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target)
MC(crawler): 2015-05-05 18:57:40 ERROR - MC(crawler): Could not process document: http://valitsus.ee/ (javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target)
com.norconex.collector.core.CollectorException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at com.norconex.collector.http.fetch.impl.GenericDocumentFetcher.fetchDocument(GenericDocumentFetcher.java:148)
    at com.norconex.collector.http.pipeline.importer.HttpImporterPipeline$DocumentFetcherStage.executeStage(HttpImporterPipeline.java:147)
    at com.norconex.collector.http.pipeline.importer.AbstractImporterStage.execute(AbstractImporterStage.java:31)
    at com.norconex.collector.http.pipeline.importer.AbstractImporterStage.execute(AbstractImporterStage.java:24)
    at com.norconex.commons.lang.pipeline.Pipeline.execute(Pipeline.java:90)
    at com.norconex.collector.http.crawler.HttpCrawler.executeImporterPipeline(HttpCrawler.java:213)
    at com.norconex.collector.core.crawler.AbstractCrawler.processNextQueuedCrawlData(AbstractCrawler.java:473)
    at com.norconex.collector.core.crawler.AbstractCrawler.processNextReference(AbstractCrawler.java:373)
    at com.norconex.collector.core.crawler.AbstractCrawler$ProcessURLsRunnable.run(AbstractCrawler.java:631)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.ssl.Alerts.getSSLException(Unknown Source)
```

**Comment by essiembre** [comment]
When trying to access http://valitsus.ee/sitemap_index.xml it the site redirects to https://valitsus.ee/et/sitemap_index.xml and that URL does not lead to a valid sitemap.  It returns a 404 error instead.  If you plan on crawling the site and don't care about the sitemap, you can turn it off in your crawler config:

```xml
<sitemap ignore="true" />
```

**Comment by csaezl** [comment]
I suppose I'll apply your advice. Anyway, why should I care about the sitemap?. In which manner does it contribute to the crawling process?

**Comment by csaezl** [comment]
I've included:
```
      <sitemap ignore="true"
         class="com.norconex.collector.http.sitemap.impl.StandardSitemapResolverFactory">
         <location>http://valitsus.ee/</location>
      </sitemap>
```
There is a warning for robots.txt:
```
WARN - Not able to obtain robots.txt at: http://valitsus.ee/robots.txt
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
The error for the site map has disappeared but the rest remains the same

**Comment by essiembre** [comment]
Sitemaps were invented (by Google) to tell search engine/crawlers what are the URLs making a website that you would like indexed.  It does not mean your site will not get crawled the typical way, but it ensures what you want made searchable is collected.  It can also be used to make pages that are not statically linked from anywhere on your site to be indexed by Google, Yahoo, or Norconex HTTP Collector :-)   Some search sites (Google, Yahoo, etc) even let you submit directly to them a sitemap for your site.  Otherwise, a standard location is to have a file called sitemap.xml a the root or your site (which in turn can point to other sitemap files).  To be crawler friendly, most popular CMS out there will offer ways to generate the sitemap files automatically.  You can easily find more about it online, like [here](http://en.wikipedia.org/wiki/Sitemaps).

The way you have it defined has no impact.  Since you are ignoring sitemaps, this like has no effect: ``<location>http://valitsus.ee/</location>``.  Also, since the ``StandardSitemapResolverFactory`` class is the default one used for sitemaps, you do not have to specify it.  In other words, you should be able to use the shortest form I provided you with: ``<sitemap ignore="true" />``.

Another feature supported by default is the use of Robots text files.  The exact same scenario happens with the redirect.  If your site does not have a robots.txt file, you can turn off support for this standard feature: 
```xml
<robotsTxt ignore="true" />
```
In either case though, while it is normal you get that error, it is not normal that it does not attempt to process your seed URL regardless.  I am marking this issue as a bug for this reason.  

The HTTP Collector needs to be fixed to process the start URLs regardless whether trying to resolve their sitemap.xml or robots.txt files result in an error.

**Comment by csaezl** [comment]
Thank you for your explanation. 

First I tried the short form ```<sitemap ignore="true" />```, but since it didn't solved the issue I tried the long, with the same result

**Comment by essiembre** [comment]
To make sure you are not stuck until a fix, does adding the tag for ignoring robot rules work for you now?

**Comment by martinfou** [comment]
To me it looks like the website has an invalid SSL certificate. Did you try to add it to your local java certificate manager? You might want to give this tutorial a try. http://www.java-samples.com/showtutorial.php?tutorialid=210

**Comment by csaezl** [comment]
I access to the site with Firefox without any issue (you can try). Could I expect the same with the crawler?

**Comment by martinfou** [comment]
Here is a copy of the error message I get when I use Chrome. My theory is that the java jre does not like something about that certificate and you will need to add it  manually to your machine. I can confirm that using Firefox I don't see any errors with the SSL certificate of that site.   
![2015-05-07_0829](https://cloud.githubusercontent.com/assets/4322052/7515389/9709960e-f494-11e4-9578-0e827931935c.png)

**Comment by csaezl** [comment]
To Pascal: I've run the crawler with ```<robotsTxt ignore="true" />``` and ```<robotsMeta ignore="true" />``` and the result is the same

**Comment by csaezl** [comment]
I suppose I can add a certificate right now. But for a crawling production environment is it expected to have to add every certificate with similar issue?. Isn't there a way of circumventing the issue? After all your Chrome has access the page and is showing it.

**Comment by essiembre** [comment]
@csaezl there is an easy way around this.  You can tell the crawler to trust all certificates, even though it is usually not recommended for security purposes (even with browsers). The [GenericHttpClientFactory](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/client/impl/GenericHttpClientFactory.html) class as a flag called ``trustAllSSLCertificates`` that you can turn on (off by default).  In its shortest form, it is as simple as adding this to your crawler config:
```xml
<httpClientFactory>
      <trustAllSSLCertificates>true</trustAllSSLCertificates>
</httpClientFactory>
```

**Comment by csaezl** [comment]
Same behaviour and same issue

**Comment by essiembre** [comment]
When you say "same behavior and same issue", are you saying you get the same robots.txt error: ``WARN - Not able to obtain robots.txt at: http://valitsus.ee/robots.txt`` when you have ``<robotsTxt ignore="true" />`` or is it something else? Just to avoid confusion, can you paste your latest config entries with the latest exception you are getting.  Thanks!

**Comment by essiembre** [comment]
I was able to reproduce.  I disabled sitemap, robots.txt, and got the SSLHandshareException.  The ``trustAllSSLCertificates`` will trust any certificates, but in this case it seems to be a case where the certificate itself cannot be obtained (invalid certification path).   It may be because that site uses outdated security settings as Google Chrome reports.  Will do more investigation.

**Comment by essiembre** [comment]
Turns out the ``trustAllSSLCertificates`` option was not being picked up when defined in the XML config. That has been fixed and is included in a new [snapshot release](http://www.norconex.com/collectors/collector-http/download) that was just made.  I tested with your site and that flag and I no longer have the SSL exception.

**Comment by csaezl** [comment]
It seems to work. Thank you for your support

**Comment by csaezl** [comment]
I've got an error, perhaps not related to the issue itself:
From the log:
```
INFO - Sending 10 documents to Solr for update/deletion.
INFO - Done sending documents to Solr for update/deletion.
INFO - MC (crawler): Crawler finishing: committing documents.
INFO - Committing 0 files
INFO - Sending 7 documents to Solr for update/deletion.
INFO - Done sending documents to Solr for update/deletion.
INFO - MC (crawler): 893 reference(s) processed.
INFO -          CRAWLER_FINISHED
```
From the console:
```
INFO - Sending 10 documents to Solr for update/deletion.
INFO - Done sending documents to Solr for update/deletion.
Exception in thread "pool-1-thread-2" java.lang.OutOfMemoryError: Java heap spaceINFO - MC (crawler): Crawler finishing: committing documents.
INFO - Committing 0 files
INFO - Sending 7 documents to Solr for update/deletion.
INFO - Done sending documents to Solr for update/deletion.
INFO - MC (crawler): 893 reference(s) processed.
INFO -          CRAWLER_FINISHED
```
An Exception happened not shown in the log. I have more demanding crawlers running that don't get out of memory errors, so I'll check the initial conditions for the the test and try again.

**Comment by csaezl** [comment]
I've run the test again and got the same result

**Comment by essiembre** [comment]
You are right this last issue about memory is not related to SSL Certificates.  I moved it to https://github.com/Norconex/collector-http/issues/106

**Comment by essiembre** [comment]
Norconex HTTP Collector 2.2.0 official release is out. It includes this fix. You can download it [here](http://www.norconex.com/collectors/collector-http/download).
