### ISSUE TITLE
Document content in the log

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#101]
Sometimes the content for a document appears in the log, in DOCUMENT_COMMITED_ADD ```...... content=[``` Does it denote anything special?.

**Comment by essiembre** [comment]
If I get your question right, the answer is: not really.  With every events, the "subject" of the event was getting printed as well to help troubleshooting.  That's merely doing a ``toString()`` on the object we feel is responsible for the event trigger.  In the case of a DOCUMENT_COMMITTED_ADD, the subject is the document itself, so that's what gets printed.  With 2.2.0, this was changed so the subject gets printed only if running with DEBUG loglevel to avoid printing to much noise.

**Comment by csaezl** [comment]
It's good news that the content won't be shown in the log if not requested.
