### ISSUE TITLE
referenceFilter and filter tags

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#113]
I have a main config with following lines:
```xml
<referenceFilters>
   #parse("${configdir}/config-reference-filters.xml")
</referenceFilters>
```
config-reference-filters.xml + .properties:
```
filterExtension = "com.norconex.collector.core.filter.impl.ExtensionReferenceFilter"
filterRegexRef  = "com.norconex.collector.core.filter.impl.RegexReferenceFilter"
```

```xml
<filter class="$filterRegexRef" onMatch="include" caseSensitive="false">.*</filter>
```

The collector delivers following error:
```
[Fatal Error] :40:29: Element type "filter" must be followed by either attribute specifications, ">" or "/>".
```

What is wrong with my config: it looks correct. I tried to put regex into ~~ and //, but get the same error.

**Comment by essiembre** [comment]
I am sure you like easy fixes: remove the double quotes in your .properties file. :-)   

Otherwise, with the quotes, after the substitution took place, you end up with (notice the double double-quotes):
```
<filter class=""com.norconex.collector.core.filter.impl.RegexReferenceFilter"" ...
```
FYI, when using ``.properties`` to hold variables, the expected/supported syntax is described [here]( 
http://docs.oracle.com/javase/7/docs/api/java/util/Properties.html#load%28java.io.Reader%29).

**Comment by AntonioAmore** [comment]
Thank you, I'm trying use a good product on a good way.
Yes, removing of double quotes solved the problem -  a kind of hard-to-catch mistakes.
