### ISSUE TITLE
Feature request: recrawl delay

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#127]
While using Last-modified is saving a lot of downloading, there is still a request being made to the server.

So when you are recrawling on a daily basis and crawled a HTML page a few hours ago. Chances are it hasn't changed, but it's still being checked to see if it's modified. On other hand if it's a RSS feed, then chances are it did change. 

So one kind of mechanism could be that you set a max recrawl time in hours for certain mime types. That way you could crawl on an hourly basis and only add the new HTML found in RSS. And old HTML or changed HTML will be updated in 24h max.

Another way is to increment recrawl time with every crawl it hasn't changed (with a max). So it automatically identifies content that needs to be checked often and content that doesn't.

**Comment by essiembre** [comment]
I like this idea.  It won't be for the upcoming 2.2.0, but I am keeping it.

**Comment by OkkeKlein** [comment]
Bump:)

**Comment by essiembre** [comment]
Putting here design considerations from our offline discussion about this issue:
 
* This would apply on incremental crawls only (i.e. not on a fresh crawl).
* When a document is about to be processed, we check the URL cache to see if it was processed in previous run:
  * If not previously processed, we process it.
  * If previously processed, we apply the elapsed time logic by comparing last crawl time with current time.
    * If not ready to be recrawled, we mark the document right away processed/skipped without attempting to download it. It will not be verified again in this crawling session.
    * If ready to be crawled, we proceed as normal.
* These are the different elapsed-time logic we should support for docs that have been previously crawled:
  * Can specify a minimum elapsed time for recrawl, affecting all documents.
  * Can specify a minimum elapsed time different for each doc, based on mime-type of cached URL.
  * Can support change frequency specified in sitemaps for each URLs (but above logic would take precedence).

**Comment by niels** [comment]
This would / will be a great feature!

Two suggestions for the elapsed time logic:

1. Being able to specify different re-crawl times for different URL patterns would also be very useful (perhaps even more-so than for mime-types). For example, I might want to crawl `^http://example.com/forums/.*` more frequently than `^http://example.com/blog/.*` and that in turn more frequently than `^http://example.com/static/.*`.

2. Specifying `-1` to indicate "never re-crawl this site" would also be useful. Perhaps I know that the document will truly never change or I am only interested in doing a one-time import for some types of documents.

  (Of course setting a very high elapsed time requirement would have the same effect but an explicit "never re-crawl this site" setting would communicate the intent more clearly and might allow for some optimizations in the code as well [no need to calculate `last crawl + elapsed time requirement` if the site should  *never* be re-crawled]).

**Comment by OkkeKlein** [comment]
niels,

I think using a regex for recrawl delay is a good idea. You can also use this for mimetypes. So 1 solution fits all.

**Comment by OkkeKlein** [comment]
Shame this was moved to 2.5.0, Still waiting for this feature :)

**Comment by essiembre** [comment]
You will be glad to hear this feature has finally been added to [2.5.0 snapshot release](https://www.norconex.com/collectors/collector-http/download).

This new feature can be configured with the ``recrawlableResolver`` tag.  Its default implementation is [GenericRecrawlableResolver](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/recrawl/impl/GenericRecrawlableResolver.html).  That implementation is enabled by default now and supports sitemap last modified date and change frequency out of the box.  Refer to the javadoc (above link) to find out how you can add your custom "minimum frequency" patterns for recrawls.  You can also specify if you want sitemap directives to be interpreted before yours (default), after, or never. Here is the configuration example from the Javadoc:

```xml
  <recrawlableResolver 
         class="com.norconex.collector.http.recrawl.impl.GenericRecrawlableResolver"
         sitemapSupport="last" >
     <minFrequency applyTo="contentType" value="monthly">application/pdf</minFrequency>
     <minFrequency applyTo="reference" value="1800000">.*latest-news.*\.html</minFrequency>
  </recrawlableResolver>
```

To implement this, the last crawl date and content type had to be added to the crawl data store.  It is recommended you start using 2.5.0 with a "clean" crawl since the crawl data store is not compatible with your former crawls (those new fields are not present).  In addition, if you are using the default crawl store, it has been changed from MapDB to MVStore, which is one more reason to start "clean" (else, you'll have to explicitly configure your ``crawlDataStoreFactory`` back to MapDB or it will create a brand new one for MVStore).  

Please test it and confirm if it works as expected.

**Comment by niels** [comment]
Fantastic!

This does all we need and after preliminary testing seems to work exactly as expected. Thanks, Pascal!

For the benefit of others looking at this, documents not crawled due to a matching `recrawlableResolver` configuration will be logged at verbosity `INFO` as `REJECTED_PREMATURE`.

**Comment by essiembre** [comment]
Thanks for confirming!
