### ISSUE TITLE
Document checksummer custom logics

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#137]
I have a custom importer which perform some operations on the crawled page's text before committing.

I'd like to set page's checksum calculation (to avoid duplicate crawling) from the text, already processed by the importer, for example as MD5. 

I believe current checksummers are executing before import operation. Please tell me, is it possible to implement such flow with current collector-http?

**Comment by essiembre** [comment]
What you describe is already the current behavior.  The default ``<documentChecksummer ...>`` is [MD5DocumentChecksummer](http://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/checksum/impl/MD5DocumentChecksummer.html) and it takes place AFTER the import stage (for the reasons you mention).  Its default behavior is to create a MD5 hash for the checksum using the content (but you can configure it to use fields instead if you prefer).

**Comment by AntonioAmore** [comment]
That's perfect! 

Is the following the correct flow:
- results of the Importer are written to a custom meta-data field;
- a custom checksummer uses the meta-data field for calculations;
- a custom importer also uses the meta-data field.

May I use any random name for meta-data?

**Comment by essiembre** [comment]
The correct flow for checksum, by default is:

* Results of the Importer are written in both metadata fields and content stream. Depends what you do exactly.
* A custom checksummer can use anything (meta-data fields and/or content stream) to create a checksum.  But the default checksumer uses the content stream only and creates a MD5 hash with it.

What do you mean by "custom Importer"?   Do you mean you want to use the generated checksum in one of your importer handler (like a tagger, transformer, filter, etc)?  Since the document checksummer takes places AFTER the import, you cannot really do this.  But there are many workarounds.  Like doing a checksum in a custom Importer Tagger that store it in a field of your choice.   Then have a custom document checksummer return that field for its checksum value.

If you mean something else, please elaborate.

**Comment by AntonioAmore** [comment]
To be more correct, I'm using a custom document transformer with a method:
```java
protected void transformTextDocument(String string, Reader reader, Writer writer, ImporterMetadata im, boolean bln) throws IOException {
...
writer.write(transformedText);
...
```
and would like the checksummer use the transformed text for the visited pages database. Does MD5 checksummer work in such case, or I should write my own one?

**Comment by essiembre** [comment]
Yes it will.  The document checksummer uses the content of the document after the Importer module did whatever it wanted to do with it.  That means, the content used to generate the checksum will have your transformations.  You should not need to write your own.

**Comment by AntonioAmore** [comment]
Thanks a lot for your answer! Seems the issue may be closed.

**Comment by essiembre** [comment]
You are welcome!
