### ISSUE TITLE
Web page candidate to be rejected? 

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#139]
Crawling web sites I've found out some web pages (really large groups of web pages) that have not real contents, but that the crawler has to commit  because they exist. For example, calendars. One sample:
```
http://agcex.org/_sites/teleformacion/calendar/view.php?view=month&cal_d=1&cal_m=1&cal_y=1057
```
This seems to be an e-learning platform that shows courses by date. This specific page should contain the courses for year 1057 (jan, 1). I can't imagine how many worthless pages the crawler has committed.

The question: In the crawler world, are this kind of pages identified and procedures defined to get rid of them?. It sounds difficult to me but (hopefully) perhaps not to you. Is there any literature on the subject?.

**Comment by essiembre** [comment]
Crawling sites with calendars is a frequent challenge.  Unless you want to simply eliminate them via URL filtering rules, you sometimes have to get creative.  Luckily, there are a few things that can help you.

**Depth:**
``maxDepth`` is a very useful flag to avoid infinite crawl loop caused by calendars (or others).  Make sure to put a reasonably low number here (like 10).  That flag alone can be acceptable for most looping scenarios and you may not need to do anything else.

**Reject small docs:**
You say these calendar pages do not contain much. If you strip their header and footer, they will contain even less.  You can use the following combination to eliminate documents that are too small (e.g. < 100 bytes) to be considered valid docs:
```xml
<tagger class="com.norconex.importer.handler.tagger.impl.DocumentLengthTagger" field="docSize" />
<filter class="com.norconex.importer.handler.filter.impl.NumericMetadataFilter"
    onMatch="exclude" field="docSize" >
  <condition operator="lt" number="100" />
</filter>
```

**Strip calendar pages that are too old/future:**
This one involves knowing the calendar URL structure upfront. You can limit crawling of these calendars to certain years (or else) via a regex filter.  It means you'll have to update it once in a while though, which is not ideal.  For example, assuming current year is 2015, you can prevent following other years this way:
```xml
<filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude">
      .*(cal_y=2014|cal_y=2016).*
</filter>
```
You can also extract the year from the URL in a numeric field, and then user a numeric filter to exclude it.

**Page specifics:**
Look at something you can use in the calendar page to eliminate bad ones.  For instance, in your URL sample above, I found this: ``<span class="current">January 1057</span>``.   Using a combination of handlers like the second suggestion above, you can extract that date text using a TextBetweenTagger, or a TextPatternTagger (and optionally convert that date to another format using a DateFormatTagger).  Then you can use a DateMatadataFilter to exclude old years.  Like this:

```xml
<filter class="com.norconex.importer.handler.filter.impl.DateMetadataFilter"
          onMatch="include" field="calendarYear">
      <condition operator="ge" date="TODAY-1y" />
      <condition operator="le" date="TODAY" />
</filter>
```
You can also use the URL pattern instead to extract the year (and month).  This may actually be a faster and safer approach.  This method has the advantage of not having to hard-code a date in your confirm.  But like the previous suggestion, it implies you know how a calendar is built on a site upfront (so not a one-size-fit-all solution for all sites).

Hopefully the above suggestions will get you somewhere.  Maybe you can think of other things.  For instance, maybe you have noticed that calendar pages with no content always have a string that says so or something like that.  You can exclude pages based on whether that string is found in each page.

Let me know how that goes.  Good luck!

**Comment by csaezl** [comment]
Are there other types of pages, candidates to be rejected?. Can you give me any reference to get more information?

**Comment by essiembre** [comment]
That's really on a case-by-case basis.  Let's divide crawling exercises into two categories: horizontal and vertical.  

An horizontal crawl is when you scrape the surface of tons of different web sites with a short maximum depth and limited shared tuning options (since they are all different).

A vertical crawl is when you focus on a site (or handful of sites) that you know well and you want to perform specialized activities on it to get the most out of your crawl.

You usually have to compromise based on which one you are after (volume vs precision/quality).  You usually can't have both without a great deal of effort.

I do not have specific references that comes to mind, but if you are after an horizontal crawl, here are some generic ideas that are easy to implement:

* Exclude all URLs with these extensions: jpg,gif,png,ico,css,js  + whatever else you do not want.
* Exclude URLs with a query string, if you suspect most are dynamic applications that produce no valuable content or only produce content found as static pages linked elsewhere (like in index or listing pages).
* You can also opt to reject (at your own risk) a few patterns often associated with pages you don't want to crawl.  If you apply this at large, you will reject a few good documents though. Like URLs containing ``/search``, ``/feed/``, ``sort=``, ``query=``, etc.

If you are doing is more a vertical crawl, nothing beats a good analysis of your crawled content to find out patterns to exclude.  I will take a few passes to get it right, that's OK.  The more you spend time refining, the better your content will become.  Once you are done, an next step could be to start eliminating headers and footers from crawled content to make it super-clean.   It depends how many sites you have to do, and much time you have as well. :-)

Lastly but maybe most importantly, it is to try to solve the above problem that sitemaps were invented.  If you respect sitemaps and you put your maximum depth to 0, only documents in the sitemap will be crawled.  You have no extra logic to apply then.

**Comment by csaezl** [comment]
Thank you very much for your information
