### ISSUE TITLE
Issue with redirect/canonical?

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#142]
Crawling ``` http://caminosdecultura.blogspot.com.es/``` with:
```
	  <canonicalLinkDetector ignore="false"> </canonicalLinkDetector>
      <httpClientFactory>
        <ignoreExternalRedirects>true</ignoreExternalRedirects>
      </httpClientFactory>	  
      <linkExtractors>
        <extractor ignoreExternalLinks="true" />
      </linkExtractors>	  
      <startURLs>
        <url>http://caminosdecultura.blogspot.com.es/</url>      
      </startURLs>
```
I get no document crawled:
```
MC (crawler): 2015-09-17 19:05:01 INFO - MC (crawler): RobotsTxt support: false
MC (crawler): 2015-09-17 19:05:01 INFO - MC (crawler): RobotsMeta support: true
MC (crawler): 2015-09-17 19:05:01 INFO - MC (crawler): Sitemap support: false
MC (crawler): 2015-09-17 19:05:01 INFO - MC (crawler): Canonical links support: true
MC (crawler): 2015-09-17 19:05:02 INFO -           CRAWLER_STARTED
MC (crawler): 2015-09-17 19:05:02 INFO - MC (crawler): Crawling references...
MC (crawler): 2015-09-17 19:05:03 INFO -          DOCUMENT_FETCHED: http://caminosdecultura.blogspot.com.es/
MC (crawler): 2015-09-17 19:05:04 INFO -        REJECTED_CANONICAL: http://caminosdecultura.blogspot.com.es/
MC (crawler): 2015-09-17 19:05:04 INFO - Ignoring external redirect: http://caminosdecultura.blogspot.com/ -> http://caminosdecultura.blogspot.com.es/
MC (crawler): 2015-09-17 19:05:04 INFO -       REJECTED_BAD_STATUS: http://caminosdecultura.blogspot.com/
MC (crawler): 2015-09-17 19:05:04 INFO - MC (crawler): Crawler finishing: committing documents.
MC (crawler): 2015-09-17 19:05:04 INFO - MC (crawler): 2 reference(s) processed.
MC (crawler): 2015-09-17 19:05:04 INFO -          CRAWLER_FINISHED
MC (crawler): 2015-09-17 19:05:04 INFO - MC (crawler): Crawler completed.

```
So, I try to crawl ``` http://caminosdecultura.blogspot.com/``` instead, thinking that should cincunvent the problem, but I get:
```
MC (crawler): 2015-09-17 19:28:24 INFO - MC (crawler): RobotsTxt support: false
MC (crawler): 2015-09-17 19:28:24 INFO - MC (crawler): RobotsMeta support: true
MC (crawler): 2015-09-17 19:28:24 INFO - MC (crawler): Sitemap support: false
MC (crawler): 2015-09-17 19:28:24 INFO - MC (crawler): Canonical links support: true
MC (crawler): 2015-09-17 19:28:24 INFO -           CRAWLER_STARTED
MC (crawler): 2015-09-17 19:28:24 INFO - MC (crawler): Crawling references...
MC (crawler): 2015-09-17 19:28:25 INFO - Ignoring external redirect: http://caminosdecultura.blogspot.com/ -> http://caminosdecultura.blogspot.com.es/
MC (crawler): 2015-09-17 19:28:25 INFO -       REJECTED_BAD_STATUS: http://caminosdecultura.blogspot.com/
MC (crawler): 2015-09-17 19:28:25 INFO - MC (crawler): Crawler finishing: committing documents.
MC (crawler): 2015-09-17 19:28:25 INFO - MC (crawler): 1 reference(s) processed.
MC (crawler): 2015-09-17 19:28:25 INFO -          CRAWLER_FINISHED
MC (crawler): 2015-09-17 19:28:25 INFO - MC (crawler): Crawler completed.
```
What do you advice me to do in this situation to get the domain crawled?.

**Comment by essiembre** [comment]
That's an odd site behavior.  You get this issue because you want to stick to a domain with the flags for ignoring external links and external redirects, but the site has a canonical link that is on a different domain:

``<link href='http://caminosdecultura.blogspot.com/' rel='canonical'/>``

That's a .com domain, but it will in turn redirect to the domain matching your location (I get .ca in my case).

One of these two options should do it for you:

* Ignore canonical link instructions: ``<canonicalLinkDetector ignore="true" />``.  That way it will not follow the canonical link instruction found in the page and stick to the .es domain.  But since I see in the page that some links are .es and some are .com... it may not be enough, so try the next one:
* Set to ``false`` these two: ``<ignoreExternalRedirects>false</ignoreExternalRedirects>`` and  ``<extractor ignoreExternalLinks="false" />``.  Then rely on regular reference filters or importer filter to make sure you only stay on domains you support (a mix of .es and .com).

If you know all pages can be accessed either way (.com or .es), then you can use the [GenericURLNormalizer](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/impl/GenericURLNormalizer.html) search and replace feature to replace .com domains to .es before they are fetched (or the other way around).

**Comment by csaezl** [comment]
Thank you for your advice.

**Comment by essiembre** [comment]
For the record, ``ignoreExternalRedirects`` and ``ignoreExternalLinks`` have been replaced in favor of:

```xml
 <startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
```
