### ISSUE TITLE
CircularRedirectException and URLs with accented letters

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#146]
Crawling  ```http://gobiernoextremadura.tumblr.com/```, I've gotten several thousand errors like the three samples below:
```
MC (crawler): 2015-09-20 17:16:14 ERROR - Cannot fetch document: http://gobiernoextremadura.tumblr.com/post/111176119745/la-nueva-edición-de-encuentra-capital-cierra-la (null)
MC (crawler): 2015-09-20 17:16:14 INFO -            REJECTED_ERROR: http://gobiernoextremadura.tumblr.com/post/111176119745/la-nueva-edición-de-encuentra-capital-cierra-la
MC (crawler): 2015-09-20 17:16:14 ERROR - MC (crawler): Could not process document: http://gobiernoextremadura.tumblr.com/post/111176119745/la-nueva-edición-de-encuentra-capital-cierra-la (org.apache.http.client.ClientProtocolException)
com.norconex.collector.core.CollectorException: org.apache.http.client.ClientProtocolException
...
Caused by: org.apache.http.client.CircularRedirectException: Circular redirect to 'http://gobiernoextremadura.tumblr.com/post/111176119745/la-nueva-ediciÃ³n-de-encuentra-capital-cierra-la#_=_'
...
...
MC (crawler): 2015-09-20 17:16:15 ERROR - Cannot fetch document: http://gobiernoextremadura.tumblr.com/post/111186372280/educación-invertirá-más-de-62-millones-de-euros (null)
MC (crawler): 2015-09-20 17:16:16 INFO -            REJECTED_ERROR: http://gobiernoextremadura.tumblr.com/post/111186372280/educación-invertirá-más-de-62-millones-de-euros
MC (crawler): 2015-09-20 17:16:16 ERROR - MC (crawler): Could not process document: http://gobiernoextremadura.tumblr.com/post/111186372280/educación-invertirá-más-de-62-millones-de-euros (org.apache.http.client.ClientProtocolException)
com.norconex.collector.core.CollectorException: org.apache.http.client.ClientProtocolException
...
Caused by: org.apache.http.client.CircularRedirectException: Circular redirect to 'http://gobiernoextremadura.tumblr.com/post/111186372280/educaciÃ³n-invertirÃ¡-mÃ¡s-de-62-millones-de-euros#_=_'
...
...
MC (crawler): 2015-09-20 17:51:07 ERROR - Cannot fetch document: http://gobiernoextremadura.tumblr.com/post/68971312568/convocadas-las-ayudas-para-la-gesti&oacute;n-de-libros (null)
MC (crawler): 2015-09-20 17:51:07 INFO -            REJECTED_ERROR: http://gobiernoextremadura.tumblr.com/post/68971312568/convocadas-las-ayudas-para-la-gesti&oacute;n-de-libros
MC (crawler): 2015-09-20 17:51:07 ERROR - MC (crawler): Could not process document: http://gobiernoextremadura.tumblr.com/post/68971312568/convocadas-las-ayudas-para-la-gesti&oacute;n-de-libros (org.apache.http.client.ClientProtocolException)
com.norconex.collector.core.CollectorException: org.apache.http.client.ClientProtocolException
...
Caused by: org.apache.http.client.CircularRedirectException: Circular redirect to 'http://gobiernoextremadura.tumblr.com/post/68971312568/convocadas-las-ayudas-para-la-gestiÃ³n-de-libros#_=_'
```
It seems they have to deal with accented letters inside the URL, but I'm not sure.

**Comment by essiembre** [comment]
Redirect handling was redone in such a way that circular redirects can no longer happen (it would stop processing the page instead).

For your site it now works.  For some reason, when I tried to decode the URL escaped characters it did not work. As a result you may see accented characters that appear encoded badly in the logs for some URLs, but when they are accessed, they work.

The fix is in the [latest snapshot](https://www.norconex.com/collectors/collector-http/download).

**Comment by csaezl** [comment]
Testing with:
```
      <startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
		         <url>http://gobiernoextremadura.tumblr.com</url>
      </startURLs>
```
I get a lot of ```REJECTED_REDIRECTED:``` as:
```
REJECTED_REDIRECTED: http://gobiernoextremadura.tumblr.com/post/110805697240/la-plataforma-de-la-infancia-de-espa&ntilde;a-propone
```

**Comment by essiembre** [comment]
That is OK.  A URL that is redirected is now rejected and its target URL is being queued for processing instead.

**Comment by csaezl** [comment]
As for the "accented characters that appear encoded badly", they do look very strange. A sample from the log file:
```
       REJECTED_REDIRECTED: http://gobiernoextremadura.tumblr.com/post/110736292085/ocho-j&oacute;venes-de-etnia-gitana-reciben-la
...
          DOCUMENT_FETCHED: http://gobiernoextremadura.tumblr.com/post/110736292085/ocho-jÃ³venes-de-etnia-gitana-reciben-la#_=_
       CREATED_ROBOTS_META: http://gobiernoextremadura.tumblr.com/post/110736292085/ocho-jÃ³venes-de-etnia-gitana-reciben-la#_=_
            URLS_EXTRACTED: http://gobiernoextremadura.tumblr.com/post/110736292085/ocho-jÃ³venes-de-etnia-gitana-reciben-la#_=_
         DOCUMENT_IMPORTED: http://gobiernoextremadura.tumblr.com/post/110736292085/ocho-jÃ³venes-de-etnia-gitana-reciben-la#_=_
    DOCUMENT_COMMITTED_ADD: http://gobiernoextremadura.tumblr.com/post/110736292085/ocho-jÃ³venes-de-etnia-gitana-reciben-la#_=_
```
Being the original:
```
http://gobiernoextremadura.tumblr.com/post/110736292085/ocho-jóvenes-de-etnia-gitana-reciben-la
```
From ```REJECTED_REDIRECTED``` to the following group of events, a change is made converting
```&oacute;``` to ```Ã³``` and ```#_=_``` is added to the right end. 

Since the URL is the ID for the document, the result of such a conversion (included from ```ó``` to ```&oacute;```) makes the ID meaningless (or unintelligible) when used in a product like Solr.

So, since the browsers are able to access web pages with an URL that contains words such us ```jóvenes```, could it be possible that the normalization proccess don't normalize accented characters?. Or any other solution that don't apply extreme changes.

**Comment by essiembre** [comment]
Turns out URLs were not percent-encoded properly before fetching.  UTF-8 should be used for this according to W3C specs.  I fixed it to use UTF-8 percent-encoding and the pages with accented characters I tried got crawled right away, without any redirect involved, and they keep their original characters when shown un-encoded.

I made a [new snapshot](https://www.norconex.com/collectors/collector-http/download) with this fix.

**Comment by csaezl** [comment]
It seems to work fine with accented characters:
```
DOCUMENT_COMMITTED_ADD: http://gobiernoextremadura.tumblr.com/post/66182247538/más-de-160-matronas-extremeñas-participan-en
```
but sometimes ```#_=_``` is still added to the right end:
```
DOCUMENT_COMMITTED_ADD: http://gobiernoextremadura.tumblr.com/post/111200837700/extremadura-muestra-el-proyecto-de#_=_
...
DOCUMENT_COMMITTED_ADD: http://gobiernoextremadura.tumblr.com/post/111171162800/el-gobex-trabaja-en-la-puesta-en-marcha-de-un#_=_
...
DOCUMENT_COMMITTED_ADD: http://gobiernoextremadura.tumblr.com/post/111171161970/fundesalud-publica-tres-ofertas-de-trabajo-para#_=_
```

**Comment by essiembre** [comment]
The ``#_=_`` is added by the site when doing a redirect, not by the Collector.  It is apparently something several sites (Facebook, Tumbler, etc) do in order to "kill a 'sticky' URI fragment which the browser carries through chain of 302 redirects".  That's the info I could get on this behavior after a quick research.

By default the ``GenericLinkExtractor`` will always remove the fragment part unless you have ``keepFragment=true``.  Unfortunately this stripping is not performed when handling redirects at the moment.  I think the possibility should be introduced, but in the meantime, I would configure the ``GenericURLNormalizer`` with the ``removeFragment`` normalization rule.

**Comment by csaezl** [comment]
Now it works fine. Thank you

**Comment by essiembre** [comment]
Thanks for confirming!
