### ISSUE TITLE
How can I display the "content" field and also successful process all content into Apache Solr?

### ISSUE THREAD

**Issue by mitchelljj** [Norconex/collector-http#148]
I am able to successfully crawl my website using the FileSystemCommitter

I am also able to successfully crawl my website using the SolrCommitter with the additional sourceContentField and targetContentField tags but that causes the "content" field to not display.

So I modified SolrCommitter by eliminating the sourceContentField and targetContentField tags so now the "content" field does display but now the web crawl does not successful process all content into Apache Solr sometimes saying "Rejected_ERROR" for one of the URLs and also "Cannot index document batch to Solr"

How can I display the "content" field and also successful process all content into Apache Solr?

**Comment by essiembre** [comment]
Unless you configured it differently, the content should always be passed to Solr.  If you define a ``sourceContentField``, the metadata field matching the name you give will be used as opposed to the document "body".  In a typical scenario, you don't specify a ``sourceContentField``.  

Since you sometimes get it, I supposed it is defined in your Solr schema?  

As for the rejection, have a look a the ``classes/log4j.properties`` file. You can change the log levels to DEBUG where appropriate. It should give your more insights as to what went wrong.  Especially this one:
```
log4j.logger.CrawlerEvent.REJECTED_ERROR=DEBUG
```

Have you checked your Solr logs?  I suspect the error comes from Solr. For instance, it maybe receiving fields that it considers invalid (e.g. not in your schema, or invalid format).

You may want to reduce the batch size sent to Solr just in case Solr feels it's too big, but I doubt this is the problem.

**Comment by mitchelljj** [comment]
I just checked my solr.log file and I get the below error.  So I either
have to trim the content field before it goes to Solr, or change Solr to
allow larger field contents.

John

Caused by: java.lang.IllegalArgumentException: *Document contains at least
one immense term in field="content" (whose UTF8 encoding is longer than the
max length 32766), all of which were skipped.  Please correct the analyzer
to not produce such terms.  The prefix of the first immense term is: '[10,
10, 10, 10, 10, 10, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 10, 10, 10, 9,
9, 9, 9, 9, 9, 9, 10, 10, 9, 83]...', original message: bytes can be at
most 32766 in length; got 74742*

       at
org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:671)

       at
org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:344)

       at
org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:300)

       at
org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:234)

       at
org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:450)

       at
org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1475)

       at
org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:239)

       at
org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:163)

       ... 58 more

Caused by:
org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: *bytes
can be at most 32766 in length; got 74742*

       at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:284)

       at
org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:150)

       at
org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:661)

       ... 65 more

On Tue, Sep 22, 2015 at 11:57 AM, Pascal Essiembre <notifications@github.com
> wrote:

> Unless you configured it differently, the content should always be passed
> to Solr. If you define a sourceContentField, the metadata field matching
> the name you give will be used as opposed to the document "body". In a
> typical scenario, you don't specify a sourceContentField.
>
> Since you sometimes get it, I supposed it is defined in your Solr schema?
>
> As for the rejection, have a look a the classes/log4j.properties file.
> You can change the log levels to DEBUG where appropriate. It should give
> your more insights as to what went wrong. Especially this one:
>
> log4j.logger.CrawlerEvent.REJECTED_ERROR=DEBUG
>
> Have you checked your Solr logs? I suspect the error comes from Solr. For
> instance, it maybe receiving fields that it considers invalid (e.g. not in
> your schema, or invalid format).
>
> You may want to reduce the batch size sent to Solr just in case Solr feels
> it's too big, but I doubt this is the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Norconex/collector-http/issues/148#issuecomment-142332567>
> .
>



-- 
John J. Mitchell

**Comment by essiembre** [comment]
Are you using a dynamic schema, or did you create one yourself?  Because when using a dynamic one, Solr tries to guess each field types but when in doubt, it defaults to "string".  Unfortunately, strings are limited in Solr.  I recommend you use a fulltext field instead.  It is probably what you want anyway to perform efficient searches against the content.  Either you create a content field that is a fulltext field in your schema, or maybe specify a ``targetContentField`` that matches the field pattern defined for a fulltext field in your schema (e.g. content_t).

**Comment by mitchelljj** [comment]
I am using a dynamic schema so I added the "content" field with the type of "text_general" (see below) before starting to loading any data into Apache Solr and now everything correctly loads into Apache Solr. 

curl -X POST -H 'Content-type:application/json' --data-binary '{ "add-field":{ "name":"content", "type":"text_general" } }' http://localhost:8983/solr/gettingstarted/schema
