### ISSUE TITLE
Duplicated Content-Type meta data

### ISSUE THREAD

**Issue by leonardsaers** [Norconex/collector-http#155]
Http-collector pushes duplicated Content-Type information.

I think this is because the crawler discovers Content-Type both from the content-type meta field and the crawler generated field Content-Type-Hint.

```html
<meta http-equiv="content-type" content="text/html;charset=utf-8"/> 
```

Could it be that those fields are both represented as Content-Type?

**Comment by essiembre** [comment]
It is possible content-type is found or detected in more than one location.  ``document.contentType`` is the one the Importer module will store.  Are you saying you see two values stored under the same field name?  If that's causing you trouble, you can use [ForceSingleValueTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ForceSingleValueTagger.html) to keep only one.

**Comment by essiembre** [comment]
Do you still need help with this one?

**Comment by leonardsaers** [comment]
It solved the problem for now. But I'm still not sure why there are two Content-Type fields. Could it be that Content-Type-Hint is copied to the field Content-Type. If that's the case, should Content-Type-Hint be copied to Content-Type if a value for Content-Type already exists?

I will try to verify the other issues in the beginning of the coming week.

**Comment by essiembre** [comment]
There is no special treatment of Content-Type-Hint that I am aware of.

You have not mentioned which page that was, but if you say there is a ``<meta http-equiv="content-type" ...`` tag present, I bet that's the cause.  Because the crawler will store all HTTP Header fields AND HTML meta tag fields.  So you probably have Content-Type in both the HTTP Response (usually always there) and the meta tag.

Both the [GenericMetadataFetcher](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/GenericMetadataFetcher.html) and the [GenericDocumentFetcher](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/GenericDocumentFetcher.html) classes offer an optional ``<headersPrefix>`` tag, which allows you to prefix extracted header or metadata values with a value of your choice.  This could help avoid duplicates as well.  

But if you have no need to keep both and you are not concerned they may be different, and since people often prefer to keep the actual names in there, sticking to ``ForceSingleValueTagger`` may be best.

Make sense?

**Comment by leonardsaers** [comment]
Thanks for the reply. It is as you suspected. Content-Type is given both in HTTP Header and as meta tag. Then, this is not an issue. ForceSingleValueTagger also works for me.

**Comment by essiembre** [comment]
Great.  For consistency and more reliability, a suggestion is to rely on fields added by the Collector/Importer when available.  Those are ``collector.*`` and ``document.*`` fields. For instance, the Importer makes sure to always add ``document.contentType`` and it will always be single-value (unless you add to it yourself on purpose).
