### ISSUE TITLE
One MongoDB database as data store for all the crawlers

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#158]
It seems that when using MongoDB as crawl data store, every time the crawler is run, the MongoDB data base is emptied.

I'd like to have a single data store for all the crawlers' configurations. Is that possible?

**Comment by essiembre** [comment]
Yes, each crawler creates and uses its own Mongo database.  They should be isolated from each other. This means the same Mongo installation can be used for several crawlers.  By default the crawler ID is used as the database name. 

Are you saying restarting one collector wipes out data in Mongo created by another collector?  Unless you have specified the same Mongo database name for all your crawlers, this should not happen.

**Comment by csaezl** [comment]
In my tests I use the same name for the crawler, that is, for the MongoDB database. In fact I use just one config file an change the URL to process different sites. But that's just for testing.

If I had just a crawler per site, they could be a lot of MongoDB databases. I 'm not sure if this is a good strategy. I prefer any number of documents not of databases.

While testing I've seen you use ```cached``` database. What if several collectors run at the same time (against different databases)?. Do they share ```cached``` database?. Do they all initialize ```cached``` database?. Do they use different ```cached``` databases?.

**Comment by essiembre** [comment]
All crawlers run in isolation on purpose. So they should all have different Mongo database, different cache, etc.

A crawler will never query data produced by another crawler, so there is no need to merge the data. Providing isolation by having one database per crawler is the safest route to avoid conflicts, facilitate collector upgrades, simplify troubleshooting, enable the possibility to have different security per crawler, facilitate scaling MongoDB horizontally, etc.  Not to forget, it should also increase query speed since each database can run separately (even on different cluster or hardware) and will each be significantly small compared to if they were all merged into one.

Also, one can have several versions of the HTTP Collector running or be using different collectors (like Filesystem Collector). Each may end up saving and modify different fields in a a different way so sharing the same database is risky and error-prone.  Also, when dealing with millions of docs, it is easier to reorganize your Mongo cluster if the data is already separated. 

For all of the above reasons, we have no plan to change this.

**Comment by csaezl** [comment]
Ok. Is it possible to have several databases defined, one per crawler, and update them at the same time, that is several crawlers running at the same, all in the same machine?

**Comment by essiembre** [comment]
Yes, this should not be a problem.  Are you running into issues doing that?

**Comment by csaezl** [comment]
No. Just to be sure.

**Comment by essiembre** [comment]
Can we close then?  You can try it before if you prefer.

**Comment by csaezl** [comment]
Please, close it
