### ISSUE TITLE
Dot Segments: REJECTED_BAD_STATUS

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#173]
Crawling without ```removeDotSegments``` in ```<urlNormalizer>``` I get some URLs rejected, as the one below:
```
REJECTED_BAD_STATUS: http://www.gobex.es/web/../../../../filescms/web/uploaded_images/instalaciones_presidencia/_JAM8665.jpg
```
Chrome converts it to: 
```
http://www.gobex.es/filescms/web/uploaded_images/instalaciones_presidencia/_JAM8665.jpg
```
and shows the image. I've tried with ```removeDotSegments``` and what is rejected is:
```
REJECTED_BAD_STATUS: http://www.gobex.es/web/../../../filescms/web/uploaded_images/instalaciones_presidencia/_JAM8665.jpg
```
How can I have the URL not rejected?

**Comment by essiembre** [comment]
Turns out the implementation logic for when there are more ``/../`` present than there are parent segments in a URL was not the right one.  I re-implemented the ``moveDocSegments`` to follow the algorithm prescribed by <a href="http://tools.ietf.org/html/rfc3986#section-5.2.4">RFC3986</a>.
 
I also added 27 new unit tests for this. 

The latest [snapshot release](https://www.norconex.com/collectors/collector-http/download) has this fix. Please test.

**Comment by csaezl** [comment]
It works fine. Thank you very much
