### ISSUE TITLE
startURLs section possible issue

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#174]
if  url contains non-HTML-encoded ampersands (```&``` instead of ```&amp;```, etc.) a SAX exception is dropped. Ampersand  is a part of XML language, but it is not so rare case having that symbol in urls not encoded to HTML entity.

```xml
<startUrls>
<url>http://www.somesite.com?param1=1&param2=2...</url>
...
```

**Comment by essiembre** [comment]
This is the intended behavior and will not change.  The configuration file target format is XML so ampersands have to be XML-escaped just like you need to in any XML you write (``&amp;``).  This is mandated by XML specifications and it is normal for an XML parser to fail on this. 

If you find it too troublesome to convert your ``&`` to ``&amp;`` in the config, you can use a ``<urlsFile>`` instead of storing your URLs directly in the config, or you can store your URLs within CDATA, like this:

```xml
<url><![CDATA[http://www.somesite.com?param1=1&param2=2...]]></url>
```

The CDATA is the standard way in XML to store any arbitrary text without the need for escaping.  You can also use it anywhere else in the config, like regular expressions or else.

**Comment by AntonioAmore** [comment]
Thank you for a quick reply. Yes, ```<urlsFile>``` and CDATA look like a good option.
