### ISSUE TITLE
HTTP header Etag support

### ISSUE THREAD

**Issue by jaanuska** [Norconex/collector-http#182]
Hi,

Does the crawler module support the HTTP ETag entity tag and others headers related to this? I want to mirror a fairly big web portal repeatedly and do not want to re-download files from a server if files are the same and not modified since the last fetch. HTTP/1.1 protocol describes headers like ETag, If-Modified-Since, If-Match exactly for these cases.
Do I understand correctly that the metadataChecksummer tag in configuration xml files is not the same thing?

**Comment by essiembre** [comment]
No, it currently does not support ETag and metadataChecksummer is not the same thing (but could be very similar).  I am marking this as a feature request.  In the meantime you may have a few options.

Since many sites do not support ETag, the crawl checkum mechanism is probably the safest as a catch-all solution.  The checksum does mean a hit on the server for each URL though (so would the ETag) but you can have it trigger a HTTP HEAD request to find out if a page has changed (using the last modified date or else), which can minimize bandwidth a bit like Etag would.  There is also another feature request to not even try download a page if it does not change often, or if it not enough time has passed since the last time it was downloaded (check #127).

If you know a web site supports ETag, you can verify it the Etag is also returned when you do a HTTP HEAD request.  If so, you can use the [GenericMetadataChecksummer](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/checksum/impl/GenericMetadataChecksummer.html) to use the ETag field/value as the checksum.  If the value is the same the second time a document is accessed, it will be flagged as "unmodified" and the more costly HTTP GET request will never be triggered.  In a way, that's like having the crawler apply the Etag logic as opposed to the server.

Hopefully these alternatives can work for you until full Etag support is put in place.

**Comment by essiembre** [comment]
Latest 3.0.0 snapshot now supports ETag by default when using the default `GenericHttpFetcher`.  Can be disabled by adding this to the fetcher config: 

```xml
<disableETag>true</disableETag>
```
