### ISSUE TITLE
Get original url before redirection as Metadata

### ISSUE THREAD

**Issue by csauvanet** [Norconex/collector-http#184]
Hi collector-http community,

As previous advice of Pascal, I open a ticket for documentation purpose.
I am really happy with the collector-http, and can use it with success. I have the following configuration question:

I am tweaking my crawler with some particular details now:
- I deal with links as they exist before redirection, and I prepare context with these links in my committer.
- When the actual link document is visited (Add method of my ICommitter), it is coming with the final URL, but I also need to know the original URL before redirection.

I am trying to write a configuration for the collector to save the original URL when receiving a redirection (in my case HTTP 302 "found"), and add it to the HTTP header meta-data of the final document (i.e. into Properties object).

I am not sure if I should do that with:
- a new IHttpMetadataFetcher or extend GenericMetadataFetcher, reading the javadoc I am not sure on how to use it ?
- a new IHttpDocumentFetcher or extend GenericDocumentFetcher. For instance accept the redirect code, and further process the 302 request.
- set option setKeepReferrerData(true) to GenericLinkExtractor, then getting the HttpMetadata.COLLECTOR_REFERRER_LINK_TAG to find back the original URL.

If you have a recommendation, you are welcome.
Could it be a good idea to have this information by default in the Header Metadata ?

Thanks and best regards
Colin

**Comment by csauvanet** [comment]
Hi,

Finally, I simply extended the GenericMetadataFetcher with my own class, and added the fetchHTTPHeaders url parameter to the Properties, with my custom key (at this moment, the url parameter is still the url before redirection).

It looks to be fine so far.

Thanks and best regards.
Colin

**Comment by essiembre** [comment]
I am glad you found a way to make it work the way you want.  

I once thought of storing the original URL in its own metadata field, but I had an issue with this idea.  See, there could be many different original URLs redirecting to the same final one.  Because URLs are only processed once per crawl session, only the first redirect encountered would be stored in the final document metadata field as the original URL.  And that is only true if a redirect is encountered before the final URL is.  Because if the final URL is linked directly from a page (without a redirect), then no redirect info would be stored with that final URL (even if many redirects to that final URL exists elsewhere on that website). How reliable would that be?  

If you still think there is enough value, we can make this github issue a feature request.

**Comment by csauvanet** [comment]
Hi Pascal,

Yes I understand, it really depends on what link will be visited first.
In my case, the URL after redirection is having an extra GET parameter to show it was redirected, then both URL are processed as Add document. It seems my customization did the trick:

```Java
public class CustomMetadataFetcher extends GenericMetadataFetcher {

    @Override
    public Properties fetchHTTPHeaders(HttpClient httpClient, String url) {
        Properties prop = super.fetchHTTPHeaders(httpClient, url);
        prop.addString(CUSTOM_CONSTANT, url);
        return prop;
    }
}
```
I just need to read this field in the properties.
For me no need to have a feature implementation, hope this ticket as documentation can help someone else if need be !

**Comment by essiembre** [comment]
Great, I'll close then.  Thank you for sharing your solution!

**Comment by csauvanet** [comment]
Just for information, since it seems https://github.com/Norconex/collector-http/issues/135 I do not need this workaround (just upgraded to collector 2.3.0).
In fact this was mainly to make the differentiation at commit step if I was dealing with original document or the one after redirection.
