### ISSUE TITLE
SiteMap crawling: 0 start urls identified

### ISSUE THREAD

**Issue by searchquest** [Norconex/collector-http#187]
Hi,

I am using norconex-collector-http-2.3.0-20151029.020806-31 SNAPSHOT to crawl a some of normal urls and sitemaps as well. I have been successfully crawling normal URLs as well as sitemaps until I faced this issue for one of the sitemaps with similar configuration. The configuration section where I mentioned the sitemap is like below,

&lt;startURLs&gt;
	&lt;sitemap ignore="false" lenient="true" class="com.norconex.collector.http.sitemap.impl.StandardSitemapResolverFactory">
http://www1.ericsson.com/sitemap.xml
	&lt;/sitemap&gt;
&lt;/startURLs&gt;

it says - '0 start URLs identified' in log. Here is the log snippet below,

WWW: 2015-11-30 13:16:25 INFO - Running WWW: BEGIN (Mon Nov 30 13:16:25 CET 2015)
WWW: 2015-11-30 13:16:25 INFO - Initializing reference store .\internal-output\www/crawlstore/mapdb/WWW/
WWW: 2015-11-30 13:16:25 INFO - .\internal-output\www/crawlstore/mapdb/WWW/: Done initializing databases.
WWW: 2015-11-30 13:16:25 INFO - WWW: RobotsTxt support: false
WWW: 2015-11-30 13:16:25 INFO - WWW: RobotsMeta support: true
WWW: 2015-11-30 13:16:25 INFO - WWW: Sitemap support: true
WWW: 2015-11-30 13:16:25 INFO - WWW: Canonical links support: true
WWW: 2015-11-30 13:16:25 INFO - WWW: User-Agent: <None specified>
WWW: 2015-11-30 13:16:26 INFO - WWW: Initializing sitemap store...
WWW: 2015-11-30 13:16:26 INFO - WWW: Done initializing sitemap store.
WWW: 2015-11-30 13:16:28 INFO - Resolving sitemap: http://www1.ericsson.com/sitemap.xml
WWW: 2015-11-30 13:16:29 INFO -          Resolved: http://www1.ericsson.com/sitemap.xml
WWW: 2015-11-30 13:16:29 INFO - 0 start URLs identified.
WWW: 2015-11-30 13:16:29 INFO -           CRAWLER_STARTED
WWW: 2015-11-30 13:16:29 INFO - WWW: Crawling references...
WWW: 2015-11-30 13:16:29 INFO - WWW: Re-processing orphan references (if any)...
WWW: 2015-11-30 13:16:29 INFO - WWW: Reprocessed 0 orphan references...
WWW: 2015-11-30 13:16:29 INFO - WWW: Crawler finishing: committing documents.
WWW: 2015-11-30 13:16:29 INFO - WWW: 0 reference(s) processed.
WWW: 2015-11-30 13:16:29 INFO -          CRAWLER_FINISHED
WWW: 2015-11-30 13:16:29 INFO - WWW: Crawler completed.
WWW: 2015-11-30 13:16:29 INFO - WWW: Crawler executed in 3 seconds.
WWW: 2015-11-30 13:16:29 INFO - Closing reference store: .\internal-output\www/crawlstore/mapdb/WWW/
WWW: 2015-11-30 13:16:29 INFO - Running WWW: END (Mon Nov 30 13:16:25 CET 2015)

The earlier sitemap url that I successfully crawled were intranet ones whereas this one is a internet sitemap. This is one difference that might be affecting, perhaps.
Could there be some firewall related issue or any specific configuration that I need to take care of. Please suggest.

**Comment by essiembre** [comment]
I am not sure what this specific snapshot version provides, but note that version 2.3.0 is officially out now.  Please try with the official release.

You have attributes that do not apply to the sitemap tag found under start URLs: `` ignore="false" lenient="true" class="com.norconex.collector.http.sitemap.impl.StandardSitemapResolverFactory"``.  Those are reserved for the former sitemap tag found elsewhere in the config that has since been renamed ``sitemapResolverFactory`` to avoid confusion (the [documentation page](https://www.norconex.com/collectors/collector-http/configuration) has been updated since).

When used as a start URL, you simply need to do it this way::

```
<startURLs>
    <sitemap>http://www1.ericsson.com/sitemap.xml</sitemap>
</startURLs>
```
Now to your problem.  It occurs because the host name used to access the sitemap is different than the host name in the URLs it contains, so they are rejected.  There are a few ways to fix. 

First, you can simply use ``http://www.ericsson.com/sitemap.xml`` instead (drop the "1" character).

Second, you can tell the sitemap resolver to be "lenient" when it comes to URLs not being on the same host name.  Like this:
```
<sitemapResolverFactory lenient="true" 
     class="com.norconex.collector.http.sitemap.impl.StandardSitemapResolverFactory"/>
```

Keep in mind that it will try to resolve the sitemap again for URLs on the different host, so I would pick the first approach (else, maybe setting the sitemap resolver to ``ignore=true`` would prevent processing the same sitemap twice -- once for each different host).

Let me know if that works for you.

**Comment by searchquest** [comment]
Hi Pascal,

Thanks a lot. I have downloaded the latest stable 2.3.0 version and tried crawling with the first approach which seems to have worked.

I am having one more question related to excluding a certain url pattern. Not sure if I could create a separate issue, but including here itself. There are some urls like http://x.y.com/abc/AllArticle.aspx?PageNo=1 and I am trying to exclude them as below,

&lt;filter 
            class="com.norconex.collector.core.filter.impl.RegexReferenceFilter"
            onMatch="exclude"&gt;http:\/\/x\.y\.com\/abc\/AllArticle\.aspx.*&lt;/filter&gt;

But it does not. If you please help on this plz.

**Comment by essiembre** [comment]
Yes, I prefer a separate ticket since it is unrelated to this one. I created one for you (#191) and I will reply there shortly.
