### ISSUE TITLE
How can I fetch specific links only in a site ?

### ISSUE THREAD

**Issue by bruce-genhot** [Norconex/collector-http#189]
For a given site, I am interested in some of links only, How can I specify interesting links ? maybe in a filter ?

**Comment by essiembre** [comment]
When you say "some of links", do you have more details?  If the links you want to exclude all have clear patterns, I suggest you use one or more filters like you suggest.  If you add a reference filter to your config, it will be enforced before documents are downloaded, so that's a good choice.  For example, look at the [RegexReferenceFilter](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/filter/impl/RegexReferenceFilter.html) class.

If what you want is to stay on the current host only, you can add the following attributes to your start URL tag:
```xml
<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
...
</startURLs>
```
