### ISSUE TITLE
Can I run multiple collectors in parallel ?

### ISSUE THREAD

**Issue by bruce-genhot** [Norconex/collector-http#207]
I tried to run multiple collectors (about 20 collectors, and each collector has about 10 crawlers),  but collectors can not be fully completed. the running progress was blocked by something like below
```
MapDBCrawlDataStore [INFO] Closing reference store:
JobSuite [INFO] Running 26: END
````

**Comment by essiembre** [comment]
These are the usual two last lines of a log for a crawler that stopped normally.  What makes you think it was not fully completed?    The 10 crawlers you have per collector will not all complete at the same time.  They each have their own "reference store" so when a crawler is done, it closes it.  That's why you see that in the log.  It does not mean the other crawlers are done also.

**Comment by bruce-genhot** [comment]
No more logs were printed, seems that other crawlers were blocked. I checked the directory of ```work```, no folders found for remaining collectors

**Comment by essiembre** [comment]
Humm... In your configs, can you verify you do not have overlapping paths defined?

Also, since that's 200 crawlers at once, each with possibly using different threads, can you monitor the resources on your hardware to find out if any are maxed out when this happens?

**Comment by bruce-genhot** [comment]
OK, thanks, maybe because of the disconnection with elasticsearch.

**Comment by essiembre** [comment]
Do you still have an issue with this one or can we close?

**Comment by bruce-genhot** [comment]
Do not have issue at this time moment, please close it.

**Comment by essiembre** [comment]
Thanks for confirming!
