### ISSUE TITLE
another charset encoding issue

### ISSUE THREAD

**Issue by jetnet** [Norconex/collector-http#209]
I just take the same [test page](https://herimedia.com/norconex-test.html) from the issue #202 
config:
```xml
    <importer>
        <preParseHandlers>
          <tagger class="${DeleteTagger}">
              <fields>Date,Content-Type</fields>
          </tagger>
          <transformer class="${CharsetTransformer}" targetCharset="UTF-8">
            <restrictTo caseSensitive="false" field="document.contentType">text/.*</restrictTo>
          </transformer>
        </preParseHandlers>

        <postParseHandlers>
          #parse("${shared_configs}/global-postParseHandlers.xml")
        </postParseHandlers>
    </importer>
```
log:
```log
test: 2016-01-06 18:57:29 DEBUG - All fields to remove: {Date,Content-Type}
test: 2016-01-06 18:57:29 DEBUG - Removed field: Date
test: 2016-01-06 18:57:29 DEBUG - Removed field: Content-Type
test: 2016-01-06 18:57:29 DEBUG - Creating new input stream from memory cache.
test: 2016-01-06 18:57:29 DEBUG - Detected encoding: ISO-8859-1
test: 2016-01-06 18:57:29 DEBUG - Creating new input stream from memory cache.
test: 2016-01-06 18:57:29 DEBUG - Creating new input stream from memory cache.
test: 2016-01-06 18:57:29 DEBUG - Creating new input stream from memory cache.
test: 2016-01-06 18:57:30 DEBUG - OCR parsing is disabled.
test: 2016-01-06 18:57:30 DEBUG - Parser "com.norconex.importer.parser.impl.FallbackParser" about to parse "https://herimedia.com/norconex-test.html".
```
result (in solr):
```xml
    <arr name="title">
      <str>NÃ¶rcÃ¶Ã±Ã©x Test Site</str>
    </arr>
    <arr name="text">
      <str>
    NÃ¶rcÃ¶Ã±Ã©x Test Site
    Larger File
  </str>
    <arr name="Content-Encoding">
      <str>ISO-8859-1</str>
    </arr>
    <arr name="Content-Type">
      <str>text/html; charset=ISO-8859-1</str>
    </arr>
    <arr name="collector.content-encoding">
      <str>iso-8859-1</str>
    </arr>
    <arr name="document.contentEncoding">
      <str>iso-8859-1</str>
    </arr>
```
collector version: `norconex-collector-http-2.4.0-20160106.045515-15.zip`
Thanks!

**Comment by jetnet** [comment]
Update: the encoding is broken even when the `FileSystemCommitter` is used:

`1452517967563000000-add.cntnt`
```
    NÃ¶rcÃ¶Ã±Ã©x Test Site
    Larger File
    Extension Test
    Extension Test
    No extension test
```
`1452517967563000000-add.meta`
```
Content-Encoding=ISO-8859-1
Content-Type=text/html; charset\=ISO-8859-1
collector.content-encoding=iso-8859-1
document.contentEncoding=iso-8859-1
dc\:title=NÃ¶rcÃ¶Ã±Ã©x Test Site
title=NÃ¶rcÃ¶Ã±Ã©x Test Site
```

**Comment by essiembre** [comment]
The CharsetTransformer works fine with your test file.  This issue is with your instructions to the crawler.

See, your config here is different than the one in #202.  In the ``importer`` section in the ticket 202, you were ignoring the parsing for all content types.  Then your CharsetTransformer is what was taking care of the conversion from the original one to UTF-8.

With your above config sample, you are no longer skipping parsing.  So what you are asking is to convert from ``ISO-8859-1`` to ``UTF-8`` before parsing.  That part works, so you end up with an HTML document with a declaration of ``ISO-8859-1`` but is in reality UTF-8.  

Then the parsing will parse the HTML, use the declared encoding and convert it again as UTF-8 since that's what it always does (every parsed documents are UTF-8 in the end).  Since the declared encoding is ``ISO-8859-1``, it tries to convert that charset to UTF-8... but since it is already UTF-8, the declaration is invalid and causing the conversion error.  

So the fix is very simple: If you do not want to skip the parsing stage anymore (like you did in #202), then there is no need to have a CharsetTransformer at all!  The resulting doc will be UTF-8 by default and will be good in Solr.  In other words, do not apply conversion yourself and let the parser do it.  

Give it a try and let me know.

**Comment by jetnet** [comment]
I apologize, I should have uploaded the full config at the beginning... I have one more pre-parsing step:

```xml
  <!-- remove stopindex-startindex content    -->
  <transformer class="$StripBetweenTransformer"
          inclusive="true" 
          caseSensitive="false"
          maxReadSize="1000000" >
      <stripBetween>
          <start><![CDATA[\<\!\-\-stopindex\-\-\>]]></start>
          <end><![CDATA[\<\!\-\-startindex\-\-\>]]></end>
      </stripBetween>
      <restrictTo caseSensitive="false" field="document.contentType">text/html</restrictTo>                  
  </transformer>
  <!-- remove the possible last stoptindex content  -->
  <transformer class="$StripBetweenTransformer"
          inclusive="false" 
          caseSensitive="false"
          maxReadSize="1000000" >
      <stripBetween>
          <start><![CDATA[\<\!\-\-stopindex\-\-\>]]></start>
          <end><![CDATA[\<\/body\>]]></end>
      </stripBetween>
      <restrictTo caseSensitive="false" field="document.contentType">text/html</restrictTo>
  </transformer>
  ```

So, the `StripBetweenTransformer` seems not to respect the encoding of the input document. If the above pre-parsing steps are commented out, than the document gets parsed without problems (no `CharsetTransformer` needed).

**Comment by essiembre** [comment]
The issue is that transformers assumes UTF-8.  I am marking this as a feature request to be able to detect (or specify) the encoding of the source and keep the same one when saving it back.  

In the meantime, the solution is to use ``CharsetTransformer`` to convert to UTF-8 before all your transformations and once again after (before parsing), to convert back to ``ISO-8859-1``.   Not super pretty, but it will work fine until the more elegant solution is implemented.

**Comment by jetnet** [comment]
The suggested pre-parsing conversion forth and back did the trick :)
Unfortunately, during the pre-parsing stage, there is not yet information regarding the charset available, and since the "restrictedTo" fields are "OR" linked, so it is not possible to configure a "generic" converter.
The workaround I'm using now: to configure different collector instances for UTF-8 and for not UTF-8 sites...

**Comment by jetnet** [comment]
BTW, it could be tricky to implement the "feature-request", one more thing to keep in mind, some meta-fields should be converted too:

```xml
    <str name="url">http://db-artmag.com/archiv/06/d/ausstellungen-sugimoto02.html</str>
    <arr name="collector.referrer-reference">
      <str>http://db-artmag.com/archiv/2008/d/5/archiv.html</str>
    </arr>
    <arr name="collector.referrer-link-text">
      <str>Sugimotos Portr�ts in Singapur</str>
    </arr>
```
ok, that parameter `referrer-link-text` is not that important in that case, but in some cases it could be.

**Comment by essiembre** [comment]
OK, the [latest snapshot](https://www.norconex.com/collectors/collector-http/download) release should fix a lot of character encoding issues.  When used as a pre-parse handlers, most handlers will now "detect" the character encoding instead of assuming UTF-8.  For transformers, this also means the document will be written back using the same encoding detected.   This should get rid of the vast majority of charset issues with handlers.  

In case the charset is not detected properly, one can specify it using the new ``sourceCharset`` attribute, like this (same name on all text-related handlers).

```xml
<transformer class="com.norconex.importer.handler.transformer.impl.StripBetweenTransformer"
          sourceCharset="ISO-8859-1" >
 ...
</transformer>
```

When used as post-handlers, UTF-8 is assumed (as before this fix).  The reason being every pieces of content is converted to UTF-8 after the Importer has parsed them.  

In the event that someone tells the Importer to skips parsing, then all transformations should be done as pre-parse handlers to benefit from the auto-detection.

Please give a try to this new release and confirm.

**Comment by jetnet** [comment]
I can confirm, that the pre-parse issue is gone! :)
Thank you very much for the great support again! I really appreciate that!

P.S. for the sake of completeness - the issue with the `collector.referrer-link-text` still persist, but it is not that important for now.
