### ISSUE TITLE
logfile naming

### ISSUE THREAD

**Issue by jetnet** [Norconex/collector-http#214]
Hi!
it's not really an issue, but I'd like to clarify the naming of the logfiles.
If I start a collector instance with a single crawler, then the logfile's name is:

`<crawlerid>.log`

If the instance have more than one crawler, then a single combined log file is used for all jobs:

`<httpcollectorid>.log`

Is it configurable? I'd prefer always to have separate logfiles for every job (crawler).
Thank you!

**Comment by essiembre** [comment]
This is not a configuration options via XML.  It would have to be done programmatically.

The collector uses a library called [JEF API](https://www.norconex.com/jef/api/) which among other things handles the log storage.  There is an interface that defines how logs are handled by that library called  [ILogManager](https://www.norconex.com/jef/api/latest/apidocs/com/norconex/jef4/log/ILogManager.html).  The default implementation is [FileLogManager](https://www.norconex.com/jef/api/latest/apidocs/com/norconex/jef4/log/FileLogManager.html) and only minimum tuning is offered by way of the collector config.  It does not provide ways to have different log files per crawlers (which are "jobs" to the JEF API). You would have to provide your own implementation that does it, but it may get tricky since I think the JEF API draws certain benefits from having only one log per program execution.

We can turn this into a feature request if you like.

**Comment by jetnet** [comment]
I think, it would be very helpful to have a logfile per job, when you have hundreds of crawlers.
Especially on an environment where you can only login using the command line :)
Thank you!

**Comment by essiembre** [comment]
Version 3 no longer explicitly deals with log files.  In fact, logging has been abstracted out using SLF4J. The default logging implementation is Log4J2 and it logs to STDOUT. You can replace it with your own.   

In version 3, Each crawler has their name set to their thread and that name is being logged by default.  So you have each entry "tagged" with your crawler name already, making it easy to read/parse.  Relying on thread names in your logs to split would be a good approach.  Using `grep` with your crawler name would do it.

If you still need to log to different files, you can have a look at the options offered by Log4J2 or another implementation.  Another option is to use your OS shell commands to split the content into multiple files.

As this won't be implemented in version 2.x and is no longer applicable in version 3.x, I'll close this ticket.
