### ISSUE TITLE
Can I specify content encoding for DOMTagger ?

### ISSUE THREAD

**Issue by bruce-genhot** [Norconex/collector-http#220]
Now, DOMTagger handles all document in UTF-8, it's better if user can specify content encoding. by the way, a flag controlling the removal of HTML is also necessary

**Comment by essiembre** [comment]
Charset handling has been greatly improved in the [latest snapshot](https://www.norconex.com/collectors/collector-http/download).  See this comment for more details: https://github.com/Norconex/collector-http/issues/209#issuecomment-172744356

As for controlling the removal of HTML, that snapshot now supports a new attribute called ``extract`` which takes one of the following values: ``text``, ``html``, or ``outerHtml``.  

**Important:** The default behavior has been modified to return text instead of HTML.  To get HTML back, use ``html`` as the extract value.  Like this:

```xml
<tagger class="com.norconex.importer.handler.tagger.impl.DOMTagger">
      <dom selector="div.whatever" toField="myField" extract="html" />
  </tagger>
```

Please test and confirm.

**Comment by bruce-genhot** [comment]
Confirmed, thanks.
