### ISSUE TITLE
ExtensionReferenceFilter: many periods in the name of a file

### ISSUE THREAD

**Issue by jetnet** [Norconex/collector-http#222]
hi!
it seems, that the ExtensionReferenceFilter is not able to recognize the extension correctly, when the name of a file contains multiple periods, e.g.:

```
www.db.com: 2016-01-18 11:47:09 DEBUG - ACCEPTED document reference. Reference=https://www.db.com/cr/img/_DSC0158.NEF.p.jpg Filter=ExtensionReferenceFilter[onMatch=EXCLUDE,extensions=swf,jpg,png,gif,css,js,ico,css,json,mov,avi,mp3,mp4,mpg,mpeg,bmp,jpeg,zip,jar,rar,gz,caseSensitive=false]
```

**Comment by niels** [comment]
I think this is my fault..

Since https://github.com/Norconex/collector-core/commit/4d853b3b0113468f29c2cfd17f93af2ba7afcee8, the extension filter will consider *everything following the first dot* in the last path segment to be the file extension.

In your example, the file extension would be `NEF.p.jpg`. See [this test](https://github.com/Norconex/collector-core/blob/4d853b3b0113468f29c2cfd17f93af2ba7afcee8/norconex-collector-core/src/test/java/com/norconex/collector/core/filter/impl/ExtensionReferenceFilterTest.java#L31). This struck me as sensible at the time but upon further thought, your use case is probably much more common than people wanting to filter on several "levels" of extensions.

If @essiembre has no objections, I will modify the extension filter once more to bring it into line with @jetnet's expectations.

Those who actually do want to filter on something like `NEF.p.jpg` could always do so with a separate regex filter on the entire reference.

**Comment by essiembre** [comment]
@niels, I do agree with the proposed change.

**Comment by essiembre** [comment]
The [latest snapshot](https://www.norconex.com/collectors/collector-http/download) release now has this fix. Please try.

**Comment by jetnet** [comment]
Seems to be working with `norconex-collector-http-2.4.0-20160223.174916-28.zip`
Thanks! The issue can be closed.
