### ISSUE TITLE
collect only html files

### ISSUE THREAD

**Issue by nuliknol** [Norconex/collector-http#228]
How do I collect only .html files and skip any other ?
It should be done with extensionreferencefilter but there is no documentation about it.
TIA

**Comment by essiembre** [comment]
Hello @nuliknol, All configuration options are documented and found on that page: https://www.norconex.com/collectors/collector-http/configuration. From that page, you will also find a link to the Importer module configuration option here: https://www.norconex.com/collectors/importer/configuration

In these pages each option has a clickable link that leads you to the Javadoc, which contains an example how to use it.  For instance, you can find how to use the ExtensionReferenceFilter [here](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/filter/impl/ExtensionReferenceFilter.html).

More precisely, you can do what you want this way:

```xml
<filter class="com.norconex.collector.core.filter.impl.ExtensionReferenceFilter">
      html
</filter>
```

Alternatively, you can do it on content type if you feel it is safer than relying on file extension by using the [RegexMetadataFilter](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/filter/impl/RegexMetadataFilter.html) from the Importer module.  Like this:
```xml
<importer>
  <postParseHandlers>
    <filter class="com.norconex.importer.handler.filter.impl.RegexMetadataFilter" field="document.contentType">
      text/html
    </filter>
  </postParseHandlers>
</importer>
```

If there is anything else you wonder, do not hesitate to ask.

**Comment by nuliknol** [comment]
thank you for the support. But this has to be done before the file is downloaded, otherwise, I am downloading megabyte size files and this is not good. I tried to filter at the HTTP headers level, but the config file is not parsed successfuly after adding these lines to "crawler" block:

```
   <metadataFilters>
    <filter class="com.norconex.importer.handler.filter.impl.RegexMetadataFilter" field="document.contentType">
      text/html
    </filter>
   </metadataFilters>
```

the error is:
```
com.norconex.collector.core.CollectorException: Cannot load crawler configurations.
	at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfigs(CrawlerConfigLoader.java:93)
	at com.norconex.collector.core.AbstractCollectorConfig.loadFromXML(AbstractCollectorConfig.java:183)
	at com.norconex.collector.core.CollectorConfigLoader.loadCollectorConfig(CollectorConfigLoader.java:78)
	at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:76)
	at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:75)
Caused by: java.lang.ClassCastException: com.norconex.importer.handler.filter.impl.RegexMetadataFilter cannot be cast to com.norconex.collector.core.filter.IMetadataFilter
	at com.norconex.collector.core.crawler.AbstractCrawlerConfig.loadMetadataFilters(AbstractCrawlerConfig.java:405)
	at com.norconex.collector.core.crawler.AbstractCrawlerConfig.loadFromXML(AbstractCrawlerConfig.java:320)
	at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfig(CrawlerConfigLoader.java:123)
	at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfigs(CrawlerConfigLoader.java:83)
	... 4 more

```

**Comment by essiembre** [comment]
This class belongs to the importer module: `` com.norconex.importer.handler.filter.impl.RegexMetadataFilter``.

For the ``<metadataFilters>`` tag, the equivalent class is this one ``com.norconex.collector.core.filter.impl.RegexMetadataFilter``.  But at that point ``document.contentType`` may not be set by the importer by analyzing the content so your best bet is probably to rely on the HTTP Header field ``Content-Type``.  That one sometime comes with a charset value attached, so to be safe, you probably want to use it in a pattern, like this:
```xml
<metadataFilters>
  <filter class="com.norconex.collector.core.filter.impl.RegexMetadataFilter" field="Content-Type">
    .*\btext/html\b.*
  </filter>
</metadataFilters>
```
If you still have issue making it work with the above snippet, please attach your config so we can reproduce and further help you.

**Comment by nuliknol** [comment]
thanks, it works now! I wonder, the metadata filter on HTTP header is applied after the full file was downloaded, or it downloads only some fixed amount of bytes, checks the content type, and then takes action ?

**Comment by essiembre** [comment]
HTTP requests are always fully read to avoid stalled connections so by default it will need to download the document to obtain the HTTP header information.  If you are worried this may add too much bandwidth consumption, you can first tell the crawler to perform an HTTTP HEAD request to obtain the HTTP medadata.  Your metadata filters will then be applied BEFORE the document is downloaded.  You can do this by adding the [GenericMetadataFetcher](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/GenericMetadataFetcher.html) to your crawler configuration, like this.

```xml
  <metadataFetcher class="com.norconex.collector.http.fetch.impl.GenericMetadataFetcher" />
```
Look at its javadoc (above link) for more configuration options.

If you suspect lots of documents will be filtered based on their HTTP header fields, that is definitely worth it.  Otherwise, the extra HTTP call to always get the HTTP headers first, then the document may not be worth it.  That's for you to test/evaluate.

In your case, if you know all your HTML pages will have the .html extension, it is probably best to use a simple reference filter, which takes place before any HTTP call gets made (even better).  You'll find an example of that one in a previous answer of mine.  

In the end, nothing prevents you to use a mix.  A reference filter to eliminate the vast majority of your non-HTML URLs super fast, and a metadata filter for the odd ones slipping through the cracks (not having .html as an extension in their URLs).

Make sense?

**Comment by nuliknol** [comment]
yes, how could I forget the HEAD method. Definitely will be the best solution in my case. Thank you for this wonderful software!

**Comment by essiembre** [comment]
You are welcome!
