### ISSUE TITLE
Wrong classpaths in collector-http-config-reference.xml

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#240]
Should be` <committer class="${committer}.core.impl.FileSystemCommitter">`
instead of
`<committer class="$committer.impl.FileSystemCommitter">`

and change delay to  

```
    <delay default="1000" ignoreRobotsCrawlDelay="true"
           class="${http}.delay.impl.GenericDelayResolver">
          <schedule dayOfWeek="from Monday to Friday" 
                    time="from 8:00 to 16:30">10000</schedule>
    </delay>
```

**Comment by essiembre** [comment]
Your fix did not work probably because the variable needed to be surrounded by braces in this case (it probably did not like being close to a dot).  In any case, I changed it to use a new variable called ``$fsCommitter`` instead since variables are fully used for every other config portions in that file. Thanks for reporting documentation errors!

**Comment by OkkeKlein** [comment]
I edited the post with correct code that works. Also notice the endtime of schedule. It also throws exception as it's before starttime.

**Comment by essiembre** [comment]
Thanks, I also fixed this.
