### ISSUE TITLE
Crawl behavior

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#274]
Trying to do a normal website recrawl. 

It states that starting URL is unmodified. Then ends crawl. All references go to cached table with crawl state NEW and only starting URL remains in table reference with crawl state UNMODIFIED.

Start recrawl for second time  and again it stops after starting URL and cached table is cleared from all references.

**Comment by essiembre** [comment]
You say if the start URL is unmodified it "stops" there?  It should not, unless maybe you changed the default behavior how "orphans" are handled (to be vefiried).  

After a first crawl, all URLs will be cached.  On a second crawl, if a page if found not to be modified before its URL were extracted (like by relying on HTTP last-modified header), it will not go further with that page.  Since it needs to know if other pages on the site were modified, this is where the crawler will grab all URLs in the cache from the previous run and try them all again.  Once re-processed, they should find their way back in the cache for future runs.  Are you witnessing anything different and missing documents as a consequence?  If so please attach your config with steps to reproduce (e.g. which documents are affected).

**Comment by OkkeKlein** [comment]
Orphan strategy is IGNORE.

In first crawl it cached all references. Then finds starting URL to be unmodified and then stops recrawl and deletes all the other references.

**Comment by essiembre** [comment]
What is the resulting effect of what you are describing?  In trying to reproduce, I would need the evidence you have that something is not working.  Is the crawler skipping recrawling some documents that were modified?   Having a copy of your config with how to reproduce and what to look for would help.

Not sure if it make a difference, but if you are honoring sitemaps (the default), the recrawlable resolver will honor the crawl delay specified in them.  It may be why you are not seeing documents being recrawled (if not enough time has gone by).  Assuming this is the problem you are having.

**Comment by essiembre** [comment]
With the config you sent me via email I was able to reproduce.  It is a combination of configuration settings you have that causes this.

To find if there was a change, you are using the default ``<metadataChecksummer>`` implementation which relies on the Last-Modified date field found form the HTTP headers when making the HTTP call to get a document. By default, that date field is obtained with HTTP headers obtained when the actual document is being downloaded (by the ``<documentFetcher>``).  Normally, URLs to be "followed" are extracted before the metadata checksummer is invoked to find out it was unmodified and then rejected (but the extracted URLs will be crawled).

In your case, you have configured the use of a ``<metadataFetcher>`` which will make an extra HTTP "HEAD" call to get the HTTP headers only and not the actual document.   This feature is not enabled by default and exists mostly to avoid downloading potentially large documents for no reason if we can find out using HTTP headers they were not modified.  So it costs an extra HTTP call to potentially save a few big downloads.   The net effect of this is, since the document was not downloaded, its URLs were not extracted and there is nothing to "follow" and it stops there.   

Here are your easy options to fix:

* If you want to keep using the last modified date in the HTTP header obtained from a ``<metadataFetcher>`` HEAD request to prevent some file downloads, keep things as is, and simply change the ``<orphansStrategy>`` to ``PROCESS``.  This will ensure the crawler attempts to re-crawl all the "leftovers" from the cache.

* If you are dealing mostly with small files and/or you would rather save the extra HTTP call for each document, you can comment/delete the ``<metadataFetcher>`` tag.  That way, the last modified date will still be used to find if a document has changed, but it will be obtained from HTTP headers obtained by downloading the file with a ``<documentFetcher>`` GET request.  URLs will be extracted and followed just fine, so you can keep the ``<orphansStrategy>`` to ``IGNORE``.

* If you go with the second option above, since you will have downloaded the file, feel free to disable the ``<metadataChecksummer>`` altogether if you would rather have the content compared instead, in case you find that approach more reliable to assess a change than relying on the HTTP header last modified date (not all sites are good with it).

**Comment by essiembre** [comment]
I have to add... you may have to start with a fresh crawl to have some of these changes take effect.

**Comment by OkkeKlein** [comment]
Thank you for the explanation. The metadatafetcher made sense in another config, but can be removed from this one.
