### ISSUE TITLE
check if can check the crawled website finished or not 

### ISSUE THREAD

**Issue by doaa-khaled** [Norconex/collector-http#276]
I put every crawled website as a crawler instance inside the config file, and now I want to check if there is a website finish crawling or not, I used that code 
`
JobSuiteStatusSnapshot jobSnapshot = JobSuiteStatusSnapshot.newSnapshot(new File(indexFilePath));
List<IJobStatus> jobsStatusList = jobSnapshot.getJobStatusList();
`
but it treats every config file as a job.. is there a way to check crawlers for each url ?

**Comment by essiembre** [comment]
You mean for each site?  You can do this by having one site URL per crawler defined in your config (not sure how practical it can be for you if you have tons of sites). 
A crawler is done when it has no more links to crawl, but as long as it is going, there is no way to garantee beforehand that no more pages will contain more links pointing to pages on a given site not already crawled.  The only way to tell for sure it is done with a site is when crawling is over.

**Comment by doaa-khaled** [comment]
that will not be a reasonable solution to separate every link to a config file.

**Comment by essiembre** [comment]
You do not have to create multiple files.  You can use only a single config for this or no config at all, based on your comfort level.  Here are a few options (some can be mixed):

* You can have multiple crawlers defined in a single config file.  You can have shared crawler settings in the ``<crawlerDefaults>`` section or use include files to load shared settings.  
* You can use Apache Velocity syntax dynamically create the multiple crawler configs in the same config.
* You can use Java programming to configure your crawler programatically instead of using config files.
* You can generate config files dynamically with the programming language of your choice.

You can also batch your list in manageable chunks.  Also check the FAQ titled "[One collector with several crawlers or a crawler with several starting sources?](https://www.norconex.com/collectors/collector-http/faq)" for more insight.

**Comment by doaa-khaled** [comment]
Hi Essiembre, I tried that code to get the status of every job 
`
JobSuiteStatusSnapshot jobSnapshot = JobSuiteStatusSnapshot.newSnapshot(indexFile);
List<IJobStatus> jobsStatusList = jobSnapshot.getJobStatusList();
for (IJobStatus jobStatus : jobsStatusList) {
	if (jobStatus.isCompleted()) {
		finishedJobsIDs.add(jobStatus.getJobId());
	}
}
`
do u know the reason?

**Comment by essiembre** [comment]
Is your ``jobsStatusList`` empty?  Else, try to print the actual status of every job instead of checking ``isCompleted()`` as a test (``jobStatus.getState()``).

**Comment by doaa-khaled** [comment]
it didn't work due to conflict in 2 jars with same job and different versions was included in my lib folder, now it works fine.. thank a lot

**Comment by essiembre** [comment]
You are welcome!
