### ISSUE TITLE
Refferer missing in URLStatusCrawlerEventListener

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#277]
keepReferrerData in GenericLinkExtractor needs to be set to true to discover pages with broken links.

**Comment by essiembre** [comment]
That is correct. I updated the documentation in [URLStatusCrawlerEventListener](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/crawler/event/impl/URLStatusCrawlerEventListener.htm) to reflect that.  Thanks for pointing that out.

Referrer data is not kept by default because it grows the crawl store and is often not required.  It is believed to improve performance to have it off by default but if people start reporting otherwise, or if we get that people use it in most cases, we may decide to always store the referrer data in a future release.
