### ISSUE TITLE
duplication in graped files

### ISSUE THREAD

**Issue by doaa-khaled** [Norconex/collector-http#285]
I try to crawl on websites and may same file which grapes from one parent url be grapes from another parent url.. is there a way to prevent that duplication?

**Comment by essiembre** [comment]
Within the same crawler instance, this naturally happens: the same URL will not be crawled twice.  

If you are talking about having configured **different** crawlers and they each point to the same documents, then no, nothing prevents them from getting those documents unless you told them so (crawlers run in isolation from each other).  This means, you have to make sure you define adequate filter rules so one crawler does not overlap the other and crawl the same content twice if you wan to avoid it.

**Comment by doaa-khaled** [comment]
No, I was in same crawler and there is an URL exist in 2 pages so I get its content twice.. let me give you an example,
this page conatain this pdf
http://www.polyavx.com/AGM_Form.aspx	
http://www.polyavx.com/Download/AGM/MGT%2013%20-%20AGM_2014.pdf

and also this page
http://www.polyavx.com/polyavx/AGM_Form.aspx	http://www.polyavx.com/polyavx/Download/AGM/MGT%2013%20-%20AGM_2014.pdf
I ask If there is a way to avoid getting this fetched URL twice.

**Comment by essiembre** [comment]
I see! In this case, the crawler considers them different because they have different URLs.  There is currently no support for having the crawler compare content of different downloaded documents to make sure they are not the same. This could be made a feature request, but hopefully for your site, you can filter out URL variations that lead to duplicates.  This is a more efficient approach when you can do it, since it prevents downloading the duplicates in the first place.

If you know pages are always the same under /ployavx/, you can filter out that URL pattern to solve this issue.

If you do not know upfront whether a document will be always be link linked from one or the other location, you can also try forcing which URL gets used by using a URL normalizer.  For instance, if you know /polyavx/ is equivalent to / in your site, you can try the following (which also keeps the default normalization rules):
```xml
  <urlNormalizer class="com.norconex.collector.http.url.impl.GenericURLNormalizer">
    <normalizations>
        removeFragment, lowerCaseSchemeHost, upperCaseEscapeSequence,
        decodeUnreservedCharacters, removeDefaultPort, encodeNonURICharacters
    </normalizations>
    <replacements>
      <replace>
         <match>/polyavx/</match>
         <replacement>/</replacement>
      </replace>
    </replacements>
  </urlNormalizer>
```
This will ensure every URLs pointing to /polyavx/ are always converted to / before being crawled (eliminating duplicates in your example).
