### ISSUE TITLE
[feature request] Count referrers for "relevance"

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#287]
With the referring links stored in DB, It should be possible to count them when importing and get a base 10 logarithm to get a very crude "revelance".

Just a thought, can close issue if you see no value in it.

**Comment by essiembre** [comment]
You are talking about the number of links that references a document? If I understand you right, this is currently not possible per design.  

The crawler is meant to send documents more or less as they as being crawled (up to batch size).  To do what you are asking it would mean to wait for entire crawling to be done, do a second pass on the crawl store to find all references, then commit all docs with that new relevance score.   It would mean caching all documents content until ready to be all analyzed and sent. The crawler does not perform second passes like that and does not perform massive caching of content.  It is not something we envision to have we aim to keep it lightweight.  

If you store those referring URLs in your target repository/search engine, you can periodically run a process that will do this for you and update a relevancy field for you.  It will likely be more appropriate to do it there in any case, since you will have ALL document references from all crawlers you may have created at that point.  Whereas a crawler-specific solution would only work for the links referenced within each crawler instances.

If you really want this part of the collector flow somehow, I encourage you to develop a special [ICommitter](https://www.norconex.com/collectors/committer-core/latest/apidocs/com/norconex/committer/core/ICommitter.html) implementation that will cache all documents in an intermediate repository and once the ``commit()`` method is called on it, apply all your mass-logic to it, before sending all docs to your final repository.  You will no longer get documents as they are being crawled though... so depending on your desired refresh cycle, it may be problematic or just less valuable (one more reason to do this directly on your target repo... to get faster crawl updates).

Maybe what could be a possible feature request is to have this as a separate process to run on the crawl store and produce some kind of flat file with URLs and "scores", letting people decide what to do with it.  Since that's not really a crawling activity at that point, that should maybe be a side project.

If you think I misunderstood that request of yours, feel free to re-open or ask a new question.   If you end up creating something to do so you feel is worth sharing, please let me know and I will create a link to it from the product website.
