### ISSUE TITLE
New URL normalization rule needed for links containing only hostname

### ISSUE THREAD

**Issue by xnerus** [Norconex/collector-http#290]
References containing only the hostname and references containing hostname and slash at the end perceived by the parser as different addresses. Then, the fetcher makes two requests instead of making just one. Here is an example to make it clearer:

```html
<a href="http://bot.nerus.com">Link for example 1</a><br>
<a href="http://bot.nerus.com/">Link for example 2</a><br>
```

In this case, both references will be treated as two different links. Also, I was very surprised that the rule `addTrailingSlash` did not help in this situation. But this rule should have no place in this matter.

In my opinion the new rule has the place to be (for example `addLeadingSlash`).

By the way, I bypassed the current situation with the help of a little trick. Next regular expression in `urlNormalizer` helps in this situation:

```xml
		<replacements>
			<replace>
				<match>^http[s]?:\/\/[a-zA-Z0-9\-\.]+$</match>
				<replacement>$1/</replacement>
			</replace>
		</replacements>
```

I hope my experience will be useful.

**Comment by essiembre** [comment]
Thanks for your feedback.  

Even if URLs with trailing slashes are more often than not equivalent to their version without a trailing slash, there is no guarantee of semantic equivalence according to URI standards and that's why removing/adding it id not part of the default normalization rules being applied.  

About the ``addTrailingSlash``, the documentation states it applies only to URL that ends with what appears to be "directories", so it would not apply here.  Still it is not the first time this rule name has mislead people so with the [latest snapshot](https://www.norconex.com/collectors/collector-http/download) release, it has been renamed to ``addDirectoryTrailingSlash``.

In addition, a new optional rule has been added that can help with this case if you know trailing slashes can safely be removed in your case: ``removeTrailingSlashes``.

I am glad you found a solution to your issue and I hope latest changes will make it clearer/simpler.

**Comment by xnerus** [comment]
Okay. But I still do not understand why the the two strings "http://example.com" and "http://example.com/" are perceived as two different addresses with all subsequent actions.

If my solution will be useful to someone, then since version 2.6.0 it should be valid as follows:

```xml
		<replacements>
			<replace>
				<match>^(http[s]?:\/\/[a-z0-9\-\.]+)$</match>
				<replacement>$1/</replacement>
			</replace>
		</replacements>
```

**Comment by essiembre** [comment]
FYI, the [latest snapshot](https://www.norconex.com/collectors/collector-http/download) introduces an optional "addDomainTrailingSlash" normalization rule which takes care of adding a forward slash to URLs ending with the domain name (or domain followed by ? or #).
