### ISSUE TITLE
How can I run a collector repeatedly in a correct way?

### ISSUE THREAD

**Issue by tungdx** [Norconex/collector-http#298]
Hi,
I would like to run my collector repeatedly, but unfortunately I got an exception com.norconex.collector.core.CollectorException: javax.management.InstanceAlreadyExistsException

Here is my code:

```java
while (true) {
	long start = System.currentTimeMillis();
	//... some codes to init a config for the collector

	HttpCollector collector = new HttpCollector(config);
	collector.start(true);	
	
	long end = System.currentTimeMillis();
	long threshold = end - start;
	if (threshold < MIN_INTERVAL_MILISECOND) {
		try {
			Thread.sleep(MIN_INTERVAL_MILISECOND - threshold);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}
}
```

Thanks in advance!

**Comment by essiembre** [comment]
It is best advised to run your collectors in separate JVMs for maximum isolation/stability.  Running multiple ones in the same JVM is not supported.  If you just want to automate launching many at once, I recommend one of these approaches instead:

* Have one collector with many crawlers instead (should achieve the same purpose).
* Use a shell/batch script that will launch collector instances separately (one JVM for each)
* In java, launch them as external processes.

Still, if you want to experiment and keep your approach, I can tell you each collector must have a unique working directory as they need to work in isolation from each other.  So make sure they each have different paths in your configs wherever you specified paths.  Sharing the same config will cause issues for sure because of that.

**Comment by tungdx** [comment]
Actually I am using one collector with many crawlers as your suggestion, but I can not use a shell/batch script because I must handle some logic before launching a collector. Therefore I must integrate this library in my project. I am going to choose the last your suggestion, will launch them as external processes, but before I run a collector again I must check the previous one had done or not (most likely check a process whether finished or not). I think it is a quite difficult trouble with me. I was wondering if you had any suggestion for me?

**Comment by essiembre** [comment]
Sure, to monitor external collector processes, you can use a class called [JobSuiteStatusSnapshot](https://www.norconex.com/jef/api/latest/apidocs/com/norconex/jef4/status/JobSuiteStatusSnapshot.html) like this:
```java
JobSuiteStatusSnapshot jobSnapshot = JobSuiteStatusSnapshot.newSnapshot(indexFile);
if (!jobSnapshot.getRoot().isRunning()) {
    /// do something
}
```
The ``indexFile`` you need to pass is the index file generated by each collector when they run. Typically found under ``[...]/progress/latest/*.index``.  That will give you an accurate picture of what is going on while keeping your app instance totally separate from the collector instances.

Check the following threads for more info around using it: https://github.com/Norconex/collector-http/issues/276, https://github.com/Norconex/collector-http/issues/249#issuecomment-215437279

Just as a FYI if you were not to run it as an external process, you can do ``[collectorInstance].getJobSuite().getStatus().isRunning()`` to achieve the same.

**Comment by tungdx** [comment]
I have just used JobSuiteStatusSnapshot class as your suggestion to check collector processes status and it worked well.

Thank you very much!
