### ISSUE TITLE
i can't run the main method in class HttpCollector

### ISSUE THREAD

**Issue by MohamedElsakka** [Norconex/collector-http#314]
i clone the project from github then convert the project as maven then i try to run it , but i can't .
i try to search how to start but there is no good tutorial for it please help me to start the project

**Comment by essiembre** [comment]
You can find usage documentation on the product site: https://www.norconex.com/collectors/collector-http/getting-started

You do not need to clone to use on the command line.  I am assuming if you cloned it since you want to code something.  In that case, if you just want to start it within your IDE, you have to replicate how the startup scripts do it (collector-http.[bat|sh]).

Basically, the main class is: ``com.norconex.collector.http.HttpCollector``.  You have to supply the same arguments you would on command line:
```
-a start -c /path/to/your/config.xml
```
Like the startup scripts, you can also set these JVM properties:
```
-Dfile.encoding=UTF8 -Dlog4j.configuration=file:/path/to/log4j.properties
```

Does that answer?

**Comment by MohamedElsakka** [comment]
yes , thank you .
