### ISSUE TITLE
The Handling Redirection is not working.(Maybe)

### ISSUE THREAD

**Issue by nemojjh** [Norconex/collector-http#315]
I tried to crawl some sites and found a case which is nor working.

URL is "http://ka-ps.jams.or.kr"

Log:
```
INFO  - CRAWLER_STARTED            -           CRAWLER_STARTED
INFO  - AbstractCrawler            - hello53134: Crawling references...
INFO  - DOCUMENT_FETCHED           -          DOCUMENT_FETCHED: http://ka-ps.jams.or.kr
INFO  - URLS_EXTRACTED             -            URLS_EXTRACTED: http://ka-ps.jams.or.kr
INFO  - DOCUMENT_IMPORTED          -         DOCUMENT_IMPORTED: http://ka-ps.jams.or.kr
-----START----
-----END----
INFO  - DOCUMENT_COMMITTED_ADD     -    DOCUMENT_COMMITTED_ADD: http://ka-ps.jams.or.kr
INFO  - AbstractCrawler            - hello53134: Deleting orphan references (if any)...
INFO  - AbstractCrawler            - hello53134: Deleted 0 orphan references...
INFO  - AbstractCrawler            - hello53134: Crawler finishing: committing documents.
INFO  - AbstractCrawler            - hello53134: 1 reference(s) processed.
INFO  - CRAWLER_FINISHED           -          CRAWLER_FINISHED
```

The Web Server makes clients to be redirected to "https://ka-ps.jams.or.kr"

But Crawler doesn't handle it.

How can I handle this case?

I really appreciate your kindness.

Thank you :)

Best Regards.

**Comment by essiembre** [comment]
http://ka-ps.jams.or.kr does not do a server side redirect.  Instead, it uses JavaScript to do a redirect:

```
location.assign("http://" + window.location.host + "/co/main/jmMain.kci");
```

Then, it is the page requested by JavaScript that does a server side redirect to:  http://ka-ps.jams.or.kr/co/main/jmMain.kci

The crawler does not follow the initial redirect because it does not interpret JavaScript.  To get around this problem, you will have to have in your start URLs  http://ka-ps.jams.or.kr/co/main/jmMain.kci or https://ka-ps.jams.or.kr/co/main/jmMain.kci (the first one will generate a redirect, but should be followed).  Alternatively you can write your own [ILinkExtractor](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/ILinkExtractor.html) but it is much simpler to simply change the start URL.

Does that answer?

**Comment by nemojjh** [comment]
Exactly... 

I think so. Thank you very much.

Sorry for poor question. Didn't check it.

It's my fault.

Happy New year!

**Comment by essiembre** [comment]
No worries.  Since the first page redirects quickly, it is not obvious to catch. :-)   Happy new year to you too!
