### ISSUE TITLE
New URLs to crawl

### ISSUE THREAD

**Issue by angelo337** [Norconex/collector-http#325]
hi there I am trying to crawl a group of urls, more that 100.000 and some are dynamically generated, is it possible to include a list of URL in norconex in a automatic fashion? I am trying to use "setStartURLs" however I don't see how does it works. could please provide us an example?
Best Regards
angelo

**Comment by essiembre** [comment]
Have you considered using a seed file?  That is, a file with one URLs per line?  You can then reference that file in your config using ``<urlsFile>...</urlsFile>`` instead of ``<url>...</url>``.   That URL file can be dynamically generated before each run the collector if you want.

A similar approach is to create a simple dynamic web page that generates the URLs you want to crawl on it, and use that URL as the start URL.

If you are doing it in Java, the ``setStartURLs`` should work, but they have to be set prior to starting the collector.

Does this answer?

**Comment by angelo337** [comment]
thanks a lot, 
I thing that one could be se seed file. I going to try it that route.
Regards
