### ISSUE TITLE
REJECTED_FILTER: {URL} (No additional information available.)

### ISSUE THREAD

**Issue by aleha84** [Norconex/collector-http#330]
When using referenceFilters like this: 
`<filter caseSensitive="false" class="$filterRegexRef" onMatch="include">http://.*mysite\.com/.*</filter>`
to reject everithing exept my domain (and it's subdomains) a lot of similar entries fall into the log.
```
REJECTED_FILTER: http://www.facebook.com/{someValue}?sk=wall (No additional information available.)
REJECTED_FILTER: http://mc.yandex.ru/watch/{someNum}(No additional information available.)
```

1. Reason of rejection isn't clear. - "No additional information available." Other filters write something more understandable - "ExtensionReferenceFilter[onMatch=EXCLUDE,extensions=jpg,jpeg,gif,png,ico,css,js,caseSensitive=false]" or "RegexMetadataFilter[onMatch=EXCLUDE,caseSensitive=false,field=Content-Type,regex=(application|audio|image|video).*]"

2. Prevent processing once restricted urls each next time. In my case i have 100K+ unique pages, each of them in it's master page has link to some analitics service (http://mc.yandex.ru), and each time it produce this log entry: `REJECTED_FILTER: http://mc.yandex.ru/watch/{someNum} (No additional information available.)`

**Comment by essiembre** [comment]
I just made a new [snapshot release](http://www.norconex.com/collectors/collector-http/download) that now logs more information when the rejection occurs because no "include" filters were matched.   Please confirm.

You can control what crawler events get logged by adjusting the log levels in the log4j.properties file.  For instance, to stop logging the REJECTED_FILTER entries, you can change the following to WARN:
```
log4j.logger.CrawlerEvent.REJECTED_FILTER=WARN
```

**Comment by aleha84** [comment]
Confirmed. More readable - `No "include" reference filters matched.`
