### ISSUE TITLE
question - how to make URLs less referential

### ISSUE THREAD

**Issue by danizen** [Norconex/collector-http#351]
I have a large number of URLs in my collected index like this:

https://report.nih.gov/./budget_and_spending/../nihdatabook/./charts/Default.aspx?chartId=53&catId=17

This is not the same thing as preferring rel="canonical", but it would work if there was such a link.   How does one generally clean this sort of thing up.

**Comment by essiembre** [comment]
Not sure why this one fell through the cracks.  I hope you closed because you found a solution.  If not, have a look at the [GenericURLNormalizer](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/impl/GenericURLNormalizer.html).  Look for the ``removeDotSegments`` normalization.

**Comment by danizen** [comment]
Yes, I found it.
