### ISSUE TITLE
How to tell which references are added

### ISSUE THREAD

**Issue by danizen** [Norconex/collector-http#352]
I think the log files have this information, but when I look at the "references" collection within the Mongo database, I'm not quite sure which of these means "accepted and processed":

In [25]: allstates = refs.distinct('crawlState', {'stage': 'PROCESSED'})

In [26]: allstates
Out[26]:
['REJECTED',
 'REDIRECT',
 'UNMODIFIED',
 'ERROR',
 'BAD_STATUS',
 'MODIFIED',
 'NOT_FOUND',
 'NEW',
 'DELETED']

I guess both "NEW', "UNMODIFIED", "MODIFIED" and "NEW" should all appear in a database, provided the committer has caught up.   Is that correct?

**Comment by danizen** [comment]
I guess the bigger question is how the crawlState, and stage relate to the Flow Diagram, which is very explicit.

Forgot to check the other stage, 'QUEUED', for states:

In [30]: allstates = refs.distinct('crawlState', {'stage': 'QUEUED'})

In [31]: allstates
Out[31]: ['NEW']

**Comment by essiembre** [comment]
The crawl stores are there to cache and keep track of URL processing/processed state.  So they can potentially hold any or all of the states.   If you are concerned about those making it to your Committer, only ``MODIFIED`` and ``NEW`` will trigger a commit "add" and ``DELETED`` will trigger a commit "remove".

Deletions can be caused by your "orphan strategy", or by URLs originally having a state of NOT_FOUND, ERROR, etc.. based on your SpoiledReferenceStrategy.  But in any case, the state for deleted files will be changed to ``DELETED`` before the commit "remove" no matter what the original state was.

Does that answer?

**Comment by danizen** [comment]
I guess.   So, after an url is committed, it would no longer appear in the `references` collection?
Or, would there be multiple `references` sharing the same url, in different states?

**Comment by essiembre** [comment]
For crawl stores, you can think of the document reference (e.g. URL) as a primary key.  So it should only appear maximum once per collection at any given time.    On next runs, the "cached" collection gets wiped out and the "references" one becomes the cache.  So you cannot assume entries are permanent.  Plus, if you ever need to recrawl from scratch, the recommended approach is to wipe the crawl store.  If you need a historic record of similar (i.e. permanent entries), you may want to use a different mechanism.

**Comment by danizen** [comment]
This confirms what I expected.
