### ISSUE TITLE
preParseHandler vs. postParseHandler

### ISSUE THREAD

**Issue by liar666** [Norconex/collector-http#385]
Hi,

Sorry to open an issue for this simple question. 

I've searched the web but could not find a clear answer: what is the difference between `preParseHandler` vs. `postParseHandler`? What are the assumptions for each one? When should I use one rather than the other?

Is it simply that one (post) is run after the other (pre)? What occurs betwwen the 2 (i.e. what is the "parsing" exactly)?

Thanks in advance

**Comment by essiembre** [comment]
"Parsing" in this context means extracting the raw text and metadata from a document, regardless of its content type.

That is, the text is extracted from binaries such as PDFs, MS Word, etc., or in the case of markup-based documents such as HTML, tags are stripped so you get only the content.  Extracted Metadata depends on each document.  They range from document properties to ``<meta>`` tags in HTML pages.

So ``preParseHandler`` takes place before text and metadata are extracted while ``postParseHandler`` executes after.

So if you need to deal with documents in their original form (e.g., you want to reference HTML tags using ``DOMTagger`` or else), you would use ``pre...``.  Otherwise, if you want to act on obtained metadata or the text only (without formatting or else), use ``post...```.

Using a handler that is meant to work on text only as a pre-parse handler can produce errors since many documents could be binaries.  You can use the ``restrictTo`` configuration that is available to all handlers to make sure your handler only applies to a specific content type.

Does that answer?

**Comment by liar666** [comment]
Perfectly, Thanks!
