### ISSUE TITLE
Updated webpage adding a new meta tag. Crawler is not updating index.

### ISSUE THREAD

**Issue by inpsolr** [Norconex/collector-http#388]
Hi @essiembre , 

I have successfully crawled some webpages in my website and added them to a collection in Solr. I have also setup a daily scheduled job to run the crawler. The problem is that **when I update my webpages and republish them, the new contents of the pages are not reflected in the search result after recrawling**. 

For example, I added a new metadata field to my pages. I can see those metadata fields in the page source. I then recrawled all the webpages. But, the metadata field is missing in the search result. 

**Is there something I have to do for the crawler to recognize that I have made changes to the page?**  If I clear the existing index and the working directory for the crawler, then recrawl, the metadata appears in the search results. **I would like to avoid having to clear up my index every time I make changes to my pages.**

**Comment by essiembre** [comment]
On subsequent runs, only if a file has been modified that it will be sent to your collection.  

By default, both the "Last-Modified" date in the HTTP header and the document content are checked for changes with [LastModifiedMetadataChecksummer](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/checksum/impl/LastModifiedMetadataChecksummer.html) (metadata checksummer) and [MD5DocumentChecksummer](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/checksum/impl/MD5DocumentChecksummer.html) (document checksummer) respectively.

There are different ways to resolve your issue.

Is the last updated date returned by your web server updated when you make your changes?  Making sure it is should be one solution.

Otherwise, you can configure ``MD5DocumentChecksummer`` to use specific fields instead, or you can replace the ``LastModifiedMetadataChecksummer`` with  [GenericMetadataChecksummer](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/checksum/impl/GenericMetadataChecksummer.html) for controlling exactly what fields to use to create a unique checksum.

Finally, you can also disable the checksummers altogether so changes are no longer detected (and document will be sent each time even if no changes were made).  You can do so like this:

```xml
<metadataChecksummer disabled="true" />
<documentChecksummer disabled="true" />
```

Please confirm if one of these options does it for you.

**Comment by amolpalek** [comment]
Thank you for the prompt response. I will test out your suggestions and get back to you.

**Comment by inpsolr** [comment]
Since my pages are dynamically generated, I don't believe the fist option of getting the last modified date is going to work, unless I am misunderstanding your suggestion. I get current date time for document.lastModified in the browser console. This means that the checksummer should always receive the page as modified. This is not the case.

As for the second option, I will need to remember to update the value of the new field every time I make changes to my solution that may affect the page? Is there a way to achieving this without having to manually set the date? This may work, but I am not sure how to implement this.

So, for now, the third option seems straightforward for my case. I will disable both checksummers whenever I have a new build. I will then turn it back on.

**Comment by essiembre** [comment]
To have it detect if ANY metadata field changed, you can first combine all fields first into a new one using 
[MergeTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/MergeTagger.html) as a post parse handler (``*.*`` regex), then reference that "source" field in the ``MD5DocumentChecksummer``.   But if you use those fields, you will no longer use the content for the checksum.

We can make it a feature request to be able to use a regular expression to identify fields in ``MD5DocumentChecksummer`` and/or have the ability to use the content **in addition**, to any other fields to create a checksum.

**Comment by inpsolr** [comment]
> ..have the ability to use the content in addition, to any other fields to create a checksum.

Sounds like a plan! This would be a white list approach. A black list approach, where we specify fields or tags that we want to exclude from the hash would also work. Does `MD5DocumentChecksummer ` hash the `<body>` tag right now, or is "content" a broader term?

**Comment by essiembre** [comment]
Marked as a feature request.  The "content" is the plain text extracted from documents.  For HTML files, it is indeed the body content, without any markup.

**Comment by essiembre** [comment]
The [latest snapshot](https://www.norconex.com/collectors/collector-http/download) now has this feature.  You can now specify fields using a regular expression on [MD5DocumentChecksummer](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/checksum/impl/MD5DocumentChecksummer.html) with the new option ``<sourceFieldsRegex>``.   You can also set this new attribute to combine fields and content: ``combineFieldsAndContent="true"``.  See the javadoc for more details.

Please test and confirm.

**Comment by essiembre** [comment]
These checksummer enhancements are now part of the official 2.8.0 release.
