### ISSUE TITLE
Orphaned items previously in sitemap are never deleted

### ISSUE THREAD

**Issue by mbrunnert** [Norconex/collector-http#390]
Hi, 

I have been getting into norconex as part of a search project and really liking it so far, thank you. 

I think I have come across an issue with the way sitemaps and the crawlerstore is handled, that causes sitemap pages that are orphaned to never be deleted. 

My understanding after reviewing the source code:

1) The sitemap last modified date is stored as part of the HttpCrawlData
2) Assume that a page with an old last modified date is removed, both from the sitemap and from the site
3) The crawler will at the end of the crawl handle orphans (AbstractCrawler). Assume the strategy is to process the orphans
4) For each orphan, the crawler will load the HttpCrawlData from the store and try to reprocess.
5) Because the sitemap last modified has been loaded from the crawlstore, the crawler thinks the page should not be crawled and returns a REJECTED_PREMATURE .
6) The orphaned page is never processed and therefore never deleted

Thank you.

Mattias

**Comment by essiembre** [comment]
Thanks for reporting this.  I understand the issue. I think you are right that if a URL is no longer referenced in a sitemap, we should no longer honor sitemap delays for it (and process it again if strategy says so).

I believe the same can be said about custom recrawl delays one has configured (see [GenericRecrawlableResolver](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/recrawl/impl/GenericRecrawlableResolver.html)).   

In which case I think we should change it so that orphans with "process" strategy should always be re-processed, regardless of delays associated with them.

Can you think of a scenario where this new behavior would not make sense?

**Comment by mbrunnert** [comment]
Hi, 

Yes that makes sense, I guess the only scenario I can think of is if if the last modified fetched in a header only request and is ignored because of this strategy.

**Comment by essiembre** [comment]
The latest [snapshot](https://www.norconex.com/collectors/collector-http/download) contains the fix for this.  Can you give it a try and confirm when you get the chance?

**Comment by essiembre** [comment]
This fix is now part of the official 2.8.0 release.
