### ISSUE TITLE
Question: How do you update content after configuration change?

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#391]
After making changes to http collector and recrawling and sending the documents to Solr, the documents that should now be filtered are still in index.

What is best way to handle this?

**Comment by angelo337** [comment]
OkkeKlein:
in order to remove documents from the index you could use  similar to:

http://localhost:8983/solr/collection_name/update?stream.body=<delete><query>q=</query></delete>&commit=true

in order to delete the documents, you should change q value for some that suit your needs.
Regards

**Comment by essiembre** [comment]
Not every changes in config can "undo" what was previously done.   But if you are using reference filters, you can try setting the ``orphanStrategy`` to delete.  That way, links that are no longer referenced (because of filtering in your case), should trigger a deletion on your committer and will no longer be processed.

For some config changes sometimes the best approach is to start fresh (deleting the workdir) after manually deleting the documents you no longer want in your index (like angelo337 suggests).

For major changes, sometimes a doing a full reindex (wiping your index first) may be simpler (if that's something you can do).

**Comment by OkkeKlein** [comment]
Yeah. This is what I have been doing. But then the index is empty for a while. So was thinking about an argument that you could pass that deletes index and commits at end of crawl. I assume collector now commits after queue was processed?

**Comment by essiembre** [comment]
For cases where you need to start from a clean index, you can create a temporary index and swapping it with your current one when done.

With the Solr Committer, you can control when commits are done with the ``<queueSize>`` configuration option.  Put it to a very large number if you want to avoid frequent commits (or low number for frequent commits).

**Comment by OkkeKlein** [comment]
Thanks for the info.

**Comment by essiembre** [comment]
You are welcome.
