### ISSUE TITLE
What is the intended way of running the collector?

### ISSUE THREAD

**Issue by ronjakoi** [Norconex/collector-http#398]
How does the HTTP Collector work? It comes with a script which, to my understanding, takes the seed URLs and starts crawling them according to the depth settings etc. in the XML, and then it stops when it can't find any more new links within the given constraints.

So, is the intended procedure to run the collector periodically from a cronjob, for instance? How do you determine a good interval? According to my tests, consecutive runs take different times depending on changes to the site structure and how many times the site has been crawled before, even if you don't change the maxdepth value.

Is there a way to run the collector continuously as a daemon with unlimited depth? Including periodical checks on already crawled URLs to see if they have changed?

**Comment by essiembre** [comment]
Yes, the intent is to use the OS scheduling mechanism.  

It is not intended to run as a daemon, but you can simulate it by having short schedule intervals.  It won't start if it is already running (will wait for the next scheduled cycle).  

Typically though, the expected frequency of site updates and how important it is for you to capture changes quickly will determine your best interval.   You normally try to play "nice" with sites you crawl. 
 So once a day could be just fine for the average site, while you may want to run it more frequently for a news site.

To run it with unlimited depth, set the ``maxDepth`` to ``-1``.

On subsequent runs, the default behavior is to check if files were modified or deleted.  If the file has not changed, it will not be sent again to your Committer.

Does that answer?

**Comment by ronjakoi** [comment]
Yes, thank you, but I have some further questions.

What's the best way to have the re-checking of already-crawled URLs happen frequently while also having a high crawl depth?

If I have `maxDepth` at 1 or 2, where is the depth calculated from? The seed URLs or the currently known maximum depth in the workdir?

**Comment by essiembre** [comment]
How big is your site?  If overall crawling does not take too long, simply have a frequent schedule.  Else, you have a few options to make things faster.

You can create a few different collectors, each targeting different parts of your site, each with a different schedule.  For example, you can run one that filters URLs on .*/news/.* running every 10 minutes, while having the rest crawled with a different schedule.

Another approach is to configure the [GenericRecrawlableResolver](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/recrawl/impl/GenericRecrawlableResolver.html).  With it, you can specify a minimum frequency before some pages get recrawled.  When a page is skipped because it is not ready to be recrawled, it does not wait before moving to the next one in line so it goes much faster.   Give bigger delays to pages that can wait longer to be recrawled.

The depth starts at zero with the start URLs you provide (or sitemap URLs).  Any unprocessed links found for these will be given depth 1, and so on.  The depth is basically the minimum number of "clicks" a user would have to do to get to a page from your start URLs.

**Comment by ronjakoi** [comment]
I think I've got the hang of separating things to a few different collectors which share the bulk of the config through includes.

**Comment by essiembre** [comment]
Great! Can we close?
