### ISSUE TITLE
Sending a Cookie

### ISSUE THREAD

**Issue by gordonthompson** [Norconex/collector-http#411]
I'm trying to spider a site that redirects to a EULA page if a specified cookie isn't present. 

How would I pass this cookie to the collector to avoid the redirect?

Thanks

Gordon

**Comment by essiembre** [comment]
Cookies are carried through by default once obtained.  So once it is passed the EULA it should keep going.   Do you know exactly when/how is the cookie obtained for a regular web user?  You could try to replicate doing the same when crawling.

Otherwise, there are few things you can consider.  First, you can extend ``GenericHttpClientFactory#createDefaultCookieStore()`` to create your own cookie store (set cookies you want to be used before crawling starts).

For a no-programming solution, you can set any HTTP request headers you like with the ``GenericHttpClientFactory``.  You can set the proper cookie information like this.  
```
  <httpClientFactory>
    <headers>
        <header name="Cookie">name1=value1; name2=value2; ...</header>
    </headers>
  </httpClientFactory>

If the cookie value expires, the above solutions may not work as a long-term solution and you should focus on getting the cookie from the website first (like a normal user would do).

**Comment by gordonthompson** [comment]
Thank you for your quick response. That helped lots!

**Comment by essiembre** [comment]
No problem!
