### ISSUE TITLE
Adding Fields to Index (i.e. <meta name="description".../>)

### ISSUE THREAD

**Issue by dhildreth** [Norconex/collector-http#413]
When using a config file based on the included simple example config and committing to Solr, I see these fields in search results:  `id`, `title`, `document.reference`, `content`, `_version_`.

I think I'd like to include meta description tags as well.  How would I get the crawler to extract meta description fields and then include them as a field in the search results?  Is there a better way?

**Comment by essiembre** [comment]
By default, the collector will send all fields it finds/extracts.  The ``KeepOnlyTagger`` is what limits the fields being sent in the sample config.  You can remove or modify it.  If your Solr is configured to accept any fields, you should get them all in Solr.  Otherwise, you may have to define them first.   A good idea is to use the ``FilesystemCommitter`` or use ``DebugTagger`` to know about the fields being found and adjusting your config to only keep those you want.

**Comment by dhildreth** [comment]
Okay, great.  I'll give it a whirl.  Thank you.
