### ISSUE TITLE
Links under mainnav div are not being crawled

### ISSUE THREAD

**Issue by epralsa** [Norconex/collector-http#423]
Hello
When we crawled https://www.ericsson.com/hyperscale  this link with your minimum-config.xml configuration with depth 1 . 

we are only getting -
https://www.ericsson.com/hyperscale
https://www.ericsson.com/en

but we are not getting link from div-
https://www.ericsson.com/hyperscale/why-ericsson-cloud
https://www.ericsson.com/hyperscale/cloud-infrastructure
[Norconex_32_Minimum_32_Test_32_Page.log](https://github.com/Norconex/collector-http/files/1454959/Norconex_32_Minimum_32_Test_32_Page.log)

How  we can get div links.

Best Regards,
Praloy Sarkar

**Comment by essiembre** [comment]
It appears to be because those URLs are not quoted in the ``<a href=...>`` tags, like this one:

```html
<a href=/hyperscale/why-ericsson-cloud>
```
If you control the pages you can surround the URL with quotes and it will work.

Since it is valid for URLs to be present in ``<a href=...>`` tags without quotes according to HTML specs, I will mark this as a feature request to support them.

If you do not control the content, you have options in the meantime.  You can switch to using the ``TikaLinkExtractor`` instead of the default ``GenericLinkExtractor`` one.  It does not have as many features but appears to support this use case.  Another approach would be to use the ``RegexLinkExtractor`` to catch those.

**Comment by epralsa** [comment]
Hello,
We have used TikaLinkExtractor to fetch required link with double quote .   We appreciate your Your feedback  . Thank you.

Best Regards,
Praloy sarkar

**Comment by essiembre** [comment]
``GenericLinkExtractor`` now extracts unquoted URL properly in the latest snapshot release.  

I know you have a working solution but it would be great if you could confirm the change works for you.

**Comment by epralsa** [comment]
Hello
Yes , Solution is working fine . Thank you very.

Best Regards,
Praloy Sarkar

**Comment by essiembre** [comment]
Thanks for confirming.
