### ISSUE TITLE
exit/return code to determine status?

### ISSUE THREAD

**Issue by venkatram88** [Norconex/collector-http#436]
Hi,

is there a exit code that is returned from the Java program when crawl fails due to 0 URLs processed(or for any other reasons).
I see ERROR messages being printed, but a exit code would be useful.

An exit code on the AWS cloud commiter would be useful too.

thanks,
Venkat V

**Comment by essiembre** [comment]
If the collector **aborts** due to an exception being thrown, then there is an exit code of ``-1`` returned.

I there are no URLs processed for something other than a fatal exception (e.g. no docs were modified), then you will not get an error code (will be zero).

It is possible to get exceptions/error without the collector aborting (e.g., when it can recover from the exception or decides to skip a bad document).  In which case, you will not get the error code either.

If you want to take specific actions when there are no URLs, or other conditions, you are probably best to look at alternate solutions, such as creating a custom [ICrawlerEventListener](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/crawler/event/ICrawlerEventListener.html).

**Comment by venkatram88** [comment]
Thank you, that helps.
