### ISSUE TITLE
REJECTED_CANONICAL – contentTypes?

### ISSUE THREAD

**Issue by ronjakoi** [Norconex/collector-http#438]
I noticed this in my log:

```
misc: 2017-12-03 23:03:16 INFO -        REJECTED_CANONICAL: http://www.REDACTED (GenericCanonicalLinkDetector[contentTypes={text/html,application/xhtml+xml,vnd.wap.xhtml+xml,x-asp}])
```

The site in question sends `Content-Type: text/html; charset=utf-8` in the response header. Shouldn't that match the `text/html` in my config?

The configuration looks like this:

```xml
#set($http      = "com.norconex.collector.http")
#set($linkExtractor     = "${http}.url.impl.GenericLinkExtractor")

<linkExtractors>
    <extractor class="${linkExtractor}"  maxURLLength="2048"
        ignoreNofollow="false" commentsEnabled="false">
        <contentTypes>
            text/html, application/xhtml+xml, vnd.wap.xhtml+xml, x-asp
        </contentTypes>
        <tags>
            <tag name="a" attribute="href" />
            <tag name="frame" attribute="src" />
            <tag name="meta" attribute="http-equiv" />
        </tags>
    </extractor>
</linkExtractors>
```

**Comment by essiembre** [comment]
You get this rejection because the identified URL is not a [canonical](https://support.google.com/webmasters/answer/139066?hl=en) one.  It tells crawlers another URL should be used to crawl that page.   This default behavior is normally what you want to avoid duplicate pages being crawled, but you can disable it by adding this to your crawler configuration:

```xml
 <canonicalLinkDetector ignore="true" />
```

**Comment by ronjakoi** [comment]
Oh, I see. This is a feature (of both Norconex and the web) which I was completely unaware of. Looks like everything is fine and working as expected.
