### ISSUE TITLE
Issue with special characters

### ISSUE THREAD

**Issue by murdock71** [Norconex/collector-http#445]
We have two environments using the HTTP collector, a production and QA. In our production environment everything is working fine, the same configurations in our QA environment are causing special characters such as ™ to be messed up when pulling them out of solr. It shows up as: â„¢

We do not necessarily think this is directly related to the collector but are at a loss as to what is causing it.

If I point the QA collector at the production pages the content shows up in Solr correctly. When pointing to the file generated from the same code and data in QA it gets messed up. These are XML files, when visually comparing them they are identical (although sort order of the objects can vary due to them being pulled out of a hashmap).

I would greatly appreciate any thoughts you might have on what could be causing this issue in our QA environment and not when pulling the data from production.

**Comment by essiembre** [comment]
Are you sure the charset of the XML files is the same on your QA server?  What is it?  It should normally not have an impact on the Collectors, but just in case, can you verify if your OS default locale/charset is the same in both environments?

Also, to rule out whether it is the Collector (or to see if the Collector can fix this), can you try as a test to use the ``FilesystemCommitter`` instead of the Solr Committer on a small batch just to compare if the saved files are identical (same charset) in both your environments.  You can make a copy of your existing config with different paths in it if you do not want to impact your current setup.

Also, either by using the ``DebugTagger`` or checking the extracted metadata, see what you have detected in both environments under ``collector.content-encoding`` and ``document.contentEncoding`` metadata fields.

Let me know what you find out from the above tests.
