### ISSUE TITLE
Why crawler <filters> applies to <startURL> link? 

### ISSUE THREAD

**Issue by tdrobcsak** [Norconex/collector-http#464]
Sorry but I tried to understand how does these <referenceFilters> works as I would like to collect content for certain urls which can be match with specific RegexRef expression, however since the  start URL is doesn't match that specific filter and crawler stops in very beginning. Expected behaviour would be that he would start the crawling in starting that page and would apply  crawlers filters to sub-link on that page only and not to initial start URL.
```xml
<startURLs>
        <url>(http://www.mysite.com/elite-sites)</urlr>    
 </startURLs>

</startURLs>
      <referenceFilters>
  
    <filter class="$filterExtension" onMatch="exclude">jpg,gif,png,ico,css,js</filter>
      <filter class="$filterRegexRef" onMatch="include">(http://www\.mysite\.com/experts/.*experts.*-\d*)</filter>
    
   </referenceFilters>
```
I couldn't find any good example on how to ignore filter for initial site, but apply to all filter only to links at that site.

**Comment by essiembre** [comment]
The filters apply to all URLs encountered, including the starting ones.  

If you want the main page as well, add it as an ``include`` filter:
```xml
<filter class="$filterRegexRef" onMatch="include">http://www.mysite.com/elite-sites</filter>
```

As an alternative, if what you want is the main page to be "followed" but otherwise not processed, move your existing "experts" filter under a ``<documentFilters>`` instead.  Document filters are invoked on a document after links have been extracted from it.  This [diagram](https://www.norconex.com/collectors/collector-http/flow) may help.

I noticed a few errors with your XML snippet: 

* Your start URL should not be within parenthesis.
*  ``</urlr>`` is mispelled
* ``</startURLs>`` is listed twice.

**Comment by tdrobcsak** [comment]
Thanks for answer now I understand how this works.
