### ISSUE TITLE
Does ReplaceTagger works with <content> header?

### ISSUE THREAD

**Issue by tdrobcsak** [Norconex/collector-http#484]
Hi Pascal

I have question wheather ReplaceTagger can/should be used to extract data from text between 
`<content>....</content>` using regexp? I was able to fetch data using XML commiter, however all important data i have are in <content> field. Thanks in advance for your support.

**Comment by essiembre** [comment]
You mean the ``<content>`` tags in the files generated by the XML Committer?  If so, no you cannot, since the Committer is the "final" (crawled/parsed/modified/etc) destination for a document.  You need to perform your operations *before* it reaches the Committer.  

What do you want to do with the data in the end?  Store it in a database, search engine, or else?

Can you give me a concrete example of a source document and the data/fields you want to extract?
