### ISSUE TITLE
URLs being rejected as non canonical

### ISSUE THREAD

**Issue by ohtwadi** [Norconex/collector-http#492]
This is just a question as I try to understand why certain URLs are being rejected as non canonical. This is even happening for some of my start URLs. As far as I can tell, these should be imported. What am I missing?

A couple of examples from the last run follow.

Following are deemed non canonical:
  DOCUMENT_FETCHED: http://www.calgarytransit.com
  REJECTED_NONCANONICAL: http://www.calgarytransit.com

  DOCUMENT_FETCHED: https://www.calgaryparking.com/web/guest/virtualpay
  REJECTED_NONCANONICAL: https://www.calgaryparking.com/web/guest/virtualpay

Relevant start URLs:
  http://www.calgarytransit.com
  https://www.calgaryparking.com

I noticed one of the .js files (Google analytics) being loaded does in internal redirect (307), could that be responsible?

I can certainly provide the full config and log file from this run, if you require.

Edit: I am running with the following options:
  stayOnDomain="true" stayOnPort="true" stayOnProtocol="false"

Thanks!
Harinder

**Comment by essiembre** [comment]
"Canonical" URL indicators are added to HTML pages or HTTP headers to help crawlers not crawl the same content multiple times, under different URLs.  You can search online for more information, like [here](https://moz.com/learn/seo/canonicalization).

Let's take your first URL as an example. If you view the source, you will see this tag in the ``<head>`` section : 
```xml
<link rel="canonical" href="/home" />
```
That signifies to crawlers that the "official" URL that should be used for crawling/searching for http://www.calgarytransit.com is in fact http://www.calgarytransit.com/home.  Since they share the same content, this prevents crawling duplicates.  So it rejects the ones that are not "canonical" in favor of the canonical ones (which you should find elsewhere in your logs).

It is a good feature to keep, but can disable it if you want to by adding this to your crawler:
```xml
 <canonicalLinkDetector ignore="true" />
```
Does that answer?

**Comment by ohtwadi** [comment]
Oh this is great. Thanks for all the details!
