### ISSUE TITLE
Help with crawling a Javascript site

### ISSUE THREAD

**Issue by ohtwadi** [Norconex/collector-http#495]
Hello!

I am having issues crawling a site which uses AJAX calls to bring in hyperlinks. The site is https://pub-calgary.escribemeetings.com; if you load it in a browser, dev tools will show that it makes a bunch of AJAX calls to https://pub-calgary.escribemeetings.com/MeetingsContent.aspx/PastMeetings in order to load most of the links after page load.

I have been experimenting with PhantonJSDocumentFetcher, with a 15 second renderWaitTime but not having much luck. 

```XML
<documentFetcher class="com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher"
				 detectContentType="true" 
				 detectCharset="true"
				 screenshotEnabled="false">
	<exePath>$phantomJsExePath</exePath>
	<renderWaitTime>15000</renderWaitTime>

	<referencePattern>^https://pub-calgary.escribemeetings.com$</referencePattern>

	<validStatusCodes>200,302</validStatusCodes>
	<screenshotDimensions>1024 x 768</screenshotDimensions>
</documentFetcher> 
```

Log:
> coc-wdd-crawler: 2018-06-07 13:02:09 INFO - PhantomJS screenshot enabled: false
> coc-wdd-crawler: 2018-06-07 13:02:09 DEBUG - Executing command: cmd.exe /C "C:\Users\hhanjan\Downloads\norconex-collector-http-2.8.1-SNAPSHOT\phantomjs-2.1.1-windows\bin\phantomjs.exe --ssl-protocol=any --ignore-ssl-errors=true --web-security=false --cookies-file="C:\Users\hhanjan\AppData\Local\Temp\cookies.txt" --load-images=false "C:\Users\hhanjan\Downloads\norconex-collector-http-2.8.1-SNAPSHOT\scripts\phantom.js" "https://pub-calgary.escribemeetings.com" "C:\Users\hhanjan\AppData\Local\Temp\1528398129798000000" 15000 -1 https "" "" 1.0 -1"

 In a browser, if you expand the "2026 Olympic and Paralympic..." accordion, you see 3 May links, I was expecting those to appear in the file dumped by PhantomJS.  To test this, I took that command and ran it manually and noticed that the resultant file does _not_ contain the links.

Am I missing some setting that will help? How can I further troubleshoot this?

Thanks!
Harinder

**Comment by essiembre** [comment]
It turns out the site you gave loads all divs/URLs upfront and caches them.  They are only "assigned" when you click to expand a category.  This is why you are not getting any with PhantomJS since they are not part of the DOM even after being loaded.  You would need to investigate PhantomJS scripting options to see if you can emulate the user clicking on each category.    Maybe its scripting can also read the values from the JavaScript variable used for caching (not sure if possible).  

You can also create a custom document fetcher and/or link extractor that would take all meeting titles and consider them as ajax-URLs, that you would submit via HTTP POST on https://pub-calgary.escribemeetings.com/MeetingsContent.aspx/PastMeetings

**Comment by ohtwadi** [comment]
Oh the problem is worse than I discovered. Thanks for all the help Pascal, much appreciated.
