### ISSUE TITLE
Collector's Log file name format

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#50]
Please find here as some question related to log, as my feedback after first using collector 2.*. I don't expect all things I noted here be classified as bugs or feature requests, and hope my experience help to increase collector-http's usability, make it more "friendly".

To automate some processes I'd like to read and parse collector's logs to control how processes are run.

I found the case, when crawler failed to init (I know that's normal when it is not starting if, for example, importer or committer isn't set correctly),  collector doesn't create/update workdir, including logs so the automation is unable to detect the collector haven't started at all. Or it is getting logs of previous successful launch so I can make mistakes when control running collector's instances. Is there a chance to detect had the collector launched at all automatically? How can I catch such rare, but real cases?

Let's continue :)

I found collector's logs at dir .../${workdir}/logs/latest/logs/ . Last "logs" path's part appeared after update to 2.* branch. You may keep the path as you like  but on my opinion it is senseless - already have a dir "logs" at one level upper.

I expected log have ${crawlerId}.log name format, but, for example, if crawler id is site.com_rss then the log file name is site.com_95_rss.log. Where 95 comes from? What is this?

May you tell me how to recognize crawler's latest log? May I build log name only having ${crawlerId} variable without listing .../latest/logs/ directory?

Thanks a lot for you help.

**Comment by AntonioAmore** [comment]
I should note that log file of development snapshot 2.0.2 has name ${crawler id}.log as expected. Looks like 2.0.1 bug.

**Comment by AntonioAmore** [comment]
I was wrong - even with v.2.0.2 log file name vary from launch to launch, and I can't get the sequence, Why it differs from crawler id?

**Comment by AntonioAmore** [comment]
**Update**: I can reproduce bug. If crawler id contains "_" symbol, it adds 95 number to the name. When I replaced "_" by "." all works like a charm.

The id of the crawler were: ```somename.im_rss``` . Hope it helps.

**Comment by essiembre** [comment]
That is by design.  The file names are based on the IDs, but they are escaped using a method that converts any non-OS-safe characters for file naming.   This allows anyone to put anything for their IDs without having back-end file creation causing any issues.   The method used is consistent and shall not changed from time to time.   If you are curious, the exact methods that deals with that can be seen [here](http://www.norconex.com/product/commons-lang/apidocs/com/norconex/commons/lang/file/FileUtil.html).  Look for the methods ``toSafeFileName`` and ``fromSafeFileName``.

**Comment by essiembre** [comment]
As for the log directory creation, it will append ``/latest/logs/`` on whatever base path your provide (and ``/backup/YYYY/MM/DD/logs/`` for backups).   The problem is the default behavior (and samples given) also have ``./logs`` as the base path.   The app should probably be updated to give a different base path... or just use the workdir and go from there.

The reason ``/logs/`` is added at the end is because other files are written as well, like "progress" files.  Those an be given the same base path (and maybe it should be default behavior).  This ensures they are not mixed together (e.g. ``/workdir/latest/logs`` vs ``/workdir/latest/progress``).

I'll consider changing default locations in a future release but in the meantime if that bothers you, configure the log directory to be the same as your workdir and you'll see it only once.

**Comment by AntonioAmore** [comment]
Sounds logical, yes.

At the workdir I haven't ```latest``` directory, possibly because I changed progress and logs at the config.

In scope of your comment everything looks well structured,  thank you for your reply.

**Comment by essiembre** [comment]
No problem, any time!
