### ISSUE TITLE
REJECTED_REDIRECTED preventing document commit

### ISSUE THREAD

**Issue by joettt** [Norconex/collector-http#511]
Hello, I have added maxRedirects and validStatusCodes to my attached configuration file but I still get 
```
REJECTED_REDIRECTED: https://gcconnex.gc.ca/groups/profile/39784216/e-div-prime-purge-epurge?language=en (HttpFetchResponse [crawlState=REDIRECT, statusCode=302, reasonPhrase=Found (https://gcconnex.gc.ca/login)])
```
error message as can be seen in the attached log file.

Any suggestions on how it can resolved?

Thanks.

**Comment by essiembre** [comment]
You did not attach a config or log file.  But the error indicates a URL gets rejected because it redirects to another one.  The target URL gets queued and will be processed only if it matches the results in your config.  The maxRedirect does not prevent URLs from being rejected if they are being redirected. It simply indicates the maximum redirection a single URL can have (URL A redirects to B that redirects to C that redirects to ...).  Does that help?   If not, please attach your config/log.

**Comment by joettt** [comment]
[config.txt](https://github.com/Norconex/collector-http/files/2300459/config.txt)
[logs.txt](https://github.com/Norconex/collector-http/files/2300460/logs.txt)

**Comment by joettt** [comment]
First of all I want to thank you for providing the norconex products (which work very well for my needs) and replying so promptly on the issues.  Your help is greatly appreciated.  My apologies for not attaching the files earlier.  In the config file, I have included the login pattern where the pages gets redirected to but getting the REJECTED_REDIRECTED error.

**Comment by essiembre** [comment]
It appears authentication was not sucessful since the redirection is towards the login page.  Probably tied to CSRF protection as described in https://github.com/Norconex/collector-http/issues/506#issuecomment-406908227.  You would likely need to apply the same solution you did for the other one.

**Comment by SolSearch** [comment]
I had applied the same solution but it may have to do with a bug in our app where after authentication, users are redirected to the homepage instead of the original page requested.  Although it does not explain why I am seeing REJECTED_REDIRECTED (reasonPhrase=Found https://gcconnex.gc.ca/login), I am going to wait for the developer to fix the bug and then try again.

**Comment by FireLizard** [comment]
I have the same issue as the origin issue describes.
* [config.txt](https://github.com/Norconex/collector-http/files/3112771/config.txt)
* [crawl.log](https://github.com/Norconex/collector-http/files/3112752/crawl.log)

https://www.dkfz.de/ - [302] redirects to
https://www.dkfz.de/index.html - [302] redirects to
https://www.dkfz.de/de/index.html --> This should be crawled.

Thank you in advice.

**Comment by essiembre** [comment]
I see you are using an older version.  Can you try with the latest and see if you still have the issue?  If so, please create a new ticket with the details since this one was closed a while ago.

**Comment by FireLizard** [comment]
I've upgraded to v2.8.1 but got the same result: [crawl.log](https://github.com/Norconex/collector-http/files/3141606/crawl.log)
