### ISSUE TITLE
 REJECTED_FILTER:  (No "include" reference filters matched.)

### ISSUE THREAD

**Issue by HappyCustomers** [Norconex/collector-http#517]
I ma facing the following problem, when I try to crawl the following URL

REJECTED_FILTER: https://xyz.com/en/india/bangalore (No "include" reference filters matched.)
	
StartURL ``<url>https://www.xyz.com/en/india/bangalore/</url>``
```
<filter class="$filterRegexRef" onMatch="include">https://www\.xyz\.com/en/india/bangalore.*</filter>
```
I have sent you an email with configurations

Thank you

**Comment by Krishna210414** [comment]
I am also getting the same error.

**Comment by essiembre** [comment]
At first glance, I see nothing wrong with the two lines of configuration you shared.  Can you share your full config?

**Comment by HappyCustomers** [comment]
Were you able to look into this issue? do  You need any further info ?
Thanks

**Comment by essiembre** [comment]
The config you attached does not seem the right one, since it has an obfuscated reference to ``www.xyz.com/`` in it.  That means I cannot tell for sure, but I had a closer look, and I see two potential problems with your config:

1. Your filter regex is for ``https://www\.xyz\.com/...`` while the rejected URL is ``https://xyz.com/...``.  Rejection is expected because the rejected URL is missing the required ``www.``.
2. Your config has ``stayOnDomain="true"`` which will also reject URLs that do not have ``www.xyz.com`` has the domain (with ``www``).

**Comment by essiembre** [comment]
Sorry I just saw your second email. What is an exact URL being rejected with it?  I suspect it is linked to the "stayOnDomain" flag.

**Comment by HappyCustomers** [comment]
I have sent you the log file and the configuration file along with the correct URL.  The error (No "include" reference filters matched.) usually occurs with the website where start URL is http and the website has https redirect. I have also made stayOnDomain = False.

**Comment by essiembre** [comment]
Please test your regular expression using a regex tool (there are several online ones).   I did so with what you sent me and I could quickly find the target URL rejected by your filter does not match your regex.  That is why it is excluded.  Your regex expects a forward slash at the end but the target URL does not have any.  E.g.: https://regex101.com/r/WuTkEF/1

**Comment by HappyCustomers** [comment]
Thanks for the quick response  as always. it is working. Closing the issue
