### ISSUE TITLE
Additional Input Parameters for <StartURls>

### ISSUE THREAD

**Issue by HappyCustomers** [Norconex/collector-http#521]
Hi,

I have requirement while loading the StartURls from a Text File , I need to pass additional parameter like URLID, URLName, URL and City to the collector which needs to be stored in MYSQL table along with output content data.

Example

Input Data
StartURLID----URLNAME---URL---CITY
01--ABC Corp---http://www.abc.com---New York

Output Data
StartURLID----URLNAME---StartURL---CITY--Content-----document.reference----title
01--ABC Corp---http://www.abc.com---New York--About US---http://www.abc.com/aboutus--ABCorp-About US
01--ABC Corp---http://www.abc.com---New York--Contact US---http://www.abc.com/contactus--ABCorp-Contact US

How can this be achieved in HTTP Collector?

Thank you

**Comment by essiembre** [comment]
If your requirements are getting too specific, I suggest you create your own IDocumentTagger that would add the proper metadata to your documents based on pre-defined mappings or basic analysis.  

Otherwise, you can do it via configuration alone, but it could get lengthy and hard to manage.  Not sure which approach would be best, but one way to do it could be using the ReplaceTagger.  For example, to map cities:
```xml
  <tagger class="com.norconex.importer.handler.tagger.impl.ReplaceTagger">
      <replace fromField="myDomainField" toField="city" regex="true"><fromValue>.*www.mysiteA.com</fromValue><toValue>New York</toValue></replace>
      <replace fromField="myDomainField" toField="city" regex="true"><fromValue>.*www.mysiteB.com</fromValue><toValue>Los Angeles</toValue></replace>
      <replace fromField="myDomainField" toField="city" regex="true"><fromValue>.*www.mysiteC.com</fromValue><toValue>Philadelphia</toValue></replace>
  </tagger>
```
You can also do it using the ScriptTagger if you find it any easier to implement such mapping.

**Comment by HappyCustomers** [comment]
This can be part of storing the StartURL feature where additional parameters of the startURL can be also be stored along with indexed content.
