### ISSUE TITLE
norconex 2.8.1 - how to get detail of FATAL error

### ISSUE THREAD

**Issue by mauromi76** [Norconex/collector-http#528]
Hello, 
we have installed the 2.8.1 version and we are using NORCONEX to crawl over 110 websites that are then indexed in Elastic Search 6.4.2 (we have downloaded and installed the ES commiter 4.1.0).

Our config.xml has kind of 110 <crawler id="xyz"> tags (one of for each website).
of course "xyz" is a different ID for each website.

at the end of the process, we noticed that in Elastic Search not all websites have been indexed so we checked the LOG of Norconex and we found many : **FATAL - Fatal error occured in job: xyz**

we just tried to relaunch the crawler and in the new log we found again some FATAL errors but on different websites (or maybe some same entries as before) while some websites that before generated the FATAL error are now indexed.

so this FATAL seems to be random and not connected to a specific website.

so the question is:
how can we get the details of this FATAL error to understand why this happens?

NB: in the previous version (2.7) this was never happening.
previously we were using norconex 2.7 and elastic search 5.5

thanks for the support
Mauro

**Comment by essiembre** [comment]
This typically occur on errors that we can't recover from. More often than not, it due to running out of memory.  Check your logs if you have exception stacktraces related to memory (or anything else).

The parsing of files (and their various formats) are sometimes quite demanding (CPU + RAM).  The more websites/threads you have, the more you risk of having multiple heavy processing of files happening concurently.    You may be reaching the maximum capacity of your system to handle these peaks.

Are the 110 websites part the same HTTP Collector configuration?  I recommend you try with less and see if it still happns.   I recommend you break your sites in multiple configs and run them separately, ideally distributing them on different servers to spread the load.

**Comment by mauromi76** [comment]
Hi Pascal
thanks for quick feedback.
I will try your solution to split the websites in multiple config files and run them one by one.
Will let you know if this will fix the problem.

thanks

**Comment by mauromi76** [comment]
Hello
I confirm that the problem was too many entries of the same config file.
we reduced to 25 entries for each XML and it worked fine with no FATAL errors.

if that can be useful, we are running the crawler allocating 2GB of Memory (-Xmx2G )
the result was:

- on an XML with 110 entries it was generating FATAL errors on some entries

- on an XML with 25 entries it worked fine.

we will now test and tune up to check the best nr of entries Vs allocated memory.

thanks a lot for the support.
I mark this as closed.

Mauro

**Comment by essiembre** [comment]
No problem.  I was assuming here you were using many threads to support many sites.  On second thoughts, the number of threads is probably more harmful than the number of sites.  So try reducing the number of threads as well or instead.
