### ISSUE TITLE
maxDepth and Filter

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#53]
I've tried maxDeph 10 and onMatch="include" > http://www\.norconex\.com/.* in "minimum" test, but I don't get it working.

I have 3 documents in Solr:
http://www.norconex.com/product/collector-http-test/minimum.php
http://www.norconex.com/collectors/img/norconex-logo-blue-241x51.png
http://www.norconex.com/collectors/img/collector-http.png

but not:
http://www.norconex.com/collectors/collector-http/configuration

Carlos

**Comment by essiembre** [comment]
That's expected.  That last URL is using a JavaScript trick to make sure it is not being crawled (you can see for yourself by viewing the page source).

That's because beyond the test pages, we want you to crawl your own site(s).  We do not want every testers to crawl our entire site, as it would eventually impact its performance. :-)   

Since you got all the others, it means you are doing just great.  I think you are ready to move beyond the tests.   Good job!

**Comment by csaezl** [comment]
Thanks
Carlos
