### ISSUE TITLE
403 processing

### ISSUE THREAD

**Issue by dtcyad1** [Norconex/collector-http#542]
Hi,

this is not so much an issue, but rather a what happens question

1. If a document is determined to be too deep, is it rejected without it being added to the crawlstore? The reason I ask is that if the depth were to be increased so that it falls with the depth, will it be recrawled on subsequent crawls  based on the data in the crawlstore or just never be considered?

2. A reverse of the above - if a document was previously crawled and now is deemed too deep due to the depth setting change, will a delete be issued to the committer?

3. similar thing as above, but with forbidden errors (403). On subsequent runs, will the urls be tried again?

4. For Forms authentication - how are cookie timeouts handled? If my authentication is valid for 5 mins - how can i force a new client every 4 mins to keep the cookie alive?

Thanks

**Comment by essiembre** [comment]
1. Documents rejected because they were too deep should be picked up on next crawl.

2. Same, unless you configured differently.  Documents that were once "good" and are no longer are considered "spoiled".  Then you can configure how those are handled.  See ``GenericSpoiledReferenceStrategizer``.   Also, links that are no longer reachable are considered "orphans".  You can set your orphan strategy to "DELETE" to have those removed.

3. Yes, see the "spoiled" strategies you can adopt (see previous answer).

4. Every authentication being different, I would have to know more.  The default ``GenericHttpClientFactory`` uses Apache HttpClient which maintains cookies. Unless there is more than a 5 minutes delay between two page downloads on the same site, it should maintain the cookie session active automatically.  If your site authentication has some custom behaviors, things may be different and may require a custom authentication solution.  Maybe open a new ticket just for this if you notice issues and please provide more details about your authentication mechanism.

Despite the above answers, it is often recommended to perform a "clean" crawl when making configuration changes if you want to make sure all documents get revisited with your changes.  When in doubt, test it! :-)

**Comment by dtcyad1** [comment]
Thanks for the answers!!
