### ISSUE TITLE
sitemap url crawl

### ISSUE THREAD

**Issue by dtcyad1** [Norconex/collector-http#547]
Hi Pascal,

I need to only crawl the urls that are in the sitemap. So if the sitemap has 10 urls, then those are the only ones i want to crawl. The first time i run it, everything is fine. But on subsequent re-crawls, I get REJECTED_TOO_DEEP for all of them. Am I using the config correctly?

<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
	      <sitemap>https://test.com/sitemap.xml</sitemap>
      </startURLs>

      
      <maxDepth>0</maxDepth>

Is that the correct setting for the Depth (since I dont want any urls found on the pages themselves to be followed and crawled?) Also, should it also behave the same on the first time?

Thanks

**Comment by essiembre** [comment]
Is this all you are getting?  If the files have not changed, are you getting REJECTED_UNMODIFIED as well? 

Please share a config that reproduces the issue.

**Comment by dtcyad1** [comment]
Hi Pascal,

My apologies. 

I see a status of REJECTED_PREMATURE for all of them. Is that because the date in the sitemap did not change? If that is so then we are all good!!

So will the REJECT_UNMODIFIED ever be present for the sitemap crawl? When does the REJECTED_PREMATURE vs REJECTED_UNMODIFIED appear?

Thanks

**Comment by essiembre** [comment]
There are a bunch of elements that can be added to each URLs in a sitemap.xml.   The two that pertains to your question are (sample):
```xml
      <lastmod>2005-01-01</lastmod>
      <changefreq>monthly</changefreq>
```
Unless you overwrote default sitemap processing by the HTTP Collector, the ``changefreq`` value is used to find out whether we should recrawl a document or not (regardless of last modified date).  If not enough time has passed since a URL was processed, you will get the ``REJECTED_PREMATURE``.

If enough time has elapsed, or if ``changefreq`` is not specified, it will look at ``lastmod`` to find out if the file has changed since last time it was processed.  If the date has not changed, you will get ``REJECTED_UNMODIFIED``.  This all occurs before a URL gets downloaded (to prevent unnecessary downloads).   

You can also get ``REJECTED_UNMODIFIED`` if the date is different, but the crawler found out the content has not changed after it downloaded it and extracted its content.

Does that answer?

**Comment by dtcyad1** [comment]
Hi Pascal,

This is great!! 

Thanks!!
