### ISSUE TITLE
Tesseract 4.x not working

### ISSUE THREAD

**Issue by niozasg** [Norconex/collector-http#572]
After many tries with Tesseract ocr, I realized that Norconex managed to obtain text from image files , only with  Tesseract version 3.xx.  It seems, Norconex is not yet compatible with Tesseract 4.x for images ? I actually managed to use version 4.x only for .pdf files.

**Comment by essiembre** [comment]
Tesseract is run as an external command.  So if the version you have supports images, it should work.

I think maybe images are filtered out when you crawl?  It works for PDF because its embedded images are not filtered out.

Can you double-check that and if you can confirm you are processing images, but OCR does not kick-in as it should, please share a config to reproduce.

**Comment by jetnet** [comment]
Tesseract 4.x has different start parameters, I'm not sure, how it gets invoked (via Tika or Norconex), but when it gets started like this:
```
$ /usr/bin/tesseract /tmp/apache-tika-5101498626982503112.tmp /tmp/apache-tika-1478024623766530058.tmp -l deu+eng -psm 1 txt -c preserve_interword_spaces=0
Error, unknown command line argument '-psm'
```

**Comment by jetnet** [comment]
Tika should be updated to 1.18: https://jira.apache.org/jira/browse/TIKA-2613
Thanks!

**Comment by essiembre** [comment]
Please try the latest snapshot release and confirm.  It was upgraded to use Tika 1.18.
