### ISSUE TITLE
GenericCanonicalLinkDetector leads to unexpected crawled sites

### ISSUE THREAD

**Issue by SaschaHeyer** [Norconex/collector-http#587]
Hi Pascal,

when crawling a site with a canonical link to another domain, this domain is then crawled as well even though this domain is not listed as startURL.

The startURLs are configured as
```
stayOnDomain="true"
```

Is this the expected behavior for canonical handling?

Best regards
Sascha

**Comment by essiembre** [comment]
The "stayOnDomain" means only links matching the parent page domain will be extracted to be also crawled.  In this case, since the canonical version is the one you want, it chooses it, and all its links are extracted, only if they match that new canonical domain.

If you are not interested to only crawl canonical material, can disable that feature with 
```xml
  <canonicalLinkDetector ignore="true" />
```
You can also use a [RegexReferenceFilter](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/filter/impl/RegexReferenceFilter.html) for more control on what URL to include/exclude.

**Comment by SaschaHeyer** [comment]
Thanks for the explanation.
RegexReferenceFilter sounds like a good way to solve this behavior. 

It was just somehow unexpected to see domains in the index which I had never configured. It took me some time to realize that the canonicals might caused this. And I agree with you if the canonicals links are pointing to another domain this should be indexed as well (at least as default).

Thank you
Sascha
