### ISSUE TITLE
[Q] Is it possible to keep only x days of backup logs?

### ISSUE THREAD

**Issue by ohtwadi** [Norconex/collector-http#593]
Hello,

Currently the logs under logs/latest are simply moved to logs/backup directory. As a result, the logs/backup directory continues to grow. We would like to limit how many logs are kept inside logs/backup. Everything I have found regarding this recommends setting up a scheduled task to nuke older logs. So I just wanted to check directly with you on whether it possible to do this via configuration?

Thanks!

**Comment by essiembre** [comment]
A new [snapshot release](http://www.norconex.com/collectors/collector-http/download) of HTTP Collector was just made.  You can now add ``unmanaged="true"`` to the logsDir configuration option to tell the collector not to manage file-logging.  E.g.:

```xml
  <logsDir unmanaged="true"/>
```
With that new flag, the collector will no longer generate any logs by itself.  With the default ``log4j.properties``, that means it will log to the "console" only.  If you want it to still write to a file and limit the quantity and volume, you can modify the log4j.properties file to do so.  Here is an appender example that will rollover log files larger than 10MB and keep only a maximum of 5 log files:

```
log4j.appender.rollingFile=org.apache.log4j.RollingFileAppender
log4j.appender.rollingFile.File=/path/to/your/preferred/location/mycollector.log
log4j.appender.rollingFile.layout=org.apache.log4j.PatternLayout
log4j.appender.rollingFile.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %m%n
log4j.appender.rollingFile.MaxFileSize=10MB
log4j.appender.rollingFile.MaxBackupIndex=5
log4j.appender.rollingFile.append=false
 
log4j.rootLogger=ALL, rollingFile
```

A few dependencies were updated, so make sure you use a fresh install, or that you do not have multiple versions of the same ``.jar`` files under ``lib``.

**Comment by jetnet** [comment]
Question regarding the Jef-monitor: is it true, that if you configure logs to be "unmanaged", then JEF UI will not be able to display job's logs any longer?
Thanks!

**Comment by essiembre** [comment]
That is correct.

**Comment by dtcyad1** [comment]
What happens if we we match the path of the new log file to the original one. Will the JEF Monitor be able to use that even though the "unmanaged"setting is true? The original log4j file is still being used, with the only exception of it now being rolling?
Thanks

**Comment by essiembre** [comment]
If you look under your working directory, you will find somewhere a file called ``[Your Crawler Name].index``.

That file keeps track of where your progress files are located and what log manager was used to retrieve the logs.  This is what JEF Monitor uses since it does not interact with the processes directly (to not mess with them), it simply reads their progress output.

The default log manager portion of that file looks like this:
```xml
<logManager class="com.norconex.jef4.log.FileLogManager"> 
 <logDir>/some/path</logDir>
</logManager>
```
Right now, since you are using "unmanaged", it is probably like this:
```xml
<logManager class="com.norconex.jef4.log.NoLogManager"/>
```
So the only way I can think of at the moment is if you somehow manage to copy that index file just for JEF Monitor usage, and change its content to use a log manager like the first example above.  Also, change the other paths if need be.

**Comment by dtcyad1** [comment]
Hi Pascal,

Thanks
