### ISSUE TITLE
Combination of ReferenceFilter

### ISSUE THREAD

**Issue by FcrbPeter** [Norconex/collector-http#599]
I got a complex case of reference filtering.

The config would be looked like this:
```
<!-- Exclude eCommerce PANAM -->
<filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude">
	.*\/.*\?.*
</filter>

<!-- Exclude eCommerce PANAM -->
<filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude">
	.*\/.*\/.*
</filter>

<!-- Include back a set of URLs which are matched as exclude before
<filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="include">
	.*\/catalog\/seo_sitemap\/product\/(\?p\=[0-9]*|$)
</filter>
```

The behaviour of the crawler would look like the document is marked as exclude when one of the rules is matched.

Is there any workaround? Thanks!

**Comment by essiembre** [comment]
Do you have only these 3 filters?  If so, you only need the third one.  Because the include will only allow what is matching, and exclude everything else.  Isn't it what you want?

Otherwise, you can rewrite your filters to make use a negative lookahead expression, to include/exclude anything NOT matching your expression, like:

```
^(?!.*catalog\/seo_sitemap.........).*$
```

If that does not solve your problem, please share all your filters with concrete examples (a few sample URLs along with the expected behavior).

**Comment by FcrbPeter** [comment]
Thanks for replying.

The filter rules are a bit complex.

For examples, I got the links in the website below and marked which need to crawl or commit.
```
/catalog/seo_sitemap/product/ (need crawl, not commit)
/catalog/seo_sitemap/product/?p=2 (need crawl, not commit)
/catalog/seo_sitemap/product/?p=3 (need crawl, not commit)
/projektor-h6521bd-weiss (need crawl, need commit)
/3-years-send-in-projectors (need crawl, need commit)
/checkout/cart/ (not crawl)
/laptops/gaming?dir=asc&graphics=461&order=price... (not crawl)
/catalog/product_compare/add/product/2400/uenc/.... (not crawl)
```

There are two main rules to avoid crawling the unwanted links.
1. Ignore the links with query part (contains ?)
2. Ignore the links with more than one child path (ex: /laptops/gaming, /checkout/cart/)

However, there are a set of sitemap pages which are more than one child path (/catalog/seo_sitemap/product/) and contains page number as query (?p=2)

That's why there are three filters come out.
```
<!-- Exclude eCommerce PANAM -->
<filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude">
	.*\/.*\?.*
</filter>

<!-- Exclude eCommerce PANAM -->
<filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude">
	.*\/.*\/.*
</filter>

<!-- Include back a set of URLs which are matched as exclude before
<filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="include">
	.*\/catalog\/seo_sitemap\/product\/(\?p\=[0-9]*|$)
</filter>
```

The logic behind the filters is ignore unwanted links except a special case.

Is it possible to achieve this logic?
Thanks.

p.s. Hope you can understand my poor english and explanation.

**Comment by essiembre** [comment]
I am having trouble understanding your explanation, but your examples help.  If I get you right, you only want URLs with a single segment and no question marks, except for sitemap URLs.  Correct?  If so, I think the challenge is more a regular expression one.  A variation of the following under your crawler configuration should give you that (untested):

```xml
<!-- Before download: -->
<referenceFilters>
    <!-- Include seo urls: -->
    <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="include">
        .*/seo_sitemap/.*
    </filter>
    <!-- Include only URLs with one segment, no question mark: -->
    <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="include">
        ^https?:\/\/([^\/]+?)(\/)([^\/\?]+)$
    </filter>
</referenceFilters>

<!-- After download and after links are extracted: -->
<documentFilters>
    <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude">
        .*/seo_sitemap/.*
    </filter>
</documentFilters>
```

Have you stripped out the domain portion on purpose? Your regular expressions won't work since http:// contains two slashes already.  Make sure to account for that (like I did above).

**Comment by FcrbPeter** [comment]
Thanks for the solution, I tested it and it works fine.

For the http://, I have just stripped out the protocol and domain in the examples only.
I add it back when writing the configuration file.

I will mark it close, thanks again.
