### ISSUE TITLE
[Q] limit number of active crawlers

### ISSUE THREAD

**Issue by jetnet** [Norconex/collector-http#602]
hello Pascal,

one question: is it possible to limit the number of simultaneously running ``<crawler>`` for a ``<httpcollector id="...">``? For example, if there are 1000 ``<crawler id="...">`` configured, I'd like to have only 2 of them to be processed in parallel. As far a I can see, currently, HTTP-collector creates threads for all of them, which slows down everything dramatically (maybe because of CPU context switches?).
Thank you!

**Comment by essiembre** [comment]
I understand.  Crawling, in general, can be quite taxing (some file types are heavy to parse).  You could, of course, break your configuration down to multiple Collector configs.  You can then use dynamic configuration fragment includes so you do not repeat all your configs.  Having multiple configs can make things easier to troubleshoot if just a few sites need to be revisited.

Otherwise, you have a few options.

In the latest snapshot release, you now have an option on the collector-level called ``<maxParallelCrawlers>`` that does exactly what you want to do (thanks to @martin-huber).

Another approach is to look at the crawler-level ``<delay>`` feature.  There you can have an option to have each crawler respect a certain delay between each page download, regardless of the number of threads in each crawler.  Not quite the same effect, but that can also help reduce the load.

Can one of these approach work for you?

**Comment by jetnet** [comment]
Thanks, Pascal! I'll try the new parameter - you're right, that's exactly what I'd like to have!
FYI: in the meantime, we start NC instances using a unix tool `parallel -j <number-of-NC-insances>`, where each instance processes just one site. That is working quite good!
But `maxParallelCrawlers` is much more elegant.
This issue can be close - if I find an issue with the new parameter, I'll open another one :)

**Comment by essiembre** [comment]
Great, thanks for getting back.
