### ISSUE TITLE
REJECTED_CANONICAL question

### ISSUE THREAD

**Issue by dtcyad1** [Norconex/collector-http#603]
Hi Pascal,

I am getting REJECTED_CANONICAL for a lot of pages. All these pages have self referencing canonical tags

like the page:
https://test.com/senior-strategy-manager

has this:
<link rel="canonical" href="/senior-strategy-manager" />

In ICanonicalLinkDetector.java

there is a line:

"A canonical link found to be the same as the current page reference is ignored"

Does this mean that the whole page is ignored?

Thanks

**Comment by essiembre** [comment]
No, it means the link itself is ignored.  Meaning it will not be "followed".  The log entries are probably reflecting excluding these.   Can you confirm the documents are otherwise crawled?  Are they committed?

If you know you do not have any "non-canonical" pages, you can turn off the canonical detection by adding this to your crawler configuration:
```xml
 <canonicalLinkDetector ignore="true"/>
```

**Comment by dtcyad1** [comment]
Hi Pascal,

Thanks - I just wanted to confirm the behavior. They are not crawled unless I turn off the canonical detection.

Thanks 
-yogesh

**Comment by essiembre** [comment]
Thanks for confirming.  Does that mean you have a solution that works?  Can we close?

**Comment by dtcyad1** [comment]
Hi Pascal,

Yes - we can close this. 

Thanks again for this awesome web crawler!!

Thanks
