### ISSUE TITLE
GenericLinkExtractor - extend Referrer data

### ISSUE THREAD

**Issue by jetnet** [Norconex/collector-http#608]
hello Pascal,

is it possible to store additional referrer's metadata from <img> links? E.g. if we've got the following <img>:
```
<img src="/ff-test/activity2.gif" alt="Photo activity" title="Title activity"/>
```
then the collector stores the following referrer's metadata:
```
collector.referrer-link-tag = [img.src]
collector.referrer-reference = [http://localhost:88/ff-test.html]
```

It'd be great to store all available attributes as well, something like:
```
collector.referrer-link-tag = [img.src]
collector.referrer-reference = [http://localhost:88/ff-test.html]
collector.referrer-link-alt = [Photo activity]
collector.referrer-link-title = [Title activity]
```
Thanks!

**Comment by jetnet** [comment]
actually, `TikaLinkExtractor` extracts the `alt` attrubute to `collector.referrer-link-text`
I guess, I'm fine now :)

**Comment by essiembre** [comment]
I'll close then, thanks for confirming. If there is more you want that is not offered at some point, open another one and we will make it a feature request.

**Comment by angelo337** [comment]
hi there Pascal,
I am trying to extent referrer page data with data that is not on the Link, instead is on the body of the page, this in order to enrich data of beanery documents (PDF and OFFICE files).

my scenario is currently like this:

pag_A (referrer) ------> PDF_file(target)

on page_A I got Version information and some time data in the body 

PDF_file is a form with a lot of fileds but in order to obtain more relevant doc's I need to include in my search all version and dates of my Target.

Is it possible?

thanks a lot
Angelo
