### ISSUE TITLE
monitoring norconex in production 

### ISSUE THREAD

**Issue by shradhatx** [Norconex/collector-http#611]
In production, I like to set alert whenever there is an error. For that I can redirect the standard output to error.txt and if the error.txt exists I like to be alerted.   
./collector-http.sh -a start -c gcs-crawl-config.xml 2>error.txt

The error.txt for a good run shows and I like to turn all this off. I tried settings in log4j.properties to ERROR for various settings but cannot get rid of these lines in stdout.  
How can I achieve  this or whats the recommended way to monitor successful run in production?

Jun 04, 2019 8:51:17 AM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: JBIG2ImageReader not loaded. jbig2 files will be ignored
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.
J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.

Jun 04, 2019 8:51:36 AM com.google.enterprise.cloudsearch.sdk.BatchRequestService shutDown
INFO: Shutting down batching service. flush on shutdown: true

**Comment by essiembre** [comment]
These errors are from dependent libraries with their own logging framework.  You can at least work on the warning by including the missing dependencies.  It is complaining about two jars missing in your lib folder. Those are not shipped with HTTP Collector due to licensing restrictions affecting distribution.

JBIG2: https://search.maven.org/remotecontent?filepath=com/levigo/jbig2/levigo-jbig2-imageio/1.6.5/levigo-jbig2-imageio-1.6.5.jar

JPEG2000: https://search.maven.org/remotecontent?filepath=com/github/jai-imageio/jai-imageio-jpeg2000/1.3.0/jai-imageio-jpeg2000-1.3.0.jar

Let me know if that helps.
