### ISSUE TITLE
Url Recrawl frequency. 

### ISSUE THREAD

**Issue by thawkins** [Norconex/collector-http#619]
Is there any way of setting the frequency of retrieving feed like objects like RSS feeds and Sitemaps and also setting the priority and recrawl frequency of pages based on how they where discovered. 

example:
## For RSS Feeds 
be able to set rssfeeds to be recrawled every 6 hours
for all links discovered via this method to be fetched and committed at the highest priority

## For Sitemaps
be able to set sitemaps to be recrawled every 12 hours
for all links discovered via this method to be fetched and committed at a medium priority

## for standard pages
for all links discovered via this method to be fetched and committed at a lowest priority
able to recrawl every day for the first 7 days and then every 14 days after that. 

The reason is if you are using the crawler to gather news, articles from feeds (rss and sitemap) are high priority articles, pages are also most likely to be updated in the first 7 days while they are a hot story. 

Is it possible to set up this configuration out of the box, or will it need special code, if that is the case what pointers would be available to help us do that coding?

**Comment by essiembre** [comment]
If you rely on sitemaps, the crawler will by default honor the frequency specified in it or will recrawl if a document date changed.  Otherwise, what you want can be accomplished a few different ways.  

You could create different instances of the collector and create a cronjob (or windows scheduled task) to run each one at the frequency you want.  This is often not ideal.

Another option that often works best is to have your crawler run on a frequent schedule but use a "recrawlable resolver" to skip those that are not yet ready to be recrawled.  A generic implementation is provided out-of-the-box and is quite flexible:  [GenericRecrawlableResolver](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/recrawl/impl/GenericRecrawlableResolver.html).  With it, you can set a minimum recrawl frequency to different URL patterns.
