### ISSUE TITLE
REJECTED_REDIRECTED forced unexpected DOCUMENT_FETCHED

### ISSUE THREAD

**Issue by SaschaHeyer** [Norconex/collector-http#621]
Hi Pascal, 

I found the following behavior:

* We have `page1.html` which is correctly processed as `REJECTED_PREMATURE`.  (due to no changes in the sitemap lastmod).
* And we have a second page `page2.html` which redirects to `page1.html`.
* This redirects leads to a `DOCUMENT_FETCHED` for `page1.html` even though it was already correctly listed as `REJECTED_PREMATURE`

```
2019-07-08 18:32:39 INFO - REJECTED_PREMATURE: https://obfuscated/page1.html
2019-07-08 18:32:45 INFO - REJECTED_REDIRECTED: https://obfuscated/page2.html
(HttpFetchResponse [crawlState=REDIRECT, statusCode=301, 
reasonPhrase=Moved Permanently (https://obfuscated/page1.html)])
2019-07-08 18:32:46 INFO - DOCUMENT_FETCHED: https://obfuscated/page1.html
```

I would expect the following output:

```
2019-07-08 18:32:39 INFO - REJECTED_PREMATURE: https://obfuscated/page1.html
2019-07-08 18:32:45 INFO - REJECTED_REDIRECTED: https://obfuscated/page2.html
(HttpFetchResponse [crawlState=REDIRECT, statusCode=301, 
reasonPhrase=Moved Permanently (https://obfuscated/page1.html)])
2019-07-08 18:32:46 INFO - REJECTED_PREMATURE: https://obfuscated/page1.html
```

Best regards
Sascha

**Comment by essiembre** [comment]
Interesting... I will investigate further.  Could be a bug.

**Comment by essiembre** [comment]
After investigating, I could not reproduce.  

When redirect occurs, it is possible for a page to be queued for processing a second time (but not more). This is intentional, in case of redirect loops or other odd cases (e.g. login redirecting back to original URL).  The reason for this behavior is described in #533.

I tried to reproduce the issue on my side, but while the page gets processed (but rejected) a second time for the above reasons, it comes up the second time still as REJECTED_PREMATURE.

The fact that you get something different the second time it is accessed suggests that the conditions have changed between the first and second time the page is processed.  Is it possible for instance enough time has elapsed between the two attempts so that the page suddenly became eligible for recrawl?  

If so, it is working as designed for now.  If that's not the case, I would need a copy of your configuration that can reproduce it (you can send by email if sensitive).

I am aware the occasional double-processing on redirects is not ideal, but it gets the job done until the next major release where the approach may be reconsidered.  Keep in mind it does not do that for all your URLs, just some of the redirected ones.  There should normally be no harm other than the extra processing.

**Comment by SaschaHeyer** [comment]
Hi Pascal,

thank you for your efforts. 
We found this entry in the logs

```
java.lang.IllegalStateException: Chunk 12626972 no longer exists [1.4.196/9]
```

After that error message Norconex started to re-crawl every document. 
Do you think this is might be related to this behavior?

In the meantime we are also investigating if some of the conditions might have changed.
But I wanted to make sure that this chunk issue is not causing our behavior. 

Best regards
Sascha
