### ISSUE TITLE
Document checksumming and start/stop collector logic

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#63]
I run a crawler first time with parameter ```-a start```, and it normally finishes it's working. When I run it second time with the same config and ```-a start ``` it commits same pages.

Actuallyn I expected it skips pages which haven't updated since the last launch.

In config I'm using 
```xml
<crawlerDefaults>
       <documentChecksummer class="com.norconex.collector.core.checksum.impl.MD5DocumentChecksummer" /> 
...
```

and sure there are no other checksummers in crawlers configs.

**Comment by essiembre** [comment]
What tells you they are reprocessed? Are they found in your target repository?  If it was committed on subsequent runs, that should be because the checksum is different.  Maybe the DEBUG loglevel can give you more details. Often one reason for being different is having dynamic content in the page.  Can you share the URL you use to replicate the error?  What if you the checksummer to use a specific field just as a test that the checksum works.  For example:

```xml
  <documentChecksummer 
      class="com.norconex.collector.core.checksum.impl.MD5DocumentChecksummer"
      sourceField="title" />
```

Replace title with whatever short field you know will be the same every time.  Do you still have the same behavior?

**Comment by essiembre** [comment]
This turns out to be a bug, which was address in issue #66.  The latest snapshot should fix your problem.

**Comment by essiembre** [comment]
[Norconex HTTP Collector 2.1.0](http://www.norconex.com/collectors/collector-http/download) was released. Closing.
