### ISSUE TITLE
Removal of referred urls 

### ISSUE THREAD

**Issue by jackpay** [Norconex/collector-http#661]
I notice that in the GenericLinkExtractor the setKeepReferrerData() is deprecated, and that all referral data is now kept. 
This significantly increases the size of the resulting crawldb.
I am able to retrospectively open the mvstore and remove them, but I was wondering if this will break the crawl database in anyway?
Essentially, why is referral data now always kept? 
Thanks for you help.
J

**Comment by essiembre** [comment]
It has been deprecated since version 2.6.0 (August 2016).  So unless you are using a version older than this, you have been running with this change for a while.

The reason for always including the reference data is a combination of people needing this more and more, as well as more features started to dependent on it (I don't remember exactly which ones as it's been a while).   After more than 3 years, it was not reported has having any negative impact but it cover more use cases.

Are you experiencing performance issues? You can change the crawl store implementation (or implement your own) if you are dealing with millions and need something that scales more (like the MongoDB crawlstore implementation).
