### ISSUE TITLE
How do I eexplore data in mvstore files with SQL Workbench?

### ISSUE THREAD

**Issue by LeMoussel** [Norconex/collector-http#662]
I would like to explore the data stored in [H2-mvstore](https://www.h2database.com/html/mvstore.html) databases with [SQL Workbench](http://sql-workbench.eu/index.html).
The connection to the database is OK 
![image](https://user-images.githubusercontent.com/1816573/73863509-81bd6000-4840-11ea-8231-25a1e48bb730.png)

But I can't explore data. No tablesfound in PUBLIC  schéma and I haven't no H2 errors.
![image](https://user-images.githubusercontent.com/1816573/73864904-b3372b00-4842-11ea-999c-2b25110adf5f.png)

Do you need a specific H2 configuration? 
For example, I have not configured any username and password to connect to the database.

I couldn't find any documentation on these H2 databases. Is there one?

**Comment by essiembre** [comment]
MVStore is the underlying storage engine used by H2, but is not a relational SQL database.    It is rather a super fast embeddable key-value store.

If you want to read from it, you can see how the HTTP Collector code does it, or have a look here for more options: http://www.h2database.com/html/mvstore.html

Otherwise, you can also change the crawl store implementation from the MVStore default to the ``JDBCCrawlDataStoreFactory``, which uses H2.  For large crawls it will definitely be slower, but you may like it anyway for the convenience.
