### ISSUE TITLE
Store all attributes of extracted Urls as metadata

### ISSUE THREAD

**Issue by LeMoussel** [Norconex/collector-http#668]
Currently, the following referrer information is stored as metadata in each document represented by the extracted URLs (ref: [GenericLinkExtractor](https://norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/impl/GenericLinkExtractor.html)): 

- Referrer reference
- Referrer link tag
- Referrer link text
- Referrer link title

It would be interesting to have all the attributes of extracted URLs stored as metadata in each document. 
e.g [class](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class) attribute -> Referrer link class, etc ...

Best regards.

Christian

**Comment by essiembre** [comment]
Marked as a feature request.  Maybe a way to carry over pretty much "anything" from a referrer document would be nice.

**Comment by LeMoussel** [comment]
Yep!
I notice you use regular expressions exclusively. Any particular reason not to use JSoup?

**Comment by essiembre** [comment]
At the time, flexibility and performance were the reasons.  Regex-based was about 10 times faster when I benchmarked it.  You have to consider that JSOUP does a lot to account for all the bad pages out there... to convert them to a good DOM-structure.   That step is not necessary with regex and generally speaking, we do not need the whole DOM created just to extract links.

That being said, several features were added to the generic link extractor since and maybe it warrants a second look.  

In any case, you have the TikaLinkExtractor that uses JSoup if you prefer that implementation.

**Comment by essiembre** [comment]
Implemented in version 3 codebase.  By default now all attributes of a referrer link will be stored with the target document.  One can disable this with a new ``#setIgnoreLinkData()`` method.

In addition, there is a new DOMLinkExtractor class that uses JSoup to extract links from HTML/XML documents.

**Comment by LeMoussel** [comment]
Thank you. 
Any idea when version 3 will be available?

**Comment by essiembre** [comment]
When ready. :-)  No ETA yet.

**Comment by LeMoussel** [comment]
:)
