### ISSUE TITLE
Is it possible to store pages that have turned "bad"?

### ISSUE THREAD

**Issue by LeMoussel** [Norconex/collector-http#670]
With [JSONFileCommitter](https://norconex.com/collectors/committer-core/latest/apidocs/com/norconex/committer/core/impl/JSONFileCommitter.html) as crawl data store, Is that possible to store all pages that have turned "bad" (Crawl state: NOT_FOUND | DELETE | BAD_STATUS) ?

**Comment by essiembre** [comment]
No, because pages with a bad status cannot be downloaded.  Thus, there is no document to store.  If you are only concerned about storing the URL for reporting purposes, have a look at [URLStatusCrawlerEventListener.](https://norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/crawler/event/impl/URLStatusCrawlerEventListener.html) and it will give you a detailed report.
