### ISSUE TITLE
Disable  REJECTED_REDIRECTED

### ISSUE THREAD

**Issue by LeMoussel** [Norconex/collector-http#673]
with these tags, it's possible to disable:
``` xml
    <!--
      REJECTED_ROBOTS_META_NOINDEX
      Establish whether to follow a page URLs or to index a given page based on in-page meta tag robot information.
      https://norconex.com/collectors/collector-http/configuration#tbl-robotsMeta
    -->
    <robotsMeta ignore="false" class="com.norconex.collector.http.robot.impl.StandardRobotsMetaProvider" />
    <!--
      REJECTED_ROBOTS_TXT
      Filter before download with RobotsTxt rules.
      https://norconex.com/collectors/collector-http/configuration#tbl-robotsTxt
    -->
    <robotsTxt ignore="false" class="com.norconex.collector.http.robot.impl.StandardRobotsTxtProvider" />
    <!--
      REJECTED_NONCANONICAL
      Detects pages with a canonical link and rejects them in favor of the canonical one.
      https://norconex.com/collectors/collector-http/configuration#tbl-canonicalLinkDetector
    -->
    <canonicalLinkDetector ignore="false" class="com.norconex.collector.http.url.impl.GenericCanonicalLinkDetector" />
```
In the same principle, it would be interesting to be able to disable `REJECTED_REDIRECTED`

Best regards.
Christian

**Comment by essiembre** [comment]
What would that disabling do?

If page A redirects to B, then B will be crawled, not A (hence the rejection of A).  For most redirects, there is no other way since the original URL (for A) returns a redirect directive and not an actual document.

If you mean to disable following redirects altogether, this can be done with 
```xml
<maxRedirects>0</maxRedirects>
```
found in [GenericHttpClientFactory](https://norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/client/impl/GenericHttpClientFactory.html) configuration.

**Comment by LeMoussel** [comment]
To know that A is redirected to B, my idea is to store the crawl data from A & B.

I build a graph, without storing the redirections, the relationships between the nodes of the graph are absent.

**e.g:**

> X -- href --> A -- R301 --> B

I identify 2 solutions:

1. Storage of nodes X, A & B and the relationships href & R301: X -- href --> A -- R301 --> B
2. Storage of nodes X, B and the relationship href (R301): X -- href (R301) --> B

I haven't figured out how to do that yet.
I'm interested in any idea. :)

**Comment by essiembre** [comment]
The redirected URLs should be available, stored under "collector.redirect-trail".
