### ISSUE TITLE
Crawling a SharePoint online site

### ISSUE THREAD

**Issue by MRC-westat** [Norconex/collector-http#675]
we are currently using the Norconex collector-http to crawl our internal SharePoint on-premise sites without any problems using NTLM authentication.
would it be possible to crawl SharePoint online sites with the same crawler?
has anyone had any success in doing this? - the authentication scheme appears totally different.

thanks
MRC-westat

**Comment by essiembre** [comment]
Can you elaborate on the authentication scheme used for the online version?

**Comment by MRC-westat** [comment]
thanks for replying to my question,
yes - I have the specs here on the authentication used in SP online.

from Microsoft - specifications are here:
https://docs.microsoft.com/en-us/sharepoint/authentication

MRC-westat

**Comment by essiembre** [comment]
My understanding is this type of authentication is for user login and is browser-based.  It requires human interaction that is hard to simulate (understandably).  You can try to simulate it using the ``PhantomJSDocumentFetcher`` but PhantomJS is no longer supported (FYI version 3 of HTTP Collector will offer the use of popular browsers).   

Ideally, for this purpose, you would grant access to SharePoint online to an application instead of a web user. I believe looking at "server-to-server" authentication may be getting you a step closer.

Not sure if the HTTP Collector has all the configurable options required to pass what would be required (like secret tokens).   You may need to extend ``GenericHttpClientFactory`` or create your own.

I suggest you ask the SharePoint community to confirm, but I suspect the easiest approach would be to set up a SharePoint location-based solution.  You can grant access to specific network locations/IPs that you trust.  Relevant info: https://docs.microsoft.com/en-us/sharepoint/control-access-based-on-network-location
