### ISSUE TITLE
queue being processed alphabetically

### ISSUE THREAD

**Issue by simonwibberley** [Norconex/collector-http#714]
Hi there,

I have a reasonable size queue of URLs from a sitemap. The references appear to be being processed alphabetically. This is particularly noticeable in this case since a number of sitemap pages incorrectly specify HTTP instead of HTTPS causing a large block of redirects instead of expected processing.

Is this expected behaviour?

Many thanks,

Simon

**Comment by essiembre** [comment]
Not really. they are usually processed in the approximate order they are defined in the sitemap.xml.   Can you share the URL to your sitemap.xml?

**Comment by simonwibberley** [comment]
OK, thanks for your response - we're still checking into this but have hit some other problems! 

The sitemap in question was either:
https://www.milenio.com/sitemap/sitemap-articles-index.xml 
or
https://www.mimorelia.com/sitemap.xml

Apologies I can't remember which. Also, this was in the case of a resumed crawl. 

Kind regards,

Simon

**Comment by essiembre** [comment]
I was able to reproduce the sorting behavior.  It turns out you are correct: the default crawl store implementation will sort its queue by document reference (URL) for optimization.  

It usually does not make much of an impact since the queue is read regularly as items are added.  There is an exception with sitemaps where ALL sitemap URLs are downloaded and queued in full before the crawler starts reading the queue (at that point they are ALL sorted).

It should not be an issue if you plan to index the entire sitemap, or if you exclude via reference filters those problematic ones you do not want.   Does this prevent the crawling of your site somehow?

Version 3 adds an `async` flag that on your `<startURLs ...>`,  when turned on, will start processing URLs as they are queued (will not wait until the entire sitemap gets queued).

**Comment by simonwibberley** [comment]
Hi Pascal - in our use case we were interested only in pages within a particular date interval, say the last week or so, and the sitemap index covers the entire history of the site so we expected to see our relevant pages sooner and in order. 

We have introduced a 'from' timestamp parameter to the StandardSitemapResolver which filters out any sitemap loc's which have a lower lastMod value - this massively reduces the amount work when indexing a large site in our use case because the vast majority of the URLs aren't considered for processing.

I'd be happy to submit this upstream in a PR if you feel it's an appropriate addition?

**Comment by essiembre** [comment]
Of course, I would be happy you submit a PR. :-)
