### ISSUE TITLE
"Don't Recrawl" resolver

### ISSUE THREAD

**Issue by simonwibberley** [Norconex/collector-http#715]
Hi there,

We're trying to implement a crawl strategy which essentially never re-crawls a URL, unless under some specific conditions. The basis for this functionality is a IRecrawlableResolver which trivially returns false.

When exploring this approach we found that on subsequent crawls the crawler would put referenced child URLs from the cached HttpCrawlData back on to the queue for processing. This happens at the last bit of beforeFinalizeDocumentProcessing() in HttpCrawler.  We expected the IRecrawlableResolver which always returns false to never put anything on the queue.

Is this expected behaviour of how recrawls should be treated? 

Many thanks,

Simon

**Comment by essiembre** [comment]
Hello, they are put in the queue, but are they actually processed/committed, or are they all rejected since "premature"?

Depending on your answer, it could be expected behavior  See, if you crawl a website and you say a page is not ready to be recrawled, the crawler does not download it and thus, cannot extract and follow its links.  It then relies on what is in the cache, to make sure a "premature" page does not prevent its children from being re-crawled (in case those are not premature).   

So when done first-pass crawling, all "orphans" (those not encountered due to being premature or else) are put back in the queue for processing to make sure they are not missed.

You could change the `<orphanStrategy>` to `IGNORE`, but they may fall off the cache (to be confirmed) and will be reattempted on a subsequent crawl, so the default `PROCESS` may be best.

Does that answer?

**Comment by simonwibberley** [comment]
Hi Pascal,

Thanks for your response. To explain out situation briefly: we identify particular pages as "articles", other page we could just call "nodes" which are used for links. Articles are either REJECTed or ACCEPTed based on content and we never want to re-crawl them. However, we do want to re-crawl "node" such as landing and listing pages. We found that articles REJECTed articles are not considered for re-crawling since they are not PROCESSed as 'valid' by the data store, and therefor not restored as having cached crawl data. 

I believe we have found a work around by ACCEPTing all articles, and instead tagging them with booleans of corresponding to the content filter criteria for the Commiter to decide whether to commit, and REJECTing nodes to ensure they are always crawled. I guess this somewhat skews ACCEPT / REJECT semantics in our situation, which is fine unless there are more fine grained status we could use?

Many thanks,

Simon

**Comment by essiembre** [comment]
Hello Simon. I am glad you found a way that works for you.

The only alternate option that comes to mind right now is to rely on the `collector.is-crawl-new` which you can try to filter on using a metadata filter.  Basically, it will be `false` if coming from the cache (i.e., previously encountered).

**Comment by simonwibberley** [comment]
OK, thanks Pascal - I'll close the issue since this is all expected behaviour. Thanks for your input nonetheless! 

All the best,

Simon
