### ISSUE TITLE
DOMTagger selector question

### ISSUE THREAD

**Issue by bennrx** [Norconex/collector-http#716]
Hello,

I'm trying to use the DomTagger to create some new fields during an http crawl.

Everything is fine with a basic dom selector like for example : 
`<dom selector ="div.class" toField="newField" />`

I've got 2 use cases I can't manage : 

How can I extract the text with a selector from this html : 
```
<div class="title">
<span>Text</span>
</div>
```

I've tried something like this but it's unsuccessful : 
`<dom selector ="div.title span" toField="newField" />`

Second use case with this html : 
Is-it a selector to match an html tag with 2 classes like this one (goal is to extract "text" ): 
`<li class="category with-link"><a href="http://xxx">Text</a></li>`

Thanks for feedback

Kind Regards

**Comment by essiembre** [comment]
I am surprised your first use case worked since `.class` in `div.class` should be the actual class name.

`div.title span` should definitely match this:

```xml
<div class="title">
<span>Text</span>
</div>
```

Your second one should get matched by this: `li.category a`.

Given "text" is what gets extracted by default, you do not need to tell it otherwise.

The underlying technology uses [JSoup](https://jsoup.org/cookbook/extracting-data/selector-syntax). Sometimes whether it treats it as HTML or XML it may do things a bit differently.  So try switching to a different parser: `<tagger ... parser="xml" ...>`.  Default is "html".

If changing the parser does not work for you, please attach a config that reproduces the issue.

**Comment by bennrx** [comment]
Hello,

Thanks for quick answer !
I've tried with the xml parser with the same result.

I'm not able to make working selectors with more than one criterion

This one work : 
`<dom selector="span.certification-date" toField="certificationDate" />`

Those don't :
```
<dom selector="div.title span" toField="title" overwrite="true" />
<dom selector="li.category.withlink a" toField="category" />
```

Here are the xml config file and a test html page : 
[test.zip](https://github.com/Norconex/collector-http/files/5317886/test.zip)

Thanks

**Comment by essiembre** [comment]
The sitemap you shared points to 2 HTML pages (`janvier2017.html` and `depannretrait.html`).  I visually inspected the source for these two files, and neither contain elements matching your second and third selectors (and only `depannretrait.html` has a match for the first one).

In other words, there is nothing to be matched, thus works as expected.  

Did you share the wrong files?

**Comment by bennrx** [comment]
Hello,

Sorry, wrong files yes. And I finally was able to manage the extraction. I close this subject.
Thanks for the help

Regards,
