### ISSUE TITLE
Why does a request sent through a local Postman Proxy result in a faulty hostname?

### ISSUE THREAD

**Issue by benlogan** [Norconex/collector-http#720]
When I send a request through a local Postman Proxy server for debugging, the request fails and the hostname seen in Postman is listed as 'false'. If I manually correct the hostname in Postman, the request works (so the headers and cookies are being persisted properly).

I've sent local web browser traffic through this same proxy and it works fine.

The proxy settings that I'm using are;

<httpClientFactory class="com.norconex.collector.http.client.impl.GenericHttpClientFactory">
        <trustAllSSLCertificates>true</trustAllSSLCertificates>
        <proxyScheme>http</proxyScheme>
        <proxyHost>localhost</proxyHost>
        <proxyPort>5555</proxyPort>
...

**Comment by benlogan** [comment]
So, I'm fairly sure this is an https tunnelling issue, because I actually don't see this problem when I use the proxy for http traffic. Can someone advise is there some special configuration that I should be using to enable tunnelling?

**Comment by benlogan** [comment]
I'm guessing we would need something like this in the norconex library - which I'm assuming isn't there?

http://svn.apache.org/viewvc/httpcomponents/oac.hc3x/trunk/src/examples/ProxyTunnelDemo.java?view=markup

**Comment by essiembre** [comment]
Hello @benlogan, you are describing an issue you are having with Postman.  What is your issue with HTTP Collector?  Do you get an error?

If you wonder how to set a proxy, have a look at the proxy settings in [GenericHttpClientFactory](https://opensource.norconex.com/collectors/http/v2/apidocs/com/norconex/collector/http/client/impl/GenericHttpClientFactory.html). 

If your problem is something else, please detail the problem and attach a configuration that reproduces the issue.
