### ISSUE TITLE
Issues getting content with webdriver (firefox and geckodriver)

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#732]
Using Collector 3.0 I get different behavior for pages within same website:

https://www.voordeelvloeren.nl/klantenservice/bezorgen-afhalen has no content from Javascript

https://www.voordeelvloeren.nl/faq/onderwerp/inmeten has some content from Javascript, but not the important part. There is a zero instead of text in the content field.

https://www.voordeelvloeren.nl/combinatie-korting has all the content I expect to see,

What is causing this and can it be fixed? Also, Is there a way to store the pre-parse content in a field to debug?

**Comment by essiembre** [comment]
Hello OkkeKlein.  I was able to reproduce with your pages. I tried adding timeouts but they do not seem to have effect since your page returns fast so it does not have to wait.  

I noticed your `<footer>` is generated via JavaScript also and it is on every page, so I configured my `WebDriverHttpFetcher` to wait for it to appear instead.  Adding this to the fetcher configuration worked just fine for me:

```
<waitForElement type="tagName" selector="footer">10 seconds</waitForElement>
```

Please give it a try and let me know.

**Comment by OkkeKlein** [comment]
Let me add https://www.voordeelvloeren.nl/faq/onderwerp/top-10 to this thread as the Firefox setup is working.

It seems that the class site__body is not being rendered/parsed. I added 

`<waitForElement type="className" selector="site__body">10 seconds</waitForElement>`

but still the same content.

**Comment by essiembre** [comment]
#733 has a solution that may apply here as well.

**Comment by OkkeKlein** [comment]
Adding a threadWait solved these issues as well.
