### ISSUE TITLE
Renindex content

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#76]
Thank you for the new version. Going to test it immediately.

Was wondering how to go about when I wanted to keepDownloads.

Is this option viable for scenario where you keep a copy of the website on disk and do normal crawls, but also be able to send all content to Solr for a reindex?.Will it for example also keep track of deleted files?

**Comment by essiembre** [comment]
The ``keepDownloads`` option simply store a copy of what the collector fetches, without any intelligence into it.  It is not a way to replicate or "clone" a website, or a way to store content backup... because the directory structure is not preserved and deletions are not taken into account.  

Deletions aside, I suppose the [Norconex Filesystem Collector](http://www.norconex.com/collectors/collector-filesystem/) could be used to re-crawl those files from disk (but you may lose the URL).   

All this being said, this could be a nice feature request. :-)

**Comment by jaanuska** [comment]
Hi,

I believe that I have similar problem to solve. I want to build a system which makes an exact cloned copy of a website and stores it locally. All links in pages have to be modified to point to an another resource on the local structure, e.g. www.example.com/resource.jpg -> //local/file/system/mirrors/www.example.com/resource.jpg. This allows users to browse the copy of the website locally.
In addition, all content needs to be sent to Solr also.
As I understand, keepDownloads option is not meant for this purpose. Is there any other way to "clone" a website to a local file system, today? If not, should I implement my own committer, using the ICommitter interface, for example?

**Comment by jaanuska** [comment]
I opened a new issue about my previous question.
