### ISSUE TITLE
Store start date or crawl date with result

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#78]
What if there is, is the easiest way to store start date of crawl and/or crawl date of document?

**Comment by essiembre** [comment]
There is typically a "Date" field from the HTTP headers that you could use, and format to your need with [DateFormatTagger](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DateFormatTagger.html).

Otherwise, nothing out-of-the-box from the collector adds that.  It would be a simple addition to create a tagger that does that (by implementing [IDocumentTagger](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/IDocumentTagger.html)).  

I think a new Tagger would be the best approach since you could tell the tagger in what field to store it, in what date format, etc. and people just add this tagger if they want to.  Do you see value sometimes in storing both the document crawl date (mostly different for each doc) and the crawler start date (same for all doc)?  Because for the second, we'll have to think what to store when resuming a crawl (the initial start date? the resume date? both?).

I am marking this as a feature request to have a TimestampTagger (or similar name).

**Comment by OkkeKlein** [comment]
It's basically for troubleshooting. So when something is wrong you have a timeframe. For this the "Date" field should be enough. (Dealing with so many dates, I forgot about this one)

The start date might be useful in some cases. Nice to have, but not necessary.

**Comment by essiembre** [comment]
Since I turned this one into a feature request, let's leave it open.

**Comment by essiembre** [comment]
A new [CurrentDateTagger](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/CurrentDateTagger.html) class was added to Norconex HTTP Collector [2.2.0-SNAPSHOT](http://www.norconex.com/collectors/collector-http/download).

**Comment by essiembre** [comment]
Norconex HTTP Collector 2.2.0 official release is out. It includes this fix. You can download it [here](http://www.norconex.com/collectors/collector-http/download).
