### ISSUE TITLE
Example SharePoint 2010/2013 (NTLM?) crawl configuration?

### ISSUE THREAD

**Issue by chillwinston** [Norconex/collector-http#802]
Hi Pascal - we've tried a variety of V3 authorisation settings, none of which have worked thus far. 

Broadly, our config is:

<authentication>
  <method>ntlm</method>
 <credentials>
    <username> ...
    <password> ...
  </credentials>
  <domain>ECE</domain>
</authentication>

We've also tried Kerberos as the method, <realm> (of ECE) and <workstation> in case that was the issue.     Nothing has worked thus far.   We'd love some feedback on whether we have at least the "expected to work" config correct.

Many thanks

**Comment by essiembre** [comment]
Since each environment can be setup a bit differently, I would have a hard time telling you exactly what you need, but at a minimum, you would need something like this as part of your crawler configuration:

```xml
<httpFetchers>
  <fetcher class="com.norconex.collector.http.fetch.impl.GenericHttpFetcher">
    <authentication>
      <method>ntlm</method>
      <credentials>
        <username>...</username>
        <password>...</password>
      </credentials>
      <host>
        <name>...</name>
        <port>...</port>
      </host>
      <workstation>...</workstation>
      <domain>...</domain>
    </authentication>
  </fetcher>
</httpFetchers>
```

The crawler offers generic NTLM support thanks to the Apache HttpClient library. It supports a few different NTML protocol versions but may not support the one you are using.  Details on supported versions: https://hc.apache.org/httpcomponents-client-4.5.x/ntlm.html

You may also want to check with your system administrator to see if there are extra security layers or special configuration requirements you need to be aware of.  Maybe you need to pass custom HTTP headers, or go through a proxy (look at  `<headers>` and `<proxySettings>`). 

Finally, if all fails you can try to find out if they offer a way to access your site via other authentication methods or maybe even white-list the crawler IP or some other workaround.  There might be other network conditions you are not meeting with NTLM alone.

If you get a specific error from the crawler that suggests a bug, feel free to share your config here and the exact error/logs so we can look for a fix.

Best of luck!

**Comment by chillwinston** [comment]
Thanks Pascal  !  With

      <host>
        <name>...</name>
        <port>...</port>
      </host>

I'm unsure what's expected here - is it the AD server host name and
port ?   Is the domain the full AD domain or just the initial part of
it - eg "intranet.mycompany.com" - the short domain name used in
logins is just "intranet" - eg "intranet\myusername" is used as my
login name.  Is it "intranet" or intranet.mycompany.com (eg FQDN or
short)


   - Does the username include the short domain name - eg
"intranet\myusername" , or is it just "myusername" as the domain is
specified separately.  Workstation I'm assuming is either the FQDN of
the workstation - eg "mypc.intranet.mycompany.com" - or just "mypc".

---

   - *Domain *- Is it a FQDN or short ?  Is this used as part of the
login for username - eg it supplies "intranet" as part of
"intranet\myusername", or is it used for some other purpose?
   - *Method *- I'm also assuming that method is either "ntlm" or
"kerberos" depending on whether Kerb or NTLM auth is enabled, though
I'm less sure about that.

Sorry - this is why I'd requested an example, as all the above
questions clarify how each of the fields are used.  An example would
clarify much of my questions :)

Many thanks !

**Comment by leonardoobay** [comment]
did anyone have any updates on this I am also trying to crawl through a internal sharepoint site?
