### ISSUE TITLE
HTML ReferenceFilter Based On Anchor Attributes

### ISSUE THREAD

**Issue by gwque** [Norconex/collector-http#806]
Can the crawler of html documents filter references by attributes of the anchor <a> tag? Instead of the typical regex ReferenceFilter that basically works off of the href attribute, I'd like to filter by the class attribute value (or even ID) of that tag based on a regex. Any ideas?

**Comment by essiembre** [comment]
Instead of filtering them out, one solution could be to avoid extracting them in the first place. Have a look at [HtmlLinkExtractor](https://opensource.norconex.com/crawlers/web/v3/apidocs/com/norconex/collector/http/link/impl/HtmlLinkExtractor.html) and [DOMLinkExtractor](https://opensource.norconex.com/crawlers/web/v3/apidocs/com/norconex/collector/http/link/impl/DOMLinkExtractor.html). They both offer ways to define CSS-style selectors to have more control on what gets extracted.

Taking `DOMLinkExtractor` for example, it could look like the following (not tested).  Assuming this tag: 

```html
<a href="https://example.com/blah.html" id="exclude_me">click here</a>
```

```xml

 <linkExtractors>
    <extractor class="DOMLinkExtractor">
        <linkSelector extract="attr(href)">a:not(id='exclude_me')</linkSelector>
    </extractor>
  </linkExtractors>
```

Remove the `not:` if you want only those that match. You should look at other configuration options for these link extractors.  Adapt to your needs.

**Comment by gwque** [comment]
Thank you for the suggestion. I appreciate it.  I will definitely look at that if I can get past another issue.
