### ISSUE TITLE
GenericHttpFetcher and WebDriverHttpFetcher

### ISSUE THREAD

**Issue by angelo337** [Norconex/collector-http#808]
hi there

we are trying to use Collector version 3.0 with chrome in this configuration:

>  
      <httpFetchers>

           <fetcher class="GenericHttpFetcher">
                  <forceContentTypeDetection>true</forceContentTypeDetection> 
                  <forceCharsetDetection>true</forceCharsetDetection>
           </fetcher>
          <fetcher class="com.norconex.collector.http.fetch.impl.webdriver.WebDriverHttpFetcher">
             <browser>chrome</browser>
             <driverPath>./webdriver/chromedriver</driverPath>
             <screenshot>
                     <targetDir field="screenshot" structure="url2path">
                             ./examples-output/screenshoot
                     </targetDir>
             </screenshot>
         </fetcher>
      </httpFetchers>

to detect document encoding however when we activate GenericHttpFetcher in there all screenshot functionality is gone , not working at all.
could you please let check for me if there is and issue in my config of a bug ?
tanks a lot 
angelo

**Comment by essiembre** [comment]
The behaviour you describe is by design.  A document is fetched at most once. Configuring more than one fetcher is a fallback mechanism in case of failure or unsupported URLs. For each URL encountered, your configured fetchers will attempt to get a document in the order configured until one succeeds.  In your case, the first fetcher (`GenericHttpFetcher`) successfully fetches a document, so the job is done, and the second fetcher (`WebDriverHttpFetcher`) is never invoked. 

Could you use the WebDriver fetcher only?  Given browsers hardly support getting anything other than text/HTML via WebDrivers, are you concerned about failing to get non-HTML pages?  If so, I suggest you try reversing your fetcher order and add `<referenceFilters>` to the WebDriver fetcher only to be used for HTML.  This would only work if you can find a way to identify HTML vs non-HTML via URL alone.  For HTML pages, most sites either have the `.html` extension or no extension at all, whereas non-HTML pages pretty much always have an extension in their URL.  So you can restrict the Web Driver fetcher to this pattern.  

The net effect will be the WebDriver skipping non-HTML pages and letting the next one configured (Generic fetcher) handle them.

**Comment by angelo337** [comment]
thank you for your quick response, 

My problem is that the GENERIC detects correctly the encoding configuration, while the WEB detects the JavaScript contents, so I set the extraction order so that the encoding will be detected correctly, but it does not extract the JS content from the page.
Is there any way that the WEB can detect the configuration of Charset and ContentType? please

Thanks a lot
Angelo

**Comment by essiembre** [comment]
My proposed solution should be able to accommodate your use case.  The Web Driver fetcher should automatically set the content type to `text/html`.  The importer should also detect the content type when parsing the document.

Also, if the Generic fetcher works fine for you on non-HTML files, you can assume HTML when the content type is not set.  You can add it using [ConstantTagger](https://opensource.norconex.com/importer/v3/apidocs/com/norconex/importer/handler/tagger/impl/ConstantTagger.html#nx-xml-usage-heading) in the importer module.   Example (post-parse):

```xml
<!-- This will set text/html only if not already set (in case Web Driver Fetcher does not do it): -->
<handler class="ConstantTagger" onSet="optional">
  <constant name="document.contentType">text/html</constant>
</handler>
```

**Comment by angelo337** [comment]
Hi Pascal,
I just test a variant of your solution, and it work for content type, however using that for with Charset does not work, do you have an idea how to correct detect it?
thanks a lot
Angelo

**Comment by essiembre** [comment]
For the Charset, it should be set automatically by the Importer module under the metadata field `document.contentEncoding`.  Are you excluding that field?

Also, it is worth noting that the Importer module will convert all extracted text to UTF-8 (or at least attempt to).  So the moment it reaches your Committer and your target repository it should always be UTF-8.

**Comment by angelo337** [comment]
hi there
thanks for your answer, I get that importer try to cover to UTF8 however is not happening with all fields, in particular with a file that I extract with preprocessor, 

>     "breadcrumb_split": [ "Inicio Â__AseguramientoÂ__Procesos"],

as you can see this "Â" symbol is not properly encode.
and when I use the Generic work fine, however do not work with all javascript on the page

could you please point me out some resource or idea to fix that?

thanks
Angelo

**Comment by essiembre** [comment]
For fields, look at the Importer [CharsetTagger](https://opensource.norconex.com/importer/v3/apidocs/com/norconex/importer/handler/tagger/impl/CharsetTagger.html#nx-xml-usage-heading).

It can convert any field text to a specific character set. If you do not specify the source charset, it will detect it for you before converting it to your chosen charset. Example:

```xml
<handler class="CharsetTagger" targetCharset="UTF-8">
  <fieldMatcher>myField</fieldMatcher>
</handler>
```
Does that work for you?

**Comment by angelo337** [comment]
hi there
thanks for your answer, is working most of the time (around 90%) but that is jus good for me
thanks again.
Angelo

**Comment by essiembre** [comment]
Great! If the 10% remaining ever bothers you, open another ticket with details in case something can be done.
