### ISSUE TITLE
 Unsuccessful stage execution ReferenceFiltersStage

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#84]
Even though it's working, logs show a message. 
```
DEBUG - Unsuccessful stage execution: com.norconex.collector.core.pipeline.queue.ReferenceFiltersStage@79ad4ae5
INFO -           REJECTED_FILTER: http://www.test.com
```

**Comment by essiembre** [comment]
This is normal behavior.  It simply tells you a URL has been rejected according to one of your filters.  The "Unsuccessful stage execution" DEBUG message simply tells you hat stage caused the rejection.  I can see it happens when reference filters are applied.  Those are typically set using ``<referenceFilters>``.

If you do not want to be notified of every rejection (there are usually TONS), you can change the classes/log4j.properties file to set the log level to WARN, or ERROR for the events you do not want to see.

With this info on hand, do you have a question/issue to report or shall we close this issue?

**Comment by OkkeKlein** [comment]
Yes, if it's normal behavior, I'll raise the LOG level.
