### ISSUE TITLE
One Collector with several crawlers or a crawler with several URLs

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#93]
What is the difference in performace between one Collector with several crawlers and a crawler with several URLs both solving the same need?. Do they both run one by one or in parallel?. And applying several threads to both solutions?. Pros and cons.

**Comment by essiembre** [comment]
It often comes down to whatever is easier to maintain for you. Sometimes it could be more an art than a science. :-) The following are not fixed rules, but random things that can help you decide the best approach for you:

* Ensure all sites URLs you put under the same crawler share the same settings or crawl requirements.  For instance, two sites may need different authentication, one you may want to strip its header on every page, the other the sidebar, etc. Your config settings may not always apply to each sites and cause trouble.  In that case set them in different crawlers/collectors.
* What if you have 1 of your 10 sites under 1 crawler failing to get crawled properly because of a bad configuration or else?  Then you will have to either restart the crawl with the 10 URLs just to troubleshoot that one, or you may comment the other ones while you troubleshoot.  None are always ideal.  You may want to separate them to avoid this, especially when in heavy development stage.
* The scenario above also applies if you have multiple crawlers defined.  If only one needs restarting, you'll be forced to restart them all. Not always desired.  Separating them in different collectors can work best.
* Do you have 1000+ sites to crawl?  It maybe a big challenge to apply the above tips with so many.  You do not want tons of different crawlers/collectors defined.  In which case, it may be a good mixed approach to put long-running, or more complex sites in their own crawler or collector configuration, and put several smaller simple/sites together.
Normally, each collector instance runs in its own JVM.  Resources are shared between each crawlers/sites you have configured for each.  As opposed to try boosting the JVM settings, you may decide it is simpler to create more than one collector and spread the load that way.
* On the opposite, you do not want to have 1 JVM running for each start URL you have it you have thousands... so you'll want to do some grouping.
* Hardware resources. Maybe you are just doing too much for one server, which is problematic.  You may want to use multiple servers to spread the load.  This is obviously a very good reason to have more than one collector.
* Putting the above considerations aside, one good reason for having multiple crawlers under the same collector, is if most are sharing common values, with a few exceptions only.  You can define most settings only once under ``<crawlerDefaults>`` and have the specifics under each specific crawlers.  On the other hand, since you can include configuration fragments into your config, it also gives you a way to reuse configuration snippets.

There are certainly several other factors to consider, but those are the ones I could think of at the moment.

**Comment by csaezl** [comment]
Valuable information.
If you defined two crawlers inside a collector, are they processed in parallel or sequential?. The same for the URLs inside a crawler, although I supose in this case is sequential.

**Comment by essiembre** [comment]
**Two crawlers in one Collector:** in parallel.  So be careful the number of threads you specify in each, they will add up.

**URLs inside a crawler:** Mixed.  The first thing that happens, is each "start URL" you specified are put in a queue as a first step.  Then there is a pool of threads (the number you specified) that sequentially take the next URL in the queue.  New URLs found are added to the end of the queue, and when a thread is free, it will pick up the next one from the beginning.   So the queue is *read* sequentially, but multiple URLs can be *processed* at the same time (given your number of threads).   The time it takes to download and process each documents will vary.  This means it is possible the order they are read do not match the order they are sent to your Committer.  But generally speaking, they should roughly be in the same order.  This should not matter really, just giving a complete answer. :-)

**Comment by csaezl** [comment]
Thank you very much
